(* infotheo: information theory and error-correcting codes in Rocq            *)
(* Copyright (C) 2025 infotheo authors, license: LGPL-2.1-or-later            *)
(******************************************************************************)
(* psl211_blocks: the literal data of the twelve-card chirality instance      *)
(*                                                                            *)
(* Twelve positions 0..11. Three letter tables: reverse each quarter (r4),    *)
(* Monge-shuffle each half (m6) and its inverse, milk-shuffle each half.     *)
(* Two 132-row tables of ascending six-lists: the two Steiner systems         *)
(* S(5,6,12) on the twelve positions, the hexad system of M12 and its mirror. *)
(* A sixth table transports the non-square scaling of P^1(F_11) to this      *)
(* labelling; it exchanges the two systems and lies outside the group.       *)
(*                                                                            *)
(* Every certificate below is a vm_compute on these tables:                   *)
(*   psl211_design5_mirrorT/_hexadT == each table is a 5-(12,6,1) design     *)
(*   psl211_stable_*T               == r4 and m6 map each table into itself   *)
(*   psl211_count_okT               == equal pattern counts, coalitions <= 5  *)
(*   psl211_leak6                   == a size-6 pattern with unequal counts   *)
(*   psl211_chirality_swapT         == the transported scaling swaps the two  *)
(******************************************************************************)

From mathcomp Require Import ssreflect ssrbool ssrfun eqtype ssrnat seq path.

Set Implicit Arguments.
Unset Strict Implicit.
Import Prenex Implicits.

(** psl211_r4_tbl — the letter reversing each of the three four-position
    quarters (0..3, 4..7, 8..11) of the twelve positions. *)
Definition psl211_r4_tbl    : seq nat := [:: 3; 2; 1; 0; 7; 6; 5; 4; 11; 10; 9; 8].
(** psl211_m6_tbl — the letter applying a Monge shuffle to each of the two
    six-position halves (0..5, 6..11). *)
Definition psl211_m6_tbl    : seq nat := [:: 3; 2; 4; 1; 5; 0; 9; 8; 10; 7; 11; 6].
(** psl211_milk6_tbl — the letter applying the inverse (milk) shuffle to each
    six-position half; psl211_m6_tbl and psl211_milk6_tbl are mutual inverses
    on each half. *)
Definition psl211_milk6_tbl : seq nat := [:: 5; 3; 1; 0; 2; 4; 11; 9; 7; 6; 8; 10].
(** psl211_nonsquare_tbl — the transport, under the relabelling
    pi = (0,5,11,9,6,2,8,7,4,1,10,3), of the non-square scaling z |-> 2z of
    P^1(F_11) to the twelve positions. It exchanges psl211_mirror_tbl and
    psl211_hexad_tbl below (psl211_chirality_swapT) and lies outside the
    group generated by psl211_r4_tbl and psl211_m6_tbl: it is the PGL(2,11)
    letter that PSL(2,11) lacks. *)
Definition psl211_nonsquare_tbl : seq nat := [:: 0; 10; 2; 7; 9; 8; 1; 11; 6; 5; 3; 4].

(** psl211_mirror_tbl — the 132 blocks of one Steiner system S(5,6,12) on the
    twelve positions, the mirror image of psl211_hexad_tbl under
    psl211_nonsquare_tbl. *)
Definition psl211_mirror_tbl : seq (seq nat) := [::
  [:: 0; 1; 2; 3; 4; 10];
  [:: 0; 1; 2; 3; 5; 8];
  [:: 0; 1; 2; 3; 6; 11];
  [:: 0; 1; 2; 3; 7; 9];
  [:: 0; 1; 2; 4; 5; 6];
  [:: 0; 1; 2; 4; 7; 11];
  [:: 0; 1; 2; 4; 8; 9];
  [:: 0; 1; 2; 5; 7; 10];
  [:: 0; 1; 2; 5; 9; 11];
  [:: 0; 1; 2; 6; 7; 8];
  [:: 0; 1; 2; 6; 9; 10];
  [:: 0; 1; 2; 8; 10; 11];
  [:: 0; 1; 3; 4; 5; 7];
  [:: 0; 1; 3; 4; 6; 8];
  [:: 0; 1; 3; 4; 9; 11];
  [:: 0; 1; 3; 5; 6; 9];
  [:: 0; 1; 3; 5; 10; 11];
  [:: 0; 1; 3; 6; 7; 10];
  [:: 0; 1; 3; 7; 8; 11];
  [:: 0; 1; 3; 8; 9; 10];
  [:: 0; 1; 4; 5; 8; 11];
  [:: 0; 1; 4; 5; 9; 10];
  [:: 0; 1; 4; 6; 7; 9];
  [:: 0; 1; 4; 6; 10; 11];
  [:: 0; 1; 4; 7; 8; 10];
  [:: 0; 1; 5; 6; 7; 11];
  [:: 0; 1; 5; 6; 8; 10];
  [:: 0; 1; 5; 7; 8; 9];
  [:: 0; 1; 6; 8; 9; 11];
  [:: 0; 1; 7; 9; 10; 11];
  [:: 0; 2; 3; 4; 5; 9];
  [:: 0; 2; 3; 4; 6; 7];
  [:: 0; 2; 3; 4; 8; 11];
  [:: 0; 2; 3; 5; 6; 10];
  [:: 0; 2; 3; 5; 7; 11];
  [:: 0; 2; 3; 6; 8; 9];
  [:: 0; 2; 3; 7; 8; 10];
  [:: 0; 2; 3; 9; 10; 11];
  [:: 0; 2; 4; 5; 7; 8];
  [:: 0; 2; 4; 5; 10; 11];
  [:: 0; 2; 4; 6; 8; 10];
  [:: 0; 2; 4; 6; 9; 11];
  [:: 0; 2; 4; 7; 9; 10];
  [:: 0; 2; 5; 6; 7; 9];
  [:: 0; 2; 5; 6; 8; 11];
  [:: 0; 2; 5; 8; 9; 10];
  [:: 0; 2; 6; 7; 10; 11];
  [:: 0; 2; 7; 8; 9; 11];
  [:: 0; 3; 4; 5; 6; 11];
  [:: 0; 3; 4; 5; 8; 10];
  [:: 0; 3; 4; 6; 9; 10];
  [:: 0; 3; 4; 7; 8; 9];
  [:: 0; 3; 4; 7; 10; 11];
  [:: 0; 3; 5; 6; 7; 8];
  [:: 0; 3; 5; 7; 9; 10];
  [:: 0; 3; 5; 8; 9; 11];
  [:: 0; 3; 6; 7; 9; 11];
  [:: 0; 3; 6; 8; 10; 11];
  [:: 0; 4; 5; 6; 7; 10];
  [:: 0; 4; 5; 6; 8; 9];
  [:: 0; 4; 5; 7; 9; 11];
  [:: 0; 4; 6; 7; 8; 11];
  [:: 0; 4; 8; 9; 10; 11];
  [:: 0; 5; 6; 9; 10; 11];
  [:: 0; 5; 7; 8; 10; 11];
  [:: 0; 6; 7; 8; 9; 10];
  [:: 1; 2; 3; 4; 5; 11];
  [:: 1; 2; 3; 4; 6; 9];
  [:: 1; 2; 3; 4; 7; 8];
  [:: 1; 2; 3; 5; 6; 7];
  [:: 1; 2; 3; 5; 9; 10];
  [:: 1; 2; 3; 6; 8; 10];
  [:: 1; 2; 3; 7; 10; 11];
  [:: 1; 2; 3; 8; 9; 11];
  [:: 1; 2; 4; 5; 7; 9];
  [:: 1; 2; 4; 5; 8; 10];
  [:: 1; 2; 4; 6; 7; 10];
  [:: 1; 2; 4; 6; 8; 11];
  [:: 1; 2; 4; 9; 10; 11];
  [:: 1; 2; 5; 6; 8; 9];
  [:: 1; 2; 5; 6; 10; 11];
  [:: 1; 2; 5; 7; 8; 11];
  [:: 1; 2; 6; 7; 9; 11];
  [:: 1; 2; 7; 8; 9; 10];
  [:: 1; 3; 4; 5; 6; 10];
  [:: 1; 3; 4; 5; 8; 9];
  [:: 1; 3; 4; 6; 7; 11];
  [:: 1; 3; 4; 7; 9; 10];
  [:: 1; 3; 4; 8; 10; 11];
  [:: 1; 3; 5; 6; 8; 11];
  [:: 1; 3; 5; 7; 8; 10];
  [:: 1; 3; 5; 7; 9; 11];
  [:: 1; 3; 6; 7; 8; 9];
  [:: 1; 3; 6; 9; 10; 11];
  [:: 1; 4; 5; 6; 7; 8];
  [:: 1; 4; 5; 6; 9; 11];
  [:: 1; 4; 5; 7; 10; 11];
  [:: 1; 4; 6; 8; 9; 10];
  [:: 1; 4; 7; 8; 9; 11];
  [:: 1; 5; 6; 7; 9; 10];
  [:: 1; 5; 8; 9; 10; 11];
  [:: 1; 6; 7; 8; 10; 11];
  [:: 2; 3; 4; 5; 6; 8];
  [:: 2; 3; 4; 5; 7; 10];
  [:: 2; 3; 4; 6; 10; 11];
  [:: 2; 3; 4; 7; 9; 11];
  [:: 2; 3; 4; 8; 9; 10];
  [:: 2; 3; 5; 6; 9; 11];
  [:: 2; 3; 5; 7; 8; 9];
  [:: 2; 3; 5; 8; 10; 11];
  [:: 2; 3; 6; 7; 8; 11];
  [:: 2; 3; 6; 7; 9; 10];
  [:: 2; 4; 5; 6; 7; 11];
  [:: 2; 4; 5; 6; 9; 10];
  [:: 2; 4; 5; 8; 9; 11];
  [:: 2; 4; 6; 7; 8; 9];
  [:: 2; 4; 7; 8; 10; 11];
  [:: 2; 5; 6; 7; 8; 10];
  [:: 2; 5; 7; 9; 10; 11];
  [:: 2; 6; 8; 9; 10; 11];
  [:: 3; 4; 5; 6; 7; 9];
  [:: 3; 4; 5; 7; 8; 11];
  [:: 3; 4; 5; 9; 10; 11];
  [:: 3; 4; 6; 7; 8; 10];
  [:: 3; 4; 6; 8; 9; 11];
  [:: 3; 5; 6; 7; 10; 11];
  [:: 3; 5; 6; 8; 9; 10];
  [:: 3; 7; 8; 9; 10; 11];
  [:: 4; 5; 6; 8; 10; 11];
  [:: 4; 5; 7; 8; 9; 10];
  [:: 4; 6; 7; 9; 10; 11];
  [:: 5; 6; 7; 8; 9; 11]].

(** psl211_hexad_tbl — the 132 blocks of the hexad system of M12 on the twelve
    positions, the second Steiner system S(5,6,12). *)
Definition psl211_hexad_tbl : seq (seq nat) := [::
  [:: 0; 1; 2; 3; 4; 11];
  [:: 0; 1; 2; 3; 5; 10];
  [:: 0; 1; 2; 3; 6; 9];
  [:: 0; 1; 2; 3; 7; 8];
  [:: 0; 1; 2; 4; 5; 9];
  [:: 0; 1; 2; 4; 6; 8];
  [:: 0; 1; 2; 4; 7; 10];
  [:: 0; 1; 2; 5; 6; 7];
  [:: 0; 1; 2; 5; 8; 11];
  [:: 0; 1; 2; 6; 10; 11];
  [:: 0; 1; 2; 7; 9; 11];
  [:: 0; 1; 2; 8; 9; 10];
  [:: 0; 1; 3; 4; 5; 8];
  [:: 0; 1; 3; 4; 6; 7];
  [:: 0; 1; 3; 4; 9; 10];
  [:: 0; 1; 3; 5; 6; 11];
  [:: 0; 1; 3; 5; 7; 9];
  [:: 0; 1; 3; 6; 8; 10];
  [:: 0; 1; 3; 7; 10; 11];
  [:: 0; 1; 3; 8; 9; 11];
  [:: 0; 1; 4; 5; 6; 10];
  [:: 0; 1; 4; 5; 7; 11];
  [:: 0; 1; 4; 6; 9; 11];
  [:: 0; 1; 4; 7; 8; 9];
  [:: 0; 1; 4; 8; 10; 11];
  [:: 0; 1; 5; 6; 8; 9];
  [:: 0; 1; 5; 7; 8; 10];
  [:: 0; 1; 5; 9; 10; 11];
  [:: 0; 1; 6; 7; 8; 11];
  [:: 0; 1; 6; 7; 9; 10];
  [:: 0; 2; 3; 4; 5; 7];
  [:: 0; 2; 3; 4; 6; 10];
  [:: 0; 2; 3; 4; 8; 9];
  [:: 0; 2; 3; 5; 6; 8];
  [:: 0; 2; 3; 5; 9; 11];
  [:: 0; 2; 3; 6; 7; 11];
  [:: 0; 2; 3; 7; 9; 10];
  [:: 0; 2; 3; 8; 10; 11];
  [:: 0; 2; 4; 5; 6; 11];
  [:: 0; 2; 4; 5; 8; 10];
  [:: 0; 2; 4; 6; 7; 9];
  [:: 0; 2; 4; 7; 8; 11];
  [:: 0; 2; 4; 9; 10; 11];
  [:: 0; 2; 5; 6; 9; 10];
  [:: 0; 2; 5; 7; 8; 9];
  [:: 0; 2; 5; 7; 10; 11];
  [:: 0; 2; 6; 7; 8; 10];
  [:: 0; 2; 6; 8; 9; 11];
  [:: 0; 3; 4; 5; 6; 9];
  [:: 0; 3; 4; 5; 10; 11];
  [:: 0; 3; 4; 6; 8; 11];
  [:: 0; 3; 4; 7; 8; 10];
  [:: 0; 3; 4; 7; 9; 11];
  [:: 0; 3; 5; 6; 7; 10];
  [:: 0; 3; 5; 7; 8; 11];
  [:: 0; 3; 5; 8; 9; 10];
  [:: 0; 3; 6; 7; 8; 9];
  [:: 0; 3; 6; 9; 10; 11];
  [:: 0; 4; 5; 6; 7; 8];
  [:: 0; 4; 5; 7; 9; 10];
  [:: 0; 4; 5; 8; 9; 11];
  [:: 0; 4; 6; 7; 10; 11];
  [:: 0; 4; 6; 8; 9; 10];
  [:: 0; 5; 6; 7; 9; 11];
  [:: 0; 5; 6; 8; 10; 11];
  [:: 0; 7; 8; 9; 10; 11];
  [:: 1; 2; 3; 4; 5; 6];
  [:: 1; 2; 3; 4; 7; 9];
  [:: 1; 2; 3; 4; 8; 10];
  [:: 1; 2; 3; 5; 7; 11];
  [:: 1; 2; 3; 5; 8; 9];
  [:: 1; 2; 3; 6; 7; 10];
  [:: 1; 2; 3; 6; 8; 11];
  [:: 1; 2; 3; 9; 10; 11];
  [:: 1; 2; 4; 5; 7; 8];
  [:: 1; 2; 4; 5; 10; 11];
  [:: 1; 2; 4; 6; 7; 11];
  [:: 1; 2; 4; 6; 9; 10];
  [:: 1; 2; 4; 8; 9; 11];
  [:: 1; 2; 5; 6; 8; 10];
  [:: 1; 2; 5; 6; 9; 11];
  [:: 1; 2; 5; 7; 9; 10];
  [:: 1; 2; 6; 7; 8; 9];
  [:: 1; 2; 7; 8; 10; 11];
  [:: 1; 3; 4; 5; 7; 10];
  [:: 1; 3; 4; 5; 9; 11];
  [:: 1; 3; 4; 6; 8; 9];
  [:: 1; 3; 4; 6; 10; 11];
  [:: 1; 3; 4; 7; 8; 11];
  [:: 1; 3; 5; 6; 7; 8];
  [:: 1; 3; 5; 6; 9; 10];
  [:: 1; 3; 5; 8; 10; 11];
  [:: 1; 3; 6; 7; 9; 11];
  [:: 1; 3; 7; 8; 9; 10];
  [:: 1; 4; 5; 6; 7; 9];
  [:: 1; 4; 5; 6; 8; 11];
  [:: 1; 4; 5; 8; 9; 10];
  [:: 1; 4; 6; 7; 8; 10];
  [:: 1; 4; 7; 9; 10; 11];
  [:: 1; 5; 6; 7; 10; 11];
  [:: 1; 5; 7; 8; 9; 11];
  [:: 1; 6; 8; 9; 10; 11];
  [:: 2; 3; 4; 5; 8; 11];
  [:: 2; 3; 4; 5; 9; 10];
  [:: 2; 3; 4; 6; 7; 8];
  [:: 2; 3; 4; 6; 9; 11];
  [:: 2; 3; 4; 7; 10; 11];
  [:: 2; 3; 5; 6; 7; 9];
  [:: 2; 3; 5; 6; 10; 11];
  [:: 2; 3; 5; 7; 8; 10];
  [:: 2; 3; 6; 8; 9; 10];
  [:: 2; 3; 7; 8; 9; 11];
  [:: 2; 4; 5; 6; 7; 10];
  [:: 2; 4; 5; 6; 8; 9];
  [:: 2; 4; 5; 7; 9; 11];
  [:: 2; 4; 6; 8; 10; 11];
  [:: 2; 4; 7; 8; 9; 10];
  [:: 2; 5; 6; 7; 8; 11];
  [:: 2; 5; 8; 9; 10; 11];
  [:: 2; 6; 7; 9; 10; 11];
  [:: 3; 4; 5; 6; 7; 11];
  [:: 3; 4; 5; 6; 8; 10];
  [:: 3; 4; 5; 7; 8; 9];
  [:: 3; 4; 6; 7; 9; 10];
  [:: 3; 4; 8; 9; 10; 11];
  [:: 3; 5; 6; 8; 9; 11];
  [:: 3; 5; 7; 9; 10; 11];
  [:: 3; 6; 7; 8; 10; 11];
  [:: 4; 5; 6; 9; 10; 11];
  [:: 4; 5; 7; 8; 10; 11];
  [:: 4; 6; 7; 8; 9; 11];
  [:: 5; 6; 7; 8; 9; 10]].

(* Ascending code lists of size k with entries in [lo, 12). *)
Fixpoint psl211_asc_lists (k lo : nat) : seq (seq nat) :=
  match k with
  | 0 => [:: [::]]
  | k'.+1 =>
    flatten [seq [seq a :: L | L <- psl211_asc_lists k' a.+1]
            | a <- iota lo (12 - lo)]
  end.

(** psl211_subsets k — every ascending k-list of codes below twelve. *)
Definition psl211_subsets (k : nat) : seq (seq nat) := psl211_asc_lists k 0.

(** psl211_size_subsets5 — there are exactly 792 ascending five-lists of
    codes below twelve. *)
Lemma psl211_size_subsets5 : size (psl211_subsets 5) = 792.
Proof. by vm_compute. Qed.

(* Sublist test on sorted lists. *)
Definition psl211_subl (S R : seq nat) : bool := all (fun x => x \in R) S.

(** psl211_design5_ok tbl — every five-list lies in exactly one row of tbl. *)
Definition psl211_design5_ok (tbl : seq (seq nat)) : bool :=
  all (fun S => count (fun R => psl211_subl S R) tbl == 1) (psl211_subsets 5).

(** psl211_design5_mirrorT — psl211_mirror_tbl is a 5-(12,6,1) design: every
    five-subset of the twelve positions lies in exactly one block. *)
Lemma psl211_design5_mirrorT : psl211_design5_ok psl211_mirror_tbl.
Proof. by vm_compute. Qed.
(** psl211_design5_hexadT — psl211_hexad_tbl is a 5-(12,6,1) design: every
    five-subset of the twelve positions lies in exactly one block. *)
Lemma psl211_design5_hexadT : psl211_design5_ok psl211_hexad_tbl.
Proof. by vm_compute. Qed.

(* The image of a row under a letter table, sorted. *)
Definition psl211_map_row (g : seq nat) (R : seq nat) : seq nat :=
  sort leq [seq nth 0 g x | x <- R].

(** psl211_stable_ok g tbl — g maps every row of tbl to a row of tbl. *)
Definition psl211_stable_ok (g : seq nat) (tbl : seq (seq nat)) : bool :=
  all (fun R => psl211_map_row g R \in tbl) tbl.

(** psl211_stable_r4_mirrorT — psl211_r4_tbl maps psl211_mirror_tbl into
    itself. *)
Lemma psl211_stable_r4_mirrorT : psl211_stable_ok psl211_r4_tbl psl211_mirror_tbl.
Proof. by vm_compute. Qed.
(** psl211_stable_r4_hexadT — psl211_r4_tbl maps psl211_hexad_tbl into
    itself. *)
Lemma psl211_stable_r4_hexadT : psl211_stable_ok psl211_r4_tbl psl211_hexad_tbl.
Proof. by vm_compute. Qed.
(** psl211_stable_m6_mirrorT — psl211_m6_tbl maps psl211_mirror_tbl into
    itself. *)
Lemma psl211_stable_m6_mirrorT : psl211_stable_ok psl211_m6_tbl psl211_mirror_tbl.
Proof. by vm_compute. Qed.
(** psl211_stable_m6_hexadT — psl211_m6_tbl maps psl211_hexad_tbl into
    itself. *)
Lemma psl211_stable_m6_hexadT : psl211_stable_ok psl211_m6_tbl psl211_hexad_tbl.
Proof. by vm_compute. Qed.

(** psl211_chirality_swapT — the transported non-square scaling carries every
    mirror row to a hexad row and every hexad row to a mirror row: the
    PGL(2,11) letter that PSL(2,11) lacks exchanges the two secret classes. *)
Lemma psl211_chirality_swapT :
  psl211_stable_ok psl211_nonsquare_tbl psl211_mirror_tbl = false /\
  all (fun R => psl211_map_row psl211_nonsquare_tbl R \in psl211_hexad_tbl)
      psl211_mirror_tbl /\
  all (fun R => psl211_map_row psl211_nonsquare_tbl R \in psl211_mirror_tbl)
      psl211_hexad_tbl.
Proof. by vm_compute. Qed.

(* Intersection of a sorted row with a coalition list. *)
Definition psl211_inter (R C : seq nat) : seq nat := [seq x <- R | x \in C].

(** psl211_pattern_count tbl C A — rows of tbl meeting C in exactly A. *)
Definition psl211_pattern_count (tbl : seq (seq nat)) (C A : seq nat) : nat :=
  count (fun R => psl211_inter R C == A) tbl.

(* Every ascending sublist of an ascending list. *)
Fixpoint psl211_sublists (C : seq nat) : seq (seq nat) :=
  match C with
  | [::] => [:: [::]]
  | a :: C' => let S := psl211_sublists C' in S ++ [seq a :: L | L <- S]
  end.

(** psl211_count_ok_k k — for every coalition of exactly k positions and
    every pattern on it, psl211_mirror_tbl and psl211_hexad_tbl show the
    pattern equally often. *)
Definition psl211_count_ok_k (k : nat) : bool :=
  all (fun C => all (fun A =>
         psl211_pattern_count psl211_mirror_tbl C A
         == psl211_pattern_count psl211_hexad_tbl C A) (psl211_sublists C))
      (psl211_subsets k).

(** psl211_count_ok — for every coalition of at most five positions and every
    pattern, the two systems have the same number of blocks showing it. *)
Definition psl211_count_ok : bool :=
  [&& psl211_count_ok_k 1, psl211_count_ok_k 2, psl211_count_ok_k 3,
      psl211_count_ok_k 4 & psl211_count_ok_k 5].

(* 38.7 s measured (PROBE-REPORT.md). *)
Lemma psl211_count_okT : psl211_count_ok.
Proof. by vm_compute. Qed.

(** psl211_leak6 — the mirror representative row [2;3;5;7;8;9], taken as a
    six-coalition seeing all hearts, is shown by one mirror block and by no
    hexad block. The same witness the distributional leak of
    psl211_secrecy.v (psl211_leak_coalition) uses. *)
Lemma psl211_leak6 :
  psl211_pattern_count psl211_mirror_tbl [:: 2; 3; 5; 7; 8; 9] [:: 2; 3; 5; 7; 8; 9] = 1 /\
  psl211_pattern_count psl211_hexad_tbl [:: 2; 3; 5; 7; 8; 9] [:: 2; 3; 5; 7; 8; 9] = 0.
Proof. by vm_compute. Qed.
