$ rocq compile <flags of _CoqProject> r3_bare_conclude.v
exit status 1, 4 s

File "./notes/probes/2026-09-21-reading-index/landing1/r3_bare_conclude.v", line 15, characters 0-77:
Warning: Notations "_ <| _" defined at level 70 with arguments constr
at next level, constr at next level and "_ <| _ |> _" defined at level 49
with arguments constr at next level, constr at next level
have incompatible prefixes. One of them will likely not work.
[notation-incompatible-prefix,parsing,default]
File "./notes/probes/2026-09-21-reading-index/landing1/r3_bare_conclude.v", line 38, characters 4-29:
Error: Syntax error: '.' expected after [gallina] (in [vernac_aux]).
