$ rocq compile <flags of _CoqProject> r4_named_payload.v
exit status 1, 5 s

File "./notes/probes/2026-09-21-reading-index/landing1/r4_named_payload.v", line 18, characters 0-69:
Warning: Notations "_ <| _" defined at level 70 with arguments constr
at next level, constr at next level and "_ <| _ |> _" defined at level 49
with arguments constr at next level, constr at next level
have incompatible prefixes. One of them will likely not work.
[notation-incompatible-prefix,parsing,default]
File "./notes/probes/2026-09-21-reading-index/landing1/r4_named_payload.v", line 41, characters 7-9:
Error: Syntax error: 'assuming' expected after [term level 0] (in [term]).
