$ rocq compile <flags of _CoqProject, after> k_obstruction_inline.v
exit status 0, 24.5 s

rocq1: waiting for the Rocq lock
File "./k_obstruction_inline.v", line 27, characters 0-69:
Warning: Notations "_ <| _" defined at level 70 with arguments constr
at next level, constr at next level and "_ <| _ |> _" defined at level 49
with arguments constr at next level, constr at next level
have incompatible prefixes. One of them will likely not work.
[notation-incompatible-prefix,parsing,default]
