$ rocq compile <flags of _CoqProject, after> mutation_named_payload.v
exit status 1, 4.3 s

File "./mutation_named_payload.v", line 11, characters 0-69:
Warning: Notations "_ <| _" defined at level 70 with arguments constr
at next level, constr at next level and "_ <| _ |> _" defined at level 49
with arguments constr at next level, constr at next level
have incompatible prefixes. One of them will likely not work.
[notation-incompatible-prefix,parsing,default]
File "./mutation_named_payload.v", line 34, characters 7-9:
Error: Syntax error: 'assuming' expected after [term level 0] (in [term]).

