$ rocq compile <flags of _CoqProject, after> mutation_bare_conclude.v
exit status 1, 4.2 s

File "./mutation_bare_conclude.v", line 10, characters 0-77:
Warning: Notations "_ <| _" defined at level 70 with arguments constr
at next level, constr at next level and "_ <| _ |> _" defined at level 49
with arguments constr at next level, constr at next level
have incompatible prefixes. One of them will likely not work.
[notation-incompatible-prefix,parsing,default]
File "./mutation_bare_conclude.v", line 33, characters 4-29:
Error: Syntax error: '.' expected after [gallina] (in [vernac_aux]).

