# Delegating wrapper; the real makefile is generated by rocq makefile.
ROCQMAKEFILE := Makefile.rocq

all: $(ROCQMAKEFILE)
	$(MAKE) -f $(ROCQMAKEFILE) all

$(ROCQMAKEFILE): _CoqProject
	rocq makefile -f _CoqProject -o $(ROCQMAKEFILE)

%.vo: $(ROCQMAKEFILE) %.v
	$(MAKE) -f $(ROCQMAKEFILE) $@

install: $(ROCQMAKEFILE)
	$(MAKE) -f $(ROCQMAKEFILE) install

clean: $(ROCQMAKEFILE)
	$(MAKE) -f $(ROCQMAKEFILE) clean
	rm -f $(ROCQMAKEFILE) $(ROCQMAKEFILE).conf

.PHONY: all install clean
