# Delegating wrapper; the real makefile is generated by rocq makefile.
ROCQMAKEFILE := Makefile.rocq
DOCKER_IMAGE ?= rocq-pgg-smc-flat
DOCKER_JOBS ?= 1
FLAT_SOURCE_REF ?= HEAD
FLAT_ARCHIVE ?= dist/pgg-smc-flat.tar.gz

all: $(ROCQMAKEFILE)
	$(MAKE) -f $(ROCQMAKEFILE) all

$(ROCQMAKEFILE): _CoqProject
	rocq makefile -f _CoqProject -o $(ROCQMAKEFILE)

%.vo: $(ROCQMAKEFILE) %.v
	$(MAKE) -f $(ROCQMAKEFILE) $@

install: $(ROCQMAKEFILE)
	$(MAKE) -f $(ROCQMAKEFILE) install

clean: $(ROCQMAKEFILE)
	$(MAKE) -f $(ROCQMAKEFILE) clean
	rm -f $(ROCQMAKEFILE) $(ROCQMAKEFILE).conf

docker-build:
	./scripts/flatten_artifact.sh "$(FLAT_SOURCE_REF)" "$(FLAT_ARCHIVE)"
	docker build --build-arg ROCQ_JOBS="$(DOCKER_JOBS)" \
		--file Dockerfile --tag "$(DOCKER_IMAGE)" .

docker-check: docker-build
	docker run --rm "$(DOCKER_IMAGE)"

.PHONY: all install clean docker-build docker-check
