(* Generated by gen_fidelity.py.  Do not edit by hand. *)
From mathcomp Require Import ssreflect ssrbool eqtype ssrnat seq.
From mathcomp Require Import fintype finfun finset.
From mathcomp Require Import matrix zmodp reals.
From infotheo Require Import fdist proba entropy.
From pgg_reconstruct Require Import pgg_sharing_framework.
From pgg_smc Require Import pgg_analysis_status.
From pgg_smc Require Import pgg_instance pgg_functionality.
From pgg_smc Require Import pgg_sample_adapter.
From pgg_smc Require Import pgg_randomized_sharing pgg_canonical_sharing.
From pgg_smc Require Import s5_profile s5_exec s5_models.
From pgg_smc Require Import pgg_analysis_manifest.
From pgg_smc Require Import pgg_tableau.
From pgg_smc Require Import pgg_tableau_syntax.
From pgg_smc Require Import s5_rows.

Set Implicit Arguments.
Unset Strict Implicit.
Import Prenex Implicits.
Import GRing.Theory Num.Theory.

Local Open Scope fdist_scope.
Local Open Scope proba_scope.
Local Open Scope entropy_scope.
Local Open Scope ring_scope.

(* The eighteen declarations of instances/s5/s5_rows.v, each ascribed at the
   statement it has in production.                                           *)

Check (s5_dealt : Tableau Observed).

Check (s5_dealt_row_observedE :
  ob_obs (tableau_at s5_dealt) = apr_observed s5_row_det).

Check (s5_supplied : Tableau Observed).

Check (s5_supplied_paramsE :
  projT1 (projT2 (tableau_at s5_supplied)) = s5_supplied_params).

Check (s5_rand_static_obsE :
  forall (R : realType) (idx : unit)
    (C : {set 'I_(pi_T' (mp_PI (instance_profile s5_algebra))).+1}),
  (fun u => @static_coalition_obs s5_algebra s5_supplied_params C
              ((amf_sample s5_rand_family R idx).(sa_arg) u)
              ((amf_sample s5_rand_family R idx).(sa_cut) u))
  = rsh_view (@unif_randomized_sharing R 3 4) C).

Check (s5_rand_static_obs_indep :
  forall (R : realType) (idx : unit)
    (C : {set 'I_(pi_T' (mp_PI (instance_profile s5_algebra))).+1}),
  (#|C| < profile_k (instance_profile s5_algebra))%N ->
  sa_sampleP (amf_sample s5_rand_family R idx)
  |= (fun u => @static_coalition_obs s5_algebra s5_supplied_params C
                 ((amf_sample s5_rand_family R idx).(sa_arg) u)
                 ((amf_sample s5_rand_family R idx).(sa_cut) u))
     _|_ (rsh_secret (@unif_randomized_sharing R 3 4))).

Check (s5_rand_exact_witness :
  forall (R : realType) (idx : unit),
  ExactWitness (amf_sample s5_rand_family R idx)).

Check (s5_row_rand_tableau : PublishedRow).

Check (s5_row_rand_rowE :
  published_row s5_row_rand_tableau = s5_row_rand).

Check (s5_row_rand_armE :
  forall (R : realType)
    (idx : amf_index (ab_f (published_at s5_row_rand_tableau)) R),
  security_arm_of s5_row_rand_tableau R idx = ExactIndependenceArm).

Check (s5_rand_view_secrecy :
  forall (R : realType) (C : {set 'I_5}) (HC : (#|C| < 5)%N),
  [/\ s5_rand_sampleP R
      |= (@sa_coalition_view R s5_profile s5_rand_exec_plug
            (s5_rand_sample R) 0 C)
         _|_ (rsh_secret (@unif_randomized_sharing R 3 4)),
      `I( rsh_secret (@unif_randomized_sharing R 3 4) ;
          @sa_coalition_view R s5_profile s5_rand_exec_plug
            (s5_rand_sample R) 0 C ) = 0,
      `H( rsh_secret (@unif_randomized_sharing R 3 4) |
          @sa_coalition_view R s5_profile s5_rand_exec_plug
            (s5_rand_sample R) 0 C )
      = `H `p_ (rsh_secret (@unif_randomized_sharing R 3 4))
    & forall (W : finType) (h : {ffun 'I_5 -> 'I_5} -> W),
        s5_rand_sampleP R
        |= (h `o (@sa_coalition_view R s5_profile s5_rand_exec_plug
                    (s5_rand_sample R) 0 C))
           _|_ (rsh_secret (@unif_randomized_sharing R 3 4))]).

Check (s5_F : Functionality (oe_inputT s5_observed) (oe_outT s5_observed)).

Check (s5_FE : s5_F = MkFunctionality id 4).

Check (s5_F_thresholdE : fn_threshold s5_F = 4).

Check (s5_realises_expected : realises_expected s5_observed s5_F).

Check (s5_rand_F :
  Functionality (oe_inputT s5_rand_observed) (oe_outT s5_rand_observed)).

Check (s5_rand_FE :
  s5_rand_F = MkFunctionality (fun u => s5_codec (s5_tape_secret u)) 4).

Check (s5_rand_realises_expected :
  realises_expected s5_rand_observed s5_rand_F).

(* The assumptions of the published row and of every lemma and theorem.      *)

Print Assumptions s5_row_rand_tableau.
Print Assumptions s5_dealt_row_observedE.
Print Assumptions s5_supplied_paramsE.
Print Assumptions s5_rand_static_obsE.
Print Assumptions s5_rand_static_obs_indep.
Print Assumptions s5_rand_exact_witness.
Print Assumptions s5_row_rand_rowE.
Print Assumptions s5_row_rand_armE.
Print Assumptions s5_rand_view_secrecy.
Print Assumptions s5_FE.
Print Assumptions s5_F_thresholdE.
Print Assumptions s5_realises_expected.
Print Assumptions s5_rand_FE.
Print Assumptions s5_rand_realises_expected.
