(* Generated by gen_fidelity.py.  Do not edit by hand. *)
Require Import Lia.
From mathcomp Require Import zify.
From mathcomp Require Import ssreflect ssrbool ssrfun eqtype ssrnat seq.
From mathcomp Require Import fintype tuple finfun finset fingroup perm.
From mathcomp Require Import bigop order ssrnum ssralg reals boolp lra.
From infotheo Require Import realType_ext fdist proba variation_dist entropy.
From pgg_smc Require Import pgg_interface pgg_session_types.
From pgg_smc Require Import pgg_monodromy_profile pgg_execution_plug.
From pgg_smc Require Import pgg_observed_execution pgg_analysis_status.
From pgg_smc Require Import pgg_instance pgg_functionality.
From pgg_smc Require Import pgg_sample_adapter pgg_trace_secrecy.
From pgg_smc Require Import pgg_collusion_bound var_dist_supp.
From pgg_smc Require Import var_dist_joint_law.
From pgg_reconstruct Require Import algebraic_rigidity.
From pgg_smc Require Import five_card_group five_card_program.
From pgg_smc Require Import five_card_kim five_card_family.
From pgg_smc Require Import den_boer_encoding den_boer_run.
From pgg_smc Require Import five_card_leakage five_card_exec five_card_models.
From pgg_smc Require Import kim_input_privacy.
From pgg_smc Require Import five_card_mixing.
From pgg_smc Require Import s5_exec s5_models.
From pgg_smc Require Import pgg_analysis_manifest.
From pgg_smc Require Import pgg_tableau pgg_tableau_syntax.
From pgg_smc Require Import five_card_rows five_card_proximity.

Set Implicit Arguments.
Unset Strict Implicit.
Import Prenex Implicits.
Import GRing.Theory Num.Theory.

Local Open Scope fdist_scope.
Local Open Scope proba_scope.
Local Open Scope entropy_scope.
Local Open Scope ring_scope.

(* five_card_rows.v *)
Check @five_card_committed.
Check @five_card_committed_paramsE.
Check @five_card_colour_fill.
Check @five_card_viewS_nth.
Check @five_card_static_obsE.
Check @five_card_viewS_indep.
Check @five_card_exact_viewE.
Check @five_card_static_obs_indep.
Check @five_card_exact_witness.
Check @five_card_row_uniform_tableau.
Check @five_card_row_uniform_rowE.
Check @five_card_row_uniform_armE.
Check @five_card_exact_view_secrecy.
Check @five_card_row_repeated_tableau.
Check @five_card_row_biased_tableau.
Check @five_card_row_repeated_prefixE.
Check @five_card_row_biased_prefixE.
Check @five_card_row_repeated_modelE.
Check @five_card_row_biased_modelE.
Check @five_card_row_biased_levelE.
Check @kim_biased_epsE.
Check @kim_biased_exact_le_eps.
Check @kim_centi_cert.
Check @kim_biased_cert.
Check @five_card_row_repeated_indistinguishability_tableau.
Check @five_card_row_biased_indistinguishability_tableau.
Check @five_card_row_repeated_indistinguishability_rowE.
Check @five_card_row_biased_indistinguishability_rowE.
Check @five_card_row_repeated_indistinguishability_armE.
Check @five_card_row_biased_indistinguishability_armE.
Check @five_card_row_repeated_indistinguishability_publishedE.
Check @five_card_row_biased_indistinguishability_publishedE.
Check @five_card_pow2_39_split.
Check @kim_centi_cert_epsE.
Check @kim_centi_cert_eps_lt.
Check @kim_biased_cert_epsE.
Check @kim_biased_cert_eps_lt2.
Check @five_card_reprice39.
Check @five_card_row_repeated39.
Check @five_card_row_repeated39_atE.
Check @five_card_row_repeated39_armE.
Check @kim_biased_cert_exact.
Check @five_card_inv50_split.
Check @five_card_reprice_inv25.
Check @five_card_row_biased_inv25.
Check @five_card_row_biased_forms_publishedE.
Check @five_card_row_biased_inv25_armE.
Check @five_card_reprice_inv25_lt2.
Check @five_card_row_repeated_endpoint_lt.
Check @kim_centi_small.
Check @five_card_row_biased_leak_bound.
Check @five_card_target.
Check @five_card_F.
Check @five_card_FE.
Check @five_card_F_ite.
Check @five_card_realises_expected.

(* five_card_proximity.v *)
Check @five_card_uniform_pairE.
Check @five_card_reading_secretE.
Check @five_card_arg_cut_prodE.
Check @kim_biased_proximity_close.
Check @kim_biased_proximity_cert.
Check @kim_biased_proximity_cert_idealE.
Check @kim_biased_proximity_cert_epsE.
Check @kim_biased_proximity_eps_halfE.
Check @kim_biased_proximity_cert_eps_lt2.
Check @five_card_row_biased_branch_indistinguishability.
Check @five_card_row_biased_branch_indistinguishability_atE.
Check @five_card_row_biased_branch_indistinguishability_rowE.
Check @five_card_row_biased_proximity.
Check @five_card_row_biased_proximity_rowE.
Check @five_card_row_biased_proximity_publishedE.
Check @five_card_row_biased_branch_indistinguishability_armE.
Check @five_card_row_biased_proximity_armE.
Check @five_card_row_biased_arm_neq.
Check @five_card_biased_view_proximity.
Check @five_card_biased_view_own_marginals.
Check @five_card_reprice_inv100.
Check @kim_biased_conclude_below_false.
Check @five_card_singleton_below_threshold.
Check @five_card_biased_proximity_at_singleton.
Check @five_card_biased_proximity_prop_holds.
Check @five_card_biased_indistinguishability_implies_proximity.

(* five_card_rows.v *)
Print Assumptions five_card_committed_paramsE.
Print Assumptions five_card_viewS_nth.
Print Assumptions five_card_static_obsE.
Print Assumptions five_card_viewS_indep.
Print Assumptions five_card_exact_viewE.
Print Assumptions five_card_static_obs_indep.
Print Assumptions five_card_row_uniform_tableau.
Print Assumptions five_card_row_uniform_rowE.
Print Assumptions five_card_row_uniform_armE.
Print Assumptions five_card_exact_view_secrecy.
Print Assumptions five_card_row_repeated_prefixE.
Print Assumptions five_card_row_biased_prefixE.
Print Assumptions five_card_row_repeated_modelE.
Print Assumptions five_card_row_biased_modelE.
Print Assumptions five_card_row_biased_levelE.
Print Assumptions kim_biased_epsE.
Print Assumptions kim_biased_exact_le_eps.
Print Assumptions five_card_row_repeated_indistinguishability_tableau.
Print Assumptions five_card_row_biased_indistinguishability_tableau.
Print Assumptions five_card_row_repeated_indistinguishability_rowE.
Print Assumptions five_card_row_biased_indistinguishability_rowE.
Print Assumptions five_card_row_repeated_indistinguishability_armE.
Print Assumptions five_card_row_biased_indistinguishability_armE.
Print Assumptions five_card_row_repeated_indistinguishability_publishedE.
Print Assumptions five_card_row_biased_indistinguishability_publishedE.
Print Assumptions five_card_pow2_39_split.
Print Assumptions kim_centi_cert_epsE.
Print Assumptions kim_centi_cert_eps_lt.
Print Assumptions kim_biased_cert_epsE.
Print Assumptions kim_biased_cert_eps_lt2.
Print Assumptions five_card_row_repeated39.
Print Assumptions five_card_row_repeated39_atE.
Print Assumptions five_card_row_repeated39_armE.
Print Assumptions five_card_inv50_split.
Print Assumptions five_card_row_biased_inv25.
Print Assumptions five_card_row_biased_forms_publishedE.
Print Assumptions five_card_row_biased_inv25_armE.
Print Assumptions five_card_reprice_inv25_lt2.
Print Assumptions five_card_row_repeated_endpoint_lt.
Print Assumptions kim_centi_small.
Print Assumptions five_card_row_biased_leak_bound.
Print Assumptions five_card_FE.
Print Assumptions five_card_F_ite.
Print Assumptions five_card_realises_expected.

(* five_card_proximity.v *)
Print Assumptions five_card_uniform_pairE.
Print Assumptions five_card_reading_secretE.
Print Assumptions five_card_arg_cut_prodE.
Print Assumptions kim_biased_proximity_close.
Print Assumptions kim_biased_proximity_cert_idealE.
Print Assumptions kim_biased_proximity_cert_epsE.
Print Assumptions kim_biased_proximity_eps_halfE.
Print Assumptions kim_biased_proximity_cert_eps_lt2.
Print Assumptions five_card_row_biased_branch_indistinguishability.
Print Assumptions five_card_row_biased_branch_indistinguishability_atE.
Print Assumptions five_card_row_biased_branch_indistinguishability_rowE.
Print Assumptions five_card_row_biased_proximity.
Print Assumptions five_card_row_biased_proximity_rowE.
Print Assumptions five_card_row_biased_proximity_publishedE.
Print Assumptions five_card_row_biased_branch_indistinguishability_armE.
Print Assumptions five_card_row_biased_proximity_armE.
Print Assumptions five_card_row_biased_arm_neq.
Print Assumptions five_card_biased_view_proximity.
Print Assumptions five_card_biased_view_own_marginals.
Print Assumptions kim_biased_conclude_below_false.
Print Assumptions five_card_singleton_below_threshold.
Print Assumptions five_card_biased_proximity_at_singleton.
Print Assumptions five_card_biased_proximity_prop_holds.
Print Assumptions five_card_biased_indistinguishability_implies_proximity.

Print five_card_reprice39.
Print five_card_reprice_inv25.
Print five_card_reprice_inv100.
Print kim_biased_proximity_cert.
