#!/usr/bin/env python3
"""Generate fidelity.v (against the staged text) and baseline.v (against
production) from one shared body.

Both files name every declaration of instances/kim2025/five_card_rows.v and
instances/kim2025/five_card_proximity.v that is not a recorded Fail, print its type
under one fixed scope block, and print the assumptions of every published
row, lemma, fact and theorem.  Only the Require line differs, so `diff` of
the two outputs is the check: a declaration whose statement or whose axiom
set changed when it moved would print differently.

The two files are written under production five_card_rows.v's scope block: fdist,
proba, entropy, ring.  Production five_card_proximity.v's is ring, fdist, proba,
so the declarations that move out of it are printed here under a different
innermost scope than they were written in.  That is deliberate: it is the
check that the re-scoping changes no statement.  A numeral or a notation that
resolved differently would make the two Check lines differ.

The name lists are read out of the two production files, so this generator
cannot drift from them.

Usage: python3 gen_fidelity.py
"""

import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, "..", "..", ".."))
PROD_ROWS = os.path.join(ROOT, "instances", "kim2025", "five_card_rows.v")
PROD_PROX = os.path.join(ROOT, "instances", "kim2025", "five_card_proximity.v")

import verify  # noqa: E402  (its strip_comments and items are the audited ones)

PRELUDE = r"""(* Generated by gen_fidelity.py.  Do not edit by hand. *)
Require Import Lia.
From mathcomp Require Import zify.
From mathcomp Require Import ssreflect ssrbool ssrfun eqtype ssrnat seq.
From mathcomp Require Import fintype tuple finfun finset fingroup perm.
From mathcomp Require Import bigop order ssrnum ssralg reals boolp lra.
From infotheo Require Import realType_ext fdist proba variation_dist entropy.
From pgg_smc Require Import pgg_interface pgg_session_types.
From pgg_smc Require Import pgg_monodromy_profile pgg_execution_plug.
From pgg_smc Require Import pgg_observed_execution pgg_analysis_status.
From pgg_smc Require Import pgg_instance pgg_functionality.
From pgg_smc Require Import pgg_sample_adapter pgg_trace_secrecy.
From pgg_smc Require Import pgg_collusion_bound var_dist_supp.
From pgg_smc Require Import var_dist_joint_law.
From pgg_reconstruct Require Import algebraic_rigidity.
From pgg_smc Require Import five_card_group five_card_program.
From pgg_smc Require Import five_card_kim five_card_family.
From pgg_smc Require Import den_boer_encoding den_boer_run.
From pgg_smc Require Import five_card_leakage five_card_exec five_card_models.
From pgg_smc Require Import kim_input_privacy.
From pgg_smc Require Import five_card_mixing.
From pgg_smc Require Import s5_exec s5_models.
From pgg_smc Require Import pgg_analysis_manifest.
From pgg_smc Require Import pgg_tableau pgg_tableau_syntax.
"""

SETTINGS = r"""
Set Implicit Arguments.
Unset Strict Implicit.
Import Prenex Implicits.
Import GRing.Theory Num.Theory.

Local Open Scope fdist_scope.
Local Open Scope proba_scope.
Local Open Scope entropy_scope.
Local Open Scope ring_scope.
"""

# The ten declarations only the staged tree has.  Each Definition is
# checked at its type, which a wrong body would still satisfy; what pins
# the bodies is the six equations, each of which holds by conversion
# against a production term.  The assumptions of all ten are printed,
# because a type ascription alone would pass on a wrong body.
NEW = r"""
Check @five_card_algebraic_start.
Check @five_card_committed_executable.
Check @five_card_uniform_sampled.
Check @five_card_committed_executable_paramsE.
Check @five_card_committed_executableE.
Check @five_card_row_uniform_sampledE.
Check @five_card_row_repeated_indistinguishability_sampledE.
Check @five_card_row_biased_indistinguishability_sampledE.
Check @five_card_row_repeated39_sampledE.
Check @five_card_row_biased_inv25_sampledE.

Print Assumptions five_card_algebraic_start.
Print Assumptions five_card_committed_executable.
Print Assumptions five_card_uniform_sampled.
Print Assumptions five_card_committed_executable_paramsE.
Print Assumptions five_card_committed_executableE.
Print Assumptions five_card_row_uniform_sampledE.
Print Assumptions five_card_row_repeated_indistinguishability_sampledE.
Print Assumptions five_card_row_biased_indistinguishability_sampledE.
Print Assumptions five_card_row_repeated39_sampledE.
Print Assumptions five_card_row_biased_inv25_sampledE.
"""

# Published rows: the Definitions whose assumptions are printed beside the
# lemmas.  Every other Definition is a payload or a prefix reached through one
# of these, and a Print Assumptions on a type naming pgl27_observed is slow.
ROWS_PRINTED = [
    "five_card_row_uniform_tableau",
    "five_card_row_repeated_indistinguishability_tableau",
    "five_card_row_biased_indistinguishability_tableau",
    "five_card_row_repeated39",
    "five_card_row_biased_inv25",
    "five_card_row_biased_branch_indistinguishability",
    "five_card_row_biased_proximity",
    "five_card_F_ite",
    "five_card_biased_proximity_at_singleton",
]


def inventory():
    checks, prints = [], []
    for path in (PROD_ROWS, PROD_PROX):
        src = verify.strip_comments(open(path).read())
        head = "(* %s *)" % os.path.basename(path)
        checks.append("")
        checks.append(head)
        prints.append("")
        prints.append(head)
        for kind, name, _ in verify.items(src):
            if kind.startswith("Fail"):
                continue
            checks.append("Check @%s." % name)
            if kind != "Definition" or name in ROWS_PRINTED:
                prints.append("Print Assumptions %s." % name)
    return "\n".join(checks) + "\n", "\n".join(prints) + "\n"


CHECKS, PRINTS = inventory()


# PGL(2,7) audit ruling 10: a Definition's body is pinned by an equation,
# never by Check.  Reprice is `forall R : realType, option R`, so Check @f
# prints nothing of the number; kim_biased_proximity_cert's type hides its
# ipc_eps field the same way.  These four are the only Definitions of the two
# sources whose body holds a numeric literal, and Print puts that body on
# both sides of the diff.  five_card_reprice_inv100 and
# kim_biased_proximity_cert are also the only two of them that are re-scoped.
BODIES = r"""
Print five_card_reprice39.
Print five_card_reprice_inv25.
Print five_card_reprice_inv100.
Print kim_biased_proximity_cert.
"""


def write(name, require, extra):
    body = PRELUDE + require + SETTINGS + CHECKS + PRINTS + BODIES + extra
    with open(os.path.join(HERE, name), "w") as f:
        f.write(body)
    n = len(re.findall(r"^Check @", body, re.M))
    m = len(re.findall(r"^Print Assumptions", body, re.M))
    print("wrote %-12s %d Check, %d Print Assumptions" % (name, n, m))


write("fidelity.v",
      "From pgg_smc Require Import five_card_proximity.\n"
      "From pgg_smc Require Import five_card_tableau_algebraic.\n"
      "From pgg_smc Require Import five_card_tableau_executable.\n"
      "From pgg_smc Require Import five_card_tableau_observed.\n"
      "From pgg_smc Require Import five_card_tableau_sampled.\n"
      "From pgg_smc Require Import five_card_tableau_analysis_bridged.\n"
      "From pgg_smc Require Import five_card_tableau_checks.\n",
      NEW)

write("baseline.v",
      "From pgg_smc Require Import five_card_rows five_card_proximity.\n",
      "")
