(* infotheo: information theory and error-correcting codes in Rocq            *)
(* Copyright (C) 2025 infotheo authors, license: LGPL-2.1-or-later            *)
(******************************************************************************)
(* pgl27_mixing: the binary-N random-walk ground layer of the PGL(2,7)        *)
(*               shuffle and the in-kernel order of the generated group       *)
(*                                                                            *)
(* The realistic word shuffle draws letters from the five symmetrized         *)
(* generators (translation, scaling, inversion and the two inverses). Its     *)
(* state space is the group generated by the three PGL(2,7) generators. A     *)
(* nat-level breadth-first search enumerates the group as permutation tables  *)
(* of 'I_8; a checker re-verifies the 336-entry closure. A companion binary-N *)
(* walk of length L = 200 tabulates the distribution reached from the         *)
(* identity, and a scalar checker certifies its total-variation bound.        *)
(*                                                                            *)
(* Definitions:                                                               *)
(*   pgl27_sym_sigmas == the inverse-closed five-letter generator tuple       *)
(*   mtbl j           == the permutation table of the j-th letter             *)
(*   elem_table       == the BFS closure, keys paired with carrying words     *)
(*   walkN L          == the length-L walk distribution over the 336 states   *)
(*                                                                            *)
(* Key results:                                                               *)
(*   elem_table_okT   == the closure has 336 uniq keys, closed under letters  *)
(*   mixing_bound_okT == the length-200 walk meets the 2^-40 mixing bound     *)
(*   pgl27_gen5_eq    == the five letters generate the PGL(2,7) group         *)
(*   pgl27_card       == the PGL(2,7) shuffle group has exactly 336 elements  *)
(*   pgl27_word_mixing     == the 200-letter word law is within 2^-40 of the  *)
(*                            uniform shuffle in variation distance           *)
(*   pgl27_endpoint_mixing == the same for each single-card marginal          *)
(*   pgl27_joint_mixing    == the same for the joint secret-and-shuffle law   *)
(*                                                                            *)
(******************************************************************************)

From HB Require Import structures.
From Stdlib Require Import BinNat Nnat.
From mathcomp Require Import ssreflect ssrbool ssrfun eqtype ssrnat seq.
From mathcomp Require Import fintype tuple finfun finset fingroup perm.
From mathcomp Require Import morphism action bigop div prime.
From mathcomp Require Import ssralg ssrnum order.
From mathcomp Require Import primitive_action.
From mathcomp Require Import boolp reals.
From infotheo Require Import realType_ext fdist proba variation_dist.
From pgg_smc Require Import pgg_interface.
From pgg_smc Require Import pgl27_group pgl27_profile.
From pgg_smc Require Import pgg_collusion_bound pgg_weighted_words.

Set Implicit Arguments.
Unset Strict Implicit.
Import Prenex Implicits.

(* -------------------------------------------------------------------------- *)
(* The five symmetrized generators and their permutation tables of 'I_8.      *)
(* -------------------------------------------------------------------------- *)

(** pgl27_sym_sigmas — the inverse-closed symmetrized generator tuple of the
    realistic word shuffle: translation, scaling, inversion and the two
    inverses of translation and scaling. The letter alphabet of the L-word
    shuffle. *)
Definition pgl27_sym_sigmas : 5.-tuple {perm 'I_8} :=
  [tuple tnth pgl27_gens (@Ordinal 3 0 isT);
         ((tnth pgl27_gens (@Ordinal 3 0 isT))^-1)%g;
         tnth pgl27_gens (@Ordinal 3 1 isT);
         ((tnth pgl27_gens (@Ordinal 3 1 isT))^-1)%g;
         tnth pgl27_gens (@Ordinal 3 2 isT)].

(* The permutation table of the j-th letter, read off by position. *)
Local Definition mtbl (j : nat) : seq nat :=
  nth [::] [:: [:: 1; 2; 3; 4; 5; 6; 0; 7]
             ; [:: 6; 0; 1; 2; 3; 4; 5; 7]
             ; [:: 0; 3; 6; 2; 5; 1; 4; 7]
             ; [:: 0; 5; 3; 1; 6; 4; 2; 7]
             ; [:: 7; 6; 3; 2; 5; 4; 1; 0]] j.

(* A permutation whose forward images are read off the table F has (g^-1) x
   at Finv, whenever Finv is a right inverse of F on the eight codes.  The two
   inverse letters of the symmetrized alphabet are given by tables this way,
   so no permutation is ever inverted inside a kernel computation. *)
Local Lemma perm_inv_val (g : {perm 'I_8}) (F Finv : seq nat) (x : 'I_8) :
  (forall y : 'I_8, val (g y) = nth 0 F (val y)) ->
  (forall k, k < 8 -> nth 0 F (nth 0 Finv k) = k) ->
  (forall k, k < 8 -> nth 0 Finv k < 8) ->
  val ((g^-1)%g x) = nth 0 Finv (val x).
Proof.
move=> Hfwd Hcomp Hrange.
have Hc8 : nth 0 Finv (val x) < 8 by apply: Hrange; exact: ltn_ord.
pose z : 'I_8 := Ordinal Hc8.
have Hgz : g z = x.
  by apply/val_inj; rewrite Hfwd /= Hcomp //; exact: ltn_ord.
have Hzx : (g^-1)%g x = z by rewrite -Hgz permK.
by rewrite Hzx.
Qed.

(* The three forward generators agree with their nat-level tables. *)
Local Lemma gfwd0 (x : 'I_8) :
  val (tnth pgl27_gens (@Ordinal 3 0 isT) x) = nth 0 (mtbl 0) (val x).
Proof. by case: x => -[|[|[|[|[|[|[|[|//]]]]]]]] Hx; rewrite permE. Qed.
Local Lemma gfwd1 (x : 'I_8) :
  val (tnth pgl27_gens (@Ordinal 3 1 isT) x) = nth 0 (mtbl 2) (val x).
Proof. by case: x => -[|[|[|[|[|[|[|[|//]]]]]]]] Hx; rewrite permE. Qed.
Local Lemma gfwd2 (x : 'I_8) :
  val (tnth pgl27_gens (@Ordinal 3 2 isT) x) = nth 0 (mtbl 4) (val x).
Proof. by case: x => -[|[|[|[|[|[|[|[|//]]]]]]]] Hx; rewrite permE. Qed.

(* Each of the five letters sends a code to the entry of its own table at that
   code.  The alphabet is therefore described entirely by mtbl, which is the
   form the BFS closure and the walk recursion compute in. *)
Local Lemma mtbl_val (j : 'I_5) (x : 'I_8) :
  val (tnth pgl27_sym_sigmas j x) = nth 0 (mtbl j) (val x).
Proof.
case: j => -[|[|[|[|[|//]]]]] Hj; rewrite (tnth_nth 1%g) /=.
- exact: gfwd0.
- apply: (perm_inv_val (F := mtbl 0)); first exact: gfwd0.
  + by case=> [|[|[|[|[|[|[|[|k7]]]]]]]].
  + by case=> [|[|[|[|[|[|[|[|k7]]]]]]]].
- exact: gfwd1.
- apply: (perm_inv_val (F := mtbl 2)); first exact: gfwd1.
  + by case=> [|[|[|[|[|[|[|[|k7]]]]]]]].
  + by case=> [|[|[|[|[|[|[|[|k7]]]]]]]].
- exact: gfwd2.
Qed.

(* -------------------------------------------------------------------------- *)
(* Nat-level breadth-first enumeration of the group as permutation tables.    *)
(* -------------------------------------------------------------------------- *)

(* Composition of two tables: the table of the second read at the first. *)
Local Definition mcomp (t1 t2 : seq nat) : seq nat :=
  map (fun x => nth 0 t2 x) t1.
Local Definition idt : seq nat := [:: 0; 1; 2; 3; 4; 5; 6; 7].

(* Fueled search keeping, for each reached table, a carrying letter word. *)
Local Fixpoint elem_bfs (fuel : nat) (seen : seq (seq nat * seq nat)) :
    seq (seq nat * seq nat) :=
  match fuel with
  | 0 => seen
  | S f =>
    let nxt := flatten
      [seq [seq (mcomp tw.1 (mtbl j), rcons tw.2 j) | j <- [:: 0; 1; 2; 3; 4]]
      | tw <- seen] in
    let add := foldl (fun acc tw =>
      if has (fun sw : seq nat * seq nat => sw.1 == tw.1) (seen ++ acc)
      then acc else rcons acc tw) [::] nxt in
    if size add == 0 then seen else elem_bfs f (seen ++ add)
  end.

(* Reached tables paired with a carrying word, from the identity table. *)
Local Definition elem_table : seq (seq nat * seq nat) :=
  elem_bfs 12 [:: (idt, [::])].

(* The position of a table among the reached keys. *)
Local Definition tbl_index (t : seq nat) : nat :=
  find (fun sw : seq nat * seq nat => sw.1 == t) elem_table.

(* The letter carrying a state back along the reverse walk. *)
Local Definition inv_letter (j : nat) : nat := nth 0 [:: 1; 0; 3; 2; 4] j.

(* For each key, the indices of its five reverse-walk predecessors. *)
Local Definition pred_table : seq (seq nat) :=
  [seq [seq tbl_index (mcomp sw.1 (mtbl (inv_letter j)))
       | j <- [:: 0; 1; 2; 3; 4]]
  | sw <- elem_table].

(* The closure has 336 uniq keys, opens at the identity, every word folds to
   its key, every one-letter successor stays in the list, and every word
   carries only letters below five. *)
Local Definition elem_table_ok : bool :=
  [&& size elem_table == 336,
      uniq (unzip1 elem_table),
      nth ([::], [::]) elem_table 0 == (idt, [::]),
      all (fun sw : seq nat * seq nat =>
             foldl (fun t j => mcomp t (mtbl j)) idt sw.2 == sw.1)
          elem_table,
      all (fun sw : seq nat * seq nat =>
             all (fun j => nth [::] (unzip1 elem_table)
                     (tbl_index (mcomp sw.1 (mtbl j))) == mcomp sw.1 (mtbl j))
                 [:: 0; 1; 2; 3; 4])
          elem_table
    & all (fun sw : seq nat * seq nat =>
             all (fun j => j < 5) sw.2) elem_table].
(* Every conjunct of elem_table_ok holds.  This single kernel computation is
   what the group order and the walk's 336-state indexing both rest on: it
   fixes the number of states, their uniqueness, the state of the identity,
   and closure of the state set under the five letters. *)
Local Lemma elem_table_okT : elem_table_ok.
Proof. by vm_compute. Qed.

(* -------------------------------------------------------------------------- *)
(* The binary-N random walk of length L over the 336 states.                  *)
(* -------------------------------------------------------------------------- *)

(* walkN L s counts the length-L letter words carrying the identity to s. *)
Local Fixpoint walkN (L : nat) : seq N :=
  match L with
  | 0 => 1%num :: nseq 335 0%num
  | L'.+1 =>
    let v := walkN L' in
    [seq foldl (fun acc i => (acc + nth 0%num v i)%num) 0%num preds
    | preds <- pred_table]
  end.

(* Absolute difference of two binary naturals. *)
Local Definition absdiffN (a b : N) : N :=
  if (a <? b)%num then (b - a)%num else (a - b)%num.

(* The integer form of the mixing bound: 2^40 times the total absolute
   deviation of the 336 walk counts from the uniform value 5^200 / 336, taken
   over the common denominator, is at most 336 * 5^200. *)
Local Definition mixing_bound_ok : bool :=
  let D := (5 ^ 200)%num in
  ((2 ^ 40) * foldl (fun acc c => (acc + absdiffN (336 * c) D)%num) 0%num
                    (walkN 200)
   <=? 336 * D)%num.
(* The length-200 walk meets that integer bound.  It is the only quantitative
   input to the mixing theorem; everything after it is exact rewriting. *)
Local Lemma mixing_bound_okT : mixing_bound_ok.
Proof. by vm_compute. Qed.

(* -------------------------------------------------------------------------- *)
(* Small facts read off the closure checker: the six conjuncts of             *)
(* elem_table_ok, each projected out for use on its own.                      *)
(* -------------------------------------------------------------------------- *)

Local Lemma size_elem_table : size elem_table = 336.
Proof. by move: elem_table_okT => /andP[/eqP H _]. Qed.
Local Lemma uniq_elem_keys : uniq (unzip1 elem_table).
Proof. by move: elem_table_okT => /andP[_ /andP[H _]]. Qed.
Local Lemma elem_table0 : nth ([::], [::]) elem_table 0 = (idt, [::]).
Proof. by move: elem_table_okT => /andP[_ /andP[_ /andP[/eqP H _]]]. Qed.
Local Lemma elem_fold_key (sw : seq nat * seq nat) :
  sw \in elem_table -> foldl (fun t j => mcomp t (mtbl j)) idt sw.2 = sw.1.
Proof.
move=> Hsw; apply/eqP.
by move: elem_table_okT => /andP[_ /andP[_ /andP[_ /andP[/allP/(_ _ Hsw) H _]]]].
Qed.
Local Lemma elem_closed (sw : seq nat * seq nat) :
  sw \in elem_table ->
  all (fun j => nth [::] (unzip1 elem_table)
          (tbl_index (mcomp sw.1 (mtbl j))) == mcomp sw.1 (mtbl j)) [:: 0;1;2;3;4].
Proof.
move=> Hsw.
by move: elem_table_okT =>
  /andP[_ /andP[_ /andP[_ /andP[_ /andP[/allP/(_ _ Hsw) H _]]]]].
Qed.
Local Lemma elem_letters (sw : seq nat * seq nat) :
  sw \in elem_table -> all (fun j => j < 5) sw.2.
Proof.
move=> Hsw.
by move: elem_table_okT =>
  /andP[_ /andP[_ /andP[_ /andP[_ /andP[_ /allP/(_ _ Hsw) H]]]]].
Qed.

(* Tables composed by [mcomp] and folded keep length eight. *)
Local Lemma size_mcomp (t1 t2 : seq nat) : size (mcomp t1 t2) = size t1.
Proof. by rewrite /mcomp size_map. Qed.
Local Lemma size_fold (w : seq nat) :
  size (foldl (fun t j => mcomp t (mtbl j)) idt w) = 8.
Proof.
have gen : forall (w' : seq nat) (t : seq nat), size t = 8 ->
    size (foldl (fun t0 j => mcomp t0 (mtbl j)) t w') = 8.
  by elim=> [|j w' IH] t Ht //=; apply: IH; rewrite size_mcomp.
by apply: gen.
Qed.
(* Every closure key is a table of the eight codes. *)
Local Lemma elem_key_size (sw : seq nat * seq nat) :
  sw \in elem_table -> size sw.1 = 8.
Proof. by move=> Hsw; rewrite -(elem_fold_key Hsw) size_fold. Qed.

(* Every one-letter successor of a key is itself a key. *)
Local Lemma elem_closed_mem (sw : seq nat * seq nat) (j : nat) :
  sw \in elem_table -> j \in [:: 0; 1; 2; 3; 4] ->
  mcomp sw.1 (mtbl j) \in unzip1 elem_table.
Proof.
move=> Hsw Hj.
have /eqP Heq := allP (elem_closed Hsw) j Hj.
have Hsz8 : size (mcomp sw.1 (mtbl j)) = 8 by rewrite size_mcomp (elem_key_size Hsw).
rewrite -Heq; apply: mem_nth.
rewrite ltnNge; apply/negP => Hge.
move: Heq; rewrite (nth_default _ Hge) => Habs.
by move: Hsz8; rewrite -Habs.
Qed.
(* The identity table is a key, and by elem_table0 it is the key at index 0,
   so state 0 of the walk is the identity shuffle. *)
Local Lemma idt_in_keys : idt \in unzip1 elem_table.
Proof.
have -> : idt = nth [::] (unzip1 elem_table) 0.
  rewrite (nth_map ([::], [::])); last by rewrite size_elem_table.
  by rewrite elem_table0.
by apply: mem_nth; rewrite size_map size_elem_table.
Qed.

(* -------------------------------------------------------------------------- *)
(* The permutation-table map and its group structure.                         *)
(* -------------------------------------------------------------------------- *)

(* The table of a permutation of 'I_8: its list of images in code order.
   This is the transport between {perm 'I_8}, where the shuffle group lives,
   and seq nat, where vm_compute reduces. *)
Local Definition ptbl (g : {perm 'I_8}) : seq nat := [seq val (g x) | x <- enum 'I_8].
Local Lemma ptbl_nth (g : {perm 'I_8}) (x : 'I_8) : nth 0 (ptbl g) (val x) = val (g x).
Proof.
rewrite /ptbl (nth_map x) ?size_enum_ord ?ltn_ord //.
by rewrite nth_ord_enum.
Qed.
Local Lemma ptbl_size (g : {perm 'I_8}) : size (ptbl g) = 8.
Proof. by rewrite /ptbl size_map size_enum_ord. Qed.
Local Lemma ptbl_id : ptbl 1%g = idt.
Proof.
apply: (@eq_from_nth _ 0); rewrite ?ptbl_size // => i Hi.
have := ptbl_nth 1%g (Ordinal Hi); rewrite perm1 /= => ->.
by case: i Hi => [|[|[|[|[|[|[|[|k]]]]]]]].
Qed.
Local Lemma size_mtbl (j : nat) : j < 5 -> size (mtbl j) = 8.
Proof. by case: j => [|[|[|[|[|//]]]]]. Qed.
(* A permutation whose images are read off a length-eight list has that list
   as its table. *)
Local Lemma ptbl_of_fwd (g : {perm 'I_8}) (F : seq nat) :
  (forall x, val (g x) = nth 0 F (val x)) -> size F = 8 -> ptbl g = F.
Proof.
move=> Hfwd HF; apply: (@eq_from_nth _ 0); first by rewrite ptbl_size HF.
move=> i; rewrite ptbl_size => Hi.
transitivity (val (g (Ordinal Hi))); first by rewrite -ptbl_nth.
by rewrite Hfwd.
Qed.
(* The tables of the three generators and of the five letters are the mtbl
   entries they were written down as, so the alphabet the BFS closes under is
   the alphabet of the shuffle. *)
Local Lemma ptbl_gen0 : ptbl (tnth pgl27_gens (@Ordinal 3 0 isT)) = mtbl 0.
Proof. by apply: ptbl_of_fwd => //; exact: gfwd0. Qed.
Local Lemma ptbl_gen1 : ptbl (tnth pgl27_gens (@Ordinal 3 1 isT)) = mtbl 2.
Proof. by apply: ptbl_of_fwd => //; exact: gfwd1. Qed.
Local Lemma ptbl_gen2 : ptbl (tnth pgl27_gens (@Ordinal 3 2 isT)) = mtbl 4.
Proof. by apply: ptbl_of_fwd => //; exact: gfwd2. Qed.
Local Lemma ptbl_sym (j : 'I_5) : ptbl (tnth pgl27_sym_sigmas j) = mtbl (val j).
Proof. by apply: ptbl_of_fwd; [exact: mtbl_val | rewrite size_mtbl // ltn_ord]. Qed.
(* ptbl is a morphism: the table of a product is the composition of the two
   tables.  With ptbl_inj this makes ptbl a faithful representation of the
   shuffle group inside seq nat, which is what lets a computation on the 336
   tables settle a question about the group. *)
Local Lemma ptbl_morph (g h : {perm 'I_8}) :
  ptbl (g * h)%g = mcomp (ptbl g) (ptbl h).
Proof.
apply: (@eq_from_nth _ 0); first by rewrite ptbl_size /mcomp size_map ptbl_size.
move=> i; rewrite ptbl_size => Hi.
transitivity (val ((g * h)%g (Ordinal Hi))); first by rewrite -ptbl_nth.
rewrite permM /mcomp (nth_map 0) ?ptbl_size //.
have -> : nth 0 (ptbl g) i = val (g (Ordinal Hi)) by rewrite -ptbl_nth.
by rewrite ptbl_nth.
Qed.
(* Distinct shuffles have distinct tables, so an identity of tables is an
   identity of shuffles. *)
Local Lemma ptbl_inj : injective ptbl.
Proof.
move=> g h Heq; apply/permP => x; apply: val_inj.
by rewrite -(ptbl_nth g) -(ptbl_nth h) Heq.
Qed.
Local Lemma ptbl_gen (i0 : 'I_3) : ptbl (tnth pgl27_gens i0) = mtbl (val i0).*2.
Proof.
by case: i0 => -[|[|[|//]]] Hi0';
  [exact: ptbl_gen0 | exact: ptbl_gen1 | exact: ptbl_gen2].
Qed.

(* Every one-letter successor of a key-table is a key. *)
Local Lemma keys_closed_mem (t : seq nat) (j : nat) :
  t \in unzip1 elem_table -> j \in [:: 0; 1; 2; 3; 4] ->
  mcomp t (mtbl j) \in unzip1 elem_table.
Proof. by move=> /mapP[sw Hsw ->] Hj; exact: elem_closed_mem. Qed.
Local Lemma double_lt3_mem (i0 : 'I_3) : (val i0).*2 \in [:: 0; 1; 2; 3; 4].
Proof. by move: i0 => [[|[|[|m]]] Hm]. Qed.
(* Composing a key with the table of a generator gives a key. *)
Local Lemma gen_key_mem (h : {perm 'I_8}) (t : seq nat) :
  h \in [set tnth pgl27_gens i0 | i0 : 'I_3] ->
  t \in unzip1 elem_table ->
  mcomp t (ptbl h) \in unzip1 elem_table.
Proof.
move=> /imsetP[i0 _ ->] Ht; rewrite ptbl_gen.
exact: (keys_closed_mem Ht (double_lt3_mem i0)).
Qed.

(* Every group element has its table among the closure keys: a group element
   is a product of generators, and the keys are closed under the generators
   and contain the identity.  The keys therefore cover the group. *)
Local Lemma group_key (g : {perm 'I_8}) :
  g \in pgg_G pgl27_M -> ptbl g \in unzip1 elem_table.
Proof.
suff key : forall (n : nat) (c : 'I_n -> {perm 'I_8}),
    (forall i, c i \in [set tnth pgl27_gens i0 | i0 : 'I_3]) ->
    ptbl (\prod_(i < n) c i)%g \in unzip1 elem_table.
  by move=> /gen_prodgP[n [c Hc ->]]; apply: key.
elim=> [|n IH] c Hc.
  by rewrite big_ord0 ptbl_id idt_in_keys.
rewrite big_ord_recr ptbl_morph.
have HP : ptbl (\prod_(i < n) c (widen_ord (leqnSn n) i))%g \in unzip1 elem_table.
  by apply: IH => i; exact: Hc.
exact: (gen_key_mem (Hc ord_max) HP).
Qed.

(* -------------------------------------------------------------------------- *)
(* The reverse direction: each key is the table of a word permutation.        *)
(* -------------------------------------------------------------------------- *)

Local Lemma gen_in_G (i : 'I_3) : tnth pgl27_gens i \in pgg_G pgl27_M.
Proof. by apply: mem_gen; apply/imsetP; exists i. Qed.

(* The perm-level letter selected by a nat index. *)
Local Definition gen5_of (j : nat) : {perm 'I_8} := tnth pgl27_sym_sigmas (inord j).
(* Every letter of the symmetrized alphabet lies in the shuffle group, the
   two inverse letters because a group is closed under inversion.  So
   symmetrizing the alphabet does not enlarge the state space. *)
Local Lemma gen5_of_mem (j : nat) : gen5_of j \in pgg_G pgl27_M.
Proof.
rewrite /gen5_of; move: (inord j : 'I_5) => [[|[|[|[|[|m]]]]] Hm] //;
  rewrite (tnth_nth 1%g) /=.
- exact: (gen_in_G (@Ordinal 3 0 isT)).
- by rewrite groupV; exact: (gen_in_G (@Ordinal 3 0 isT)).
- exact: (gen_in_G (@Ordinal 3 1 isT)).
- by rewrite groupV; exact: (gen_in_G (@Ordinal 3 1 isT)).
- exact: (gen_in_G (@Ordinal 3 2 isT)).
Qed.

(* A letter word folded into the composite shuffle permutation. *)
Local Definition word5_perm (w : seq nat) : {perm 'I_8} :=
  foldl (fun g j => (g * gen5_of j)%g) 1%g w.
Local Lemma word5_perm_mem (w : seq nat) : word5_perm w \in pgg_G pgl27_M.
Proof.
rewrite /word5_perm.
have g1 : (1%g : {perm 'I_8}) \in pgg_G pgl27_M by exact: group1.
elim: w (1%g) g1 => [|j w IH] g gG //=.
by apply: IH; apply: groupM => //; exact: gen5_of_mem.
Qed.
(* The table of the permutation of a letter word is the fold of the letters'
   tables from the identity table.  The BFS's fold over words and the group's
   product over letters are the same object, read through ptbl. *)
Local Lemma ptbl_word5 (w : seq nat) :
  all (fun j => j < 5) w ->
  ptbl (word5_perm w) = foldl (fun t j => mcomp t (mtbl j)) idt w.
Proof.
rewrite /word5_perm.
have gen : forall (w' : seq nat) (g : {perm 'I_8}),
    all (fun j => j < 5) w' ->
    ptbl (foldl (fun h j => (h * gen5_of j)%g) g w') =
    foldl (fun t j => mcomp t (mtbl j)) (ptbl g) w'.
  elim=> [|j w' IH] g //= /andP[Hj Hall].
  rewrite IH //; congr (foldl _ _ _).
  rewrite ptbl_morph; congr (mcomp _ _).
  rewrite /gen5_of ptbl_sym; congr mtbl; exact: (inordK Hj).
by move=> Hw; rewrite (gen w 1%g Hw) ptbl_id.
Qed.

(* The word permutation whose table is the k-th key. *)
Local Definition entry_perm (k : nat) : {perm 'I_8} :=
  word5_perm (nth ([::], [::]) elem_table k).2.
Local Lemma entry_perm_mem (k : nat) : entry_perm k \in pgg_G pgl27_M.
Proof. exact: word5_perm_mem. Qed.
(* The table of entry_perm k is the k-th key.  entry_perm is thus a section of
   the key indexing: every state index the walk uses names an actual shuffle,
   which is the direction group_key does not give. *)
Local Lemma ptbl_entry (k : nat) : k < 336 ->
  ptbl (entry_perm k) = nth [::] (unzip1 elem_table) k.
Proof.
move=> Hk.
have Hin : nth ([::], [::]) elem_table k \in elem_table
  by apply: mem_nth; rewrite size_elem_table.
rewrite /entry_perm (ptbl_word5 (elem_letters Hin)) (elem_fold_key Hin).
by rewrite /unzip1 (nth_map ([::], [::])) ?size_elem_table.
Qed.

(* -------------------------------------------------------------------------- *)
(* The group is exactly the 336 word permutations, counted by their keys.     *)
(* -------------------------------------------------------------------------- *)

Local Lemma keys_size : size (unzip1 elem_table) = 336.
Proof. by rewrite /unzip1 size_map size_elem_table. Qed.
(* Every group element is entry_perm k for some index k below 336.  With
   entry_perm_inj this makes k |-> entry_perm k a bijection from the 336 walk
   states onto the shuffle group. *)
Local Lemma mem_G_Ps (g : {perm 'I_8}) :
  g \in pgg_G pgl27_M -> g \in [seq entry_perm k | k <- iota 0 336].
Proof.
move=> Hg.
have Hk := group_key Hg.
set k := index (ptbl g) (unzip1 elem_table).
have Hklt : k < 336 by rewrite /k -keys_size index_mem.
have Hkey : ptbl (entry_perm k) = ptbl g.
  rewrite (ptbl_entry Hklt).
  exact: (@nth_index _ [::] (ptbl g) (unzip1 elem_table) Hk).
have Hgk : g = entry_perm k by apply: ptbl_inj; rewrite Hkey.
rewrite Hgk; apply: map_f; by rewrite mem_iota /= Hklt.
Qed.
(* Distinct indices below 336 name distinct shuffles, because their keys are
   distinct. *)
Local Lemma entry_perm_inj : {in iota 0 336 &, injective entry_perm}.
Proof.
move=> k1 k2; rewrite !mem_iota /= => Hk1 Hk2 Heq.
have Hs1 : k1 < size (unzip1 elem_table) by rewrite keys_size.
have Hs2 : k2 < size (unzip1 elem_table) by rewrite keys_size.
apply/eqP.
rewrite -(nth_uniq [::] Hs1 Hs2 uniq_elem_keys).
by apply/eqP; rewrite -(ptbl_entry Hk1) -(ptbl_entry Hk2) Heq.
Qed.

(** pgl27_gen5_eq — the symmetrized five-letter alphabet generates the same
    group as the three PGL(2,7) generators.  The realistic word shuffle
    therefore explores exactly the PGL(2,7) shuffle group, neither a subgroup
    nor a larger one, so uniformity on that group is the right mixing
    target. *)
Lemma pgl27_gen5_eq :
  <<[set tnth pgl27_sym_sigmas j | j : 'I_5]>>%G = pgg_G pgl27_M.
Proof.
apply: group_inj => /=; apply/eqP; rewrite eqEsubset; apply/andP; split.
- rewrite gen_subG; apply/subsetP => x /imsetP[j _ ->].
  by move: (gen5_of_mem (val j)); rewrite /gen5_of inord_val.
- rewrite gen_subG; apply/subsetP => x /imsetP[i _ ->].
  apply: mem_gen; apply/imsetP.
  move: i => [[|[|[|//]]] Hi'].
  + by exists (@Ordinal 5 0 isT).
  + by exists (@Ordinal 5 2 isT).
  + by exists (@Ordinal 5 4 isT).
Qed.

(** pgl27_card — the PGL(2,7) shuffle group has exactly 336 elements. The
    in-kernel order of the generated group, tying the walk's 336-entry state
    space to the whole group. *)
Lemma pgl27_card : #|pgg_G pgl27_M| = 336.
Proof.
have Hii : pgg_G pgl27_M =i [seq entry_perm k | k <- iota 0 336].
  move=> g; apply/idP/idP; first exact: mem_G_Ps.
  by move=> /mapP[k _ ->]; exact: entry_perm_mem.
rewrite (eq_card Hii).
have Huniq : uniq [seq entry_perm k | k <- iota 0 336].
  by rewrite map_inj_in_uniq; [exact: iota_uniq | exact: entry_perm_inj].
move/card_uniqP: Huniq => ->.
by rewrite size_map size_iota.
Qed.

(* -------------------------------------------------------------------------- *)
(* Binary-N to nat bridges for decoding the walk certificate.                 *)
(* -------------------------------------------------------------------------- *)

Local Lemma powE (n m : nat) : Nat.pow n m = (n ^ m)%N.
Proof. by elim: m => //= m ->; rewrite expnS multE. Qed.
Local Lemma NtoNat_pow (a b : N) :
  N.to_nat (a ^ b)%num = (N.to_nat a ^ N.to_nat b)%N.
Proof. by rewrite N2Nat.inj_pow powE. Qed.
Local Lemma Nle_nat (a b : N) : (a <= b)%num -> (N.to_nat a <= N.to_nat b)%N.
Proof.
move=> Hle.
have Hadd := congr1 N.to_nat (N.sub_add _ _ Hle).
rewrite N2Nat.inj_add plusE in Hadd.
by rewrite -Hadd leq_addl.
Qed.
Local Lemma foldlN_addsum (I : Type) (g : I -> N) (s : seq I) (a0 : N) :
  N.to_nat (foldl (fun acc i => (acc + g i)%num) a0 s)
  = (N.to_nat a0 + \sum_(i <- s) N.to_nat (g i))%N.
Proof.
elim: s a0 => [|x s IH] a0 /=; first by rewrite big_nil addn0.
by rewrite IH big_cons N2Nat.inj_add plusE addnA.
Qed.

(* -------------------------------------------------------------------------- *)
(* The fibre of a length-L word over the five letters, counted by the walk.   *)
(* -------------------------------------------------------------------------- *)

Local Notation Msym := (Gen_PGGTypes pgl27_sym_sigmas).

(* The shuffle a length-L letter word evaluates to: the ordered product of its
   letters. *)
Local Definition weval (L : nat) (w : L.-tuple 'I_5) : {perm 'I_8} :=
  (\prod_(i < L) tnth pgl27_sym_sigmas (tnth w i))%g.

(* The fibre count of g at length L: how many of the 5^L letter words have
   product g.  Under the uniform letter law every word carries probability
   5^-L, so fibc L g / 5^L is the word-shuffle law at g exactly.  The whole
   certificate is a statement about this one integer sequence. *)
Local Definition fibc (L : nat) (g : {perm 'I_8}) : nat :=
  #|[set w : L.-tuple 'I_5 | weval w == g]|.

(* A word with one further letter appended. *)
Local Definition rc (L : nat) (p : L.-tuple 'I_5 * 'I_5) : L.+1.-tuple 'I_5 :=
  [tuple of rcons p.1 p.2].

(* Appending a letter multiplies the evaluation on the right by that letter.
   The last letter of a word is the last factor of the product, which is why
   the fibre recursion below walks backwards through inverse letters. *)
Local Lemma weval_last (L : nat) (w : L.-tuple 'I_5) (j : 'I_5) :
  weval (rc (w, j)) = (weval w * tnth pgl27_sym_sigmas j)%g.
Proof.
rewrite /weval big_ord_recr /=; congr (_ * _)%g.
- apply: eq_bigr => i _; congr (tnth pgl27_sym_sigmas _).
  by rewrite !(tnth_nth ord0) /= nth_rcons size_tuple ltn_ord.
- congr (tnth pgl27_sym_sigmas _).
  by rewrite (tnth_nth ord0) /= nth_rcons size_tuple ltnn eqxx.
Qed.

(* Appending a letter is a bijection from word-and-letter pairs onto words one
   letter longer, so a sum over the longer words may be reindexed as a double
   sum over shorter words and letters. *)
Local Lemma rc_bij (L : nat) : bijective (@rc L).
Proof.
exists (fun w : L.+1.-tuple 'I_5 =>
  ([tuple tnth w (widen_ord (leqnSn L) i) | i < L], tnth w ord_max)).
- move=> [w j]; rewrite /rc /=; congr (_, _).
  + apply: eq_from_tnth => i; rewrite tnth_mktuple.
    by rewrite !(tnth_nth ord0) /= nth_rcons size_tuple ltn_ord.
  + by rewrite (tnth_nth ord0) /= nth_rcons size_tuple ltnn eqxx.
- move=> w; apply: val_inj => /=.
  apply: (@eq_from_nth _ ord0).
    by rewrite size_rcons size_map size_enum_ord size_tuple.
  move=> i; rewrite size_rcons size_map size_enum_ord => Hi.
  rewrite nth_rcons size_map size_enum_ord.
  case: (ltnP i L) => HiL.
    rewrite (nth_map (Ordinal HiL)) ?size_enum_ord //.
    by rewrite (tnth_nth ord0) /= nth_enum_ord.
  have -> : i = L by apply/eqP; rewrite eqn_leq HiL andbT -ltnS.
  by rewrite eqxx (tnth_nth ord0).
Qed.

(* fibc L.+1 g is the sum over the five letters j of fibc L (g * sigma_j^-1).
   This is the backward recursion the certificate runs: the words reaching g
   in L+1 steps are the words reaching each of g's five predecessors in L.  It
   is stated on the group; walk_step is its image on the 336 state indices. *)
Local Lemma fibc_rec (L : nat) (g : {perm 'I_8}) :
  fibc L.+1 g = \sum_(j < 5) fibc L (g * (tnth pgl27_sym_sigmas j)^-1)%g.
Proof.
rewrite /fibc -sum1dep_card.
rewrite (reindex (@rc L)); last exact: (onW_bij _ (rc_bij L)).
have Hpred : (fun p : L.-tuple 'I_5 * 'I_5 => weval (rc p) == g)
          =1 (fun p => weval p.1 == g * (tnth pgl27_sym_sigmas p.2)^-1)%g.
  move=> p; case: p => w j /=.
  by rewrite weval_last; apply/idP/idP => /eqP H; apply/eqP;
     [rewrite -H mulgK | rewrite H mulgVK].
rewrite (eq_bigl _ _ Hpred) big_mkcond /=.
rewrite -(pair_bigA _ (fun (i : L.-tuple 'I_5) (j : 'I_5) =>
  if weval i == (g * (tnth pgl27_sym_sigmas j)^-1)%g then 1 else 0)) /=.
rewrite exchange_big /=.
apply: eq_bigr => j _.
by rewrite -big_mkcond /= sum1dep_card.
Qed.

(* At length zero the only word is empty, so the fibre count is one at the
   identity and zero elsewhere.  This is the initial condition walkN 0 encodes
   as 1 :: nseq 335 0. *)
Local Lemma fibc0 (g : {perm 'I_8}) : fibc 0 g = (g == 1%g).
Proof.
rewrite /fibc.
have -> : [set w : 0.-tuple 'I_5 | weval w == g]
        = if (g == 1%g) then setT else set0.
  apply/setP => w; rewrite inE /weval big_ord0 eq_sym.
  by case: (g == 1%g); rewrite inE.
by case: (g == 1%g); rewrite ?cardsT ?cards0 ?card_tuple ?card_ord ?expn0.
Qed.

(* -------------------------------------------------------------------------- *)
(* The inverse of each letter reads off the reverse-walk letter's table.      *)
(* -------------------------------------------------------------------------- *)

(* The inversion generator is an involution, so its inverse has its own
   table. *)
Local Lemma ptbl_geninv2 :
  ptbl ((tnth pgl27_gens (@Ordinal 3 2 isT))^-1)%g = mtbl 4.
Proof.
apply: (@ptbl_of_fwd _ (mtbl 4)); last by [].
move=> x; apply: (perm_inv_val (F := mtbl 4)); first exact: gfwd2.
- by case=> [|[|[|[|[|[|[|[|k]]]]]]]].
- by case=> [|[|[|[|[|[|[|[|k]]]]]]]].
Qed.

(* The inverse of letter j has the table of letter inv_letter j.  The five
   reverse steps of the walk are again letters of the alphabet, which is the
   reason the alphabet was symmetrized: the reverse walk needs no table the
   forward walk does not already have. *)
Local Lemma ptbl_inv_letter (j : 'I_5) :
  ptbl ((tnth pgl27_sym_sigmas j)^-1)%g = mtbl (inv_letter (val j)).
Proof.
case: j => -[|[|[|[|[|//]]]]] Hj; rewrite (tnth_nth 1%g) /=.
- exact: (ptbl_sym (@Ordinal 5 1 isT)).
- by rewrite invgK; exact: ptbl_gen0.
- exact: (ptbl_sym (@Ordinal 5 3 isT)).
- by rewrite invgK; exact: ptbl_gen1.
- exact: ptbl_geninv2.
Qed.

(* -------------------------------------------------------------------------- *)
(* The predecessor index and the entry-permutation reverse step.              *)
(* -------------------------------------------------------------------------- *)

Local Lemma mem_unzip1_has (t : seq nat) :
  (t \in unzip1 elem_table)
  = has (fun sw : seq nat * seq nat => sw.1 == t) elem_table.
Proof. by rewrite /unzip1 -has_pred1 has_map. Qed.

(* A key is found at an index below 336, so tbl_index lands in the walk's
   state range. *)
Local Lemma tbl_index_lt (t : seq nat) :
  t \in unzip1 elem_table -> (tbl_index t < 336)%N.
Proof. by rewrite mem_unzip1_has /tbl_index -size_elem_table -has_find. Qed.

(* Reading the key list at the index tbl_index assigns a key returns that key,
   so the indexing is a section of the key list. *)
Local Lemma tbl_index_key (t : seq nat) :
  t \in unzip1 elem_table -> nth [::] (unzip1 elem_table) (tbl_index t) = t.
Proof.
(* The side conditions carrying elem_table must be supplied as premises:
   letting done touch them forces the BFS through lazy kernel reduction
   instead of vm_compute. *)
move=> Ht.
have Hh : has (fun sw : seq nat * seq nat => sw.1 == t) elem_table
  by rewrite -mem_unzip1_has.
have Hlt : (tbl_index t < size elem_table)%N by rewrite /tbl_index -has_find.
rewrite /unzip1 (nth_map ([::], [::]) _ _ Hlt).
by apply/eqP; exact: (nth_find ([::], [::]) Hh).
Qed.

Local Lemma inv_letter_mem (jn : nat) :
  (jn < 5)%N -> inv_letter jn \in [:: 0; 1; 2; 3; 4].
Proof. by move: jn => [|[|[|[|[|]]]]]. Qed.

(* The index of the jn-th reverse-walk predecessor of state k: the key at k
   composed with the table of the inverse of letter jn, looked up again. *)
Local Definition predk (k jn : nat) : nat :=
  tbl_index (mcomp (nth [::] (unzip1 elem_table) k) (mtbl (inv_letter jn))).

Local Lemma predk_mem (k jn : nat) : (k < 336)%N -> (jn < 5)%N ->
  mcomp (nth [::] (unzip1 elem_table) k) (mtbl (inv_letter jn))
    \in unzip1 elem_table.
Proof.
move=> Hk Hjn; apply: keys_closed_mem; last exact: inv_letter_mem.
by apply: mem_nth; rewrite keys_size.
Qed.

Local Lemma predk_lt (k jn : nat) :
  (k < 336)%N -> (jn < 5)%N -> (predk k jn < 336)%N.
Proof. by move=> Hk Hjn; apply: tbl_index_lt; exact: predk_mem. Qed.

(* entry_perm k * sigma_j^-1 is entry_perm (predk k j), for k below 336.  The
   index arithmetic of pred_table is right multiplication by the inverse
   letter on the group, so the five predecessor slots the walk reads at k name
   the five group predecessors of the shuffle entry_perm k. *)
Local Lemma entry_pred (k : nat) (j : 'I_5) : (k < 336)%N ->
  (entry_perm k * (tnth pgl27_sym_sigmas j)^-1)%g = entry_perm (predk k (val j)).
Proof.
move=> Hk.
have Hpred : (predk k (val j) < 336)%N by apply: predk_lt => //; exact: ltn_ord.
apply: ptbl_inj.
rewrite (ptbl_entry Hpred) /predk (tbl_index_key (predk_mem Hk (ltn_ord j))).
by rewrite ptbl_morph (ptbl_entry Hk) (ptbl_inv_letter j).
Qed.

(* -------------------------------------------------------------------------- *)
(* One walk step reads the five reverse-walk predecessors.                    *)
(* -------------------------------------------------------------------------- *)

Local Lemma size_pred_table : size pred_table = 336.
Proof. by rewrite /pred_table size_map size_elem_table. Qed.

(* Row k of pred_table lists the five predecessor indices of state k. *)
Local Lemma nth_pred_table (k : nat) : (k < 336)%N ->
  nth [::] pred_table k = [seq predk k j | j <- [:: 0; 1; 2; 3; 4]].
Proof.
move=> Hk.
have Hk' : (k < size elem_table)%N by rewrite size_elem_table.
rewrite /pred_table (nth_map ([::], [::]) _ _ Hk').
apply: eq_map => j; rewrite /predk.
by rewrite /unzip1 (nth_map ([::], [::]) _ _ Hk').
Qed.

(* One step of the walk rereads pred_table: each new entry is the sum of the
   previous vector over that state's five predecessor slots. *)
Local Lemma walkS (L : nat) :
  walkN L.+1
  = [seq foldl (fun acc i => (acc + nth 0%num (walkN L) i)%num) 0%num preds
    | preds <- pred_table].
Proof. by []. Qed.

(* The walk vector has one entry per state at every length. *)
Local Lemma size_walkN (L : nat) : size (walkN L) = 336.
Proof.
case: L => [|L']; first by [].
by rewrite walkS size_map size_pred_table.
Qed.

(* Read in nat, walkN L.+1 at k is the sum of walkN L over the five entries of
   row k of pred_table.  This is fibc_rec transported to the state indices,
   with the walk's binary-N additions read as nat sums. *)
Local Lemma walk_step (L k : nat) : (k < 336)%N ->
  N.to_nat (nth 0%num (walkN L.+1) k)
  = \sum_(j < 5) N.to_nat (nth 0%num (walkN L) (predk k (val j))).
Proof.
move=> Hk.
have Hkp : (k < size pred_table)%N by rewrite size_pred_table.
rewrite walkS (nth_map [::] _ _ Hkp) (nth_pred_table Hk) foldlN_addsum.
rewrite [N.to_nat 0%num]/= add0n big_map.
rewrite -[ [:: 0; 1; 2; 3; 4] ]/(index_iota 0 5) big_mkord.
exact: erefl.
Qed.

(* fibc L (entry_perm k) is the k-th entry of walkN L, for every k below 336.
   This is the bridge between the two layers: the binary-N vector the kernel
   computes is the fibre-count function of the shuffle group, so the 336
   numbers vm_compute produced at L = 200 are the unnormalized word-shuffle
   law. *)
Local Lemma fiber_count (L k : nat) : (k < 336)%N ->
  fibc L (entry_perm k) = N.to_nat (nth 0%num (walkN L) k).
Proof.
elim: L k => [|L IH] k Hk.
- rewrite fibc0.
  have Hek : (entry_perm k == 1%g) = (k == 0).
    apply/idP/idP.
    - move/eqP => H1k.
      have H0 : (0 < size elem_table)%N by rewrite size_elem_table.
      have Hp : nth [::] (unzip1 elem_table) k = nth [::] (unzip1 elem_table) 0.
        rewrite -(ptbl_entry Hk) H1k ptbl_id.
        by rewrite /unzip1 (nth_map ([::], [::]) _ _ H0) elem_table0.
      have Hks : (k < size (unzip1 elem_table))%N by rewrite keys_size.
      have H0s : (0 < size (unzip1 elem_table))%N by rewrite keys_size.
      move: Hp => /eqP.
      rewrite (nth_uniq _ Hks H0s uniq_elem_keys).
      by move/eqP => ->.
    - by move/eqP => ->; rewrite /entry_perm elem_table0 /word5_perm.
  rewrite Hek.
  case: k {Hek} Hk => [|k'] Hk; first by [].
  rewrite -[walkN 0]/(1%num :: nseq 335 0%num).
  rewrite -[nth 0%num (1%num :: nseq 335 0%num) k'.+1]
           /(nth 0%num (nseq 335 0%num) k').
  by rewrite nth_nseq if_same.
- rewrite fibc_rec (@walk_step L k Hk).
  apply: eq_bigr => j _.
  rewrite (@entry_pred k j Hk) (IH _ (predk_lt Hk (ltn_ord j))).
  exact: erefl.
Qed.

(* -------------------------------------------------------------------------- *)
(* Words evaluate inside the shuffle group; the certificate in nat.           *)
(* -------------------------------------------------------------------------- *)

Local Lemma sym_in_G (j : 'I_5) : tnth pgl27_sym_sigmas j \in pgg_G pgl27_M.
Proof. by move: (gen5_of_mem (val j)); rewrite /gen5_of inord_val. Qed.

(* Every letter word evaluates inside the shuffle group, so the word shuffle
   puts no mass outside the support of the uniform law it is compared with. *)
Local Lemma word_eval_in_G (L : nat) (w : L.-tuple 'I_5) :
  weval w \in pgg_G pgl27_M.
Proof. by apply: group_prod => i _; exact: sym_in_G. Qed.

(* A 336-vector meeting the binary-N certificate inequality meets it in nat:
   2^40 times the total absolute deviation of its entries from the uniform
   value, over the common denominator, is at most 336 * 5^200. *)
Local Lemma cert_decode (v : seq N) :
  size v = 336 ->
  ((2 ^ 40) * foldl (fun acc c => (acc + absdiffN (336 * c) (5 ^ 200)%num)%num)
     0%num v <=? 336 * (5 ^ 200))%num ->
  (2 ^ 40 * (\sum_(k < 336)
       N.to_nat (absdiffN (336 * nth 0%num v k) (5 ^ 200)%num))
   <= 336 * 5 ^ 200)%N.
Proof.
(* The vector v is kept abstract: with v free the numeral rewrites' match
   attempts fail fast instead of forcing the walk through lazy kernel
   reduction. *)
move=> Hsz /N.leb_le/Nle_nat H.
have e2 : N.to_nat 2 = 2 by [].
have e5 : N.to_nat 5 = 5 by [].
have e40 : N.to_nat 40 = 40 by [].
have e200 : N.to_nat 200 = 200 by [].
have e336 : N.to_nat 336 = 336 by [].
move: H.
rewrite !N2Nat.inj_mul !multE !NtoNat_pow e2 e5 e40 e200 e336.
rewrite foldlN_addsum [N.to_nat 0%num]/= add0n.
rewrite (big_nth 0%num) Hsz big_mkord.
move=> H; exact: H.
Qed.

(* The length-200 walk vector meets the nat certificate.  This is the only
   fact about the 336 computed numbers that the real-valued argument uses. *)
Local Lemma mixing_cert_nat :
  (2 ^ 40 * (\sum_(k < 336)
       N.to_nat (absdiffN (336 * nth 0%num (walkN 200) k) (5 ^ 200)%num))
   <= 336 * 5 ^ 200)%N.
Proof.
exact: (cert_decode (size_walkN 200) mixing_bound_okT).
Qed.

(* -------------------------------------------------------------------------- *)
(* The realistic-shuffle mixing bound at L = 200.                             *)
(* -------------------------------------------------------------------------- *)

Section pgl27_mixing_sec.
Variable R : realType.
Import GRing.Theory Num.Theory.
Local Open Scope ring_scope.
Local Open Scope fdist_scope.
Local Open Scope proba_scope.

(** Wuni — the uniform letter distribution of the realistic word shuffle. The
    letter law of the L-word shuffle. *)
Definition Wuni : R.-fdist 'I_5 := fdist_uniform (card_ord 5).

(* The nat image of a binary-N absolute difference is the real absolute
   difference of the two images.  It carries the certificate's absolute values
   into the variation-distance sum. *)
Local Lemma absN_toR (a b : N) :
  (N.to_nat (absdiffN a b))%:R = `|(N.to_nat a)%:R - (N.to_nat b)%:R| :> R.
Proof.
rewrite /absdiffN; case: ifPn => H.
- move/N.ltb_lt/N.lt_le_incl: H => Hle.
  have Hadd := congr1 N.to_nat (N.sub_add _ _ Hle).
  rewrite N2Nat.inj_add plusE in Hadd.
  have Hsub : (N.to_nat (b - a) = N.to_nat b - N.to_nat a)%N by rewrite -Hadd addnK.
  have Hle2 : (N.to_nat a <= N.to_nat b)%N by rewrite -Hadd leq_addl.
  by rewrite Hsub natrB // ler0_norm ?subr_le0 ?ler_nat // opprB.
- move/negbTE: H => /N.ltb_ge Hle.
  have Hadd := congr1 N.to_nat (N.sub_add _ _ Hle).
  rewrite N2Nat.inj_add plusE in Hadd.
  have Hsub : (N.to_nat (a - b) = N.to_nat a - N.to_nat b)%N by rewrite -Hadd addnK.
  have Hle2 : (N.to_nat b <= N.to_nat a)%N by rewrite -Hadd leq_addl.
  by rewrite Hsub natrB // ger0_norm ?subr_ge0 ?ler_nat.
Qed.

(* c / D - 1 / 336 = (336 c - D) / (336 D).  Each of the 336 deviations from
   uniform is put over the single denominator 336 * 5^200, so their sum is the
   one integer the certificate bounds. *)
Local Lemma frac_diff (c D : nat) : (0 < D)%N ->
  c%:R / D%:R - 336%:R^-1 = ((336 * c)%:R - D%:R) / (336 * D)%:R :> R.
Proof.
move=> DP.
have HD : (D%:R : R) != 0 by rewrite pnatr_eq0 -lt0n.
have H336 : (336%:R : R) != 0 by rewrite pnatr_eq0.
have HDD : ((336 * D)%:R : R) != 0 by rewrite pnatr_eq0 muln_eq0 negb_or -!lt0n DP.
apply: (mulIf HDD).
rewrite divfK // natrM mulrBl natrM; congr (_ - _).
  by rewrite mulrCA divfK // mulrC.
by rewrite mulrA mulVf // mul1r.
Qed.

(* A numerator meeting 2^40 * SN <= 336 * D has SN / (336 D) <= 2^-40.  The
   last step of the chain, turning the integer certificate into the stated
   real bound. *)
Local Lemma final_bound_gen (SN D : nat) :
  (0 < D)%N -> (2 ^ 40 * SN <= 336 * D)%N ->
  SN%:R / (336 * D)%:R <= 2%:R^-40 :> R.
Proof.
move=> DP Hc.
have HDD : (0 < (336 * D)%:R :> R) by rewrite ltr0n muln_gt0 DP.
rewrite ler_pdivrMr //.
have -> : 2%:R^-40 * (336 * D)%:R = (336 * D)%:R / (2 ^ 40)%:R :> R.
  by rewrite natrX -exprVn mulrC.
rewrite ler_pdivlMr ?ltr0n ?expn_gt0 //.
by rewrite -natrM ler_nat mulnC.
Qed.

(* The word-shuffle law at g is fibc 200 g / 5^200: under the uniform letter
   law each of the 5^200 words has the same probability, so the law of the
   product is the fibre count divided by the number of words.  This is where
   the counting layer meets the probability layer. *)
Local Lemma rho_valE (g : {perm 'I_8}) :
  @rho_from_words_weighted R 6 4 200 pgl27_sym_sigmas Wuni g
  = (fibc 200 g)%:R / (5 ^ 200)%:R.
Proof.
rewrite fiber_prob_weighted.
rewrite (eq_bigr (fun=> (5 ^ 200)%:R^-1)); last first.
  move=> w _.
  rewrite word_weightedE.
  under eq_bigr => i _ do rewrite /Wuni fdist_uniformE card_ord.
  by rewrite prodr_const card_ord exprVn natrX.
by rewrite sumr_const [X in _ = X]mulrC mulr_natr; congr (_ *+ _).
Qed.

(* The word-shuffle law is within 2^-40 of the uniform law on Gg in variation
   distance, given that Gg has 336 elements injectively enumerated by ep, that
   every word evaluates inside Gg, that the fibre count of ep k is the k-th
   entry of vN, and that vN meets the nat certificate.  The bound is
   unconditional and information-theoretic: no computational assumption enters
   at any point.  Stated over abstract Gg, ep and vN so that the single
   vm_compute of the 336 counts is all the real-valued argument depends on;
   pgl27_word_mixing supplies the four PGL(2,7) witnesses. *)
Local Lemma mixing_bound_gen
  (Gg : {group {perm 'I_8}}) (ep : nat -> {perm 'I_8}) (vN : nat -> N)
  (GposH : (0 < #|Gg|)%N) :
  #|Gg| = 336 ->
  (forall g, g \in Gg -> g \in [seq ep k | k <- iota 0 336]) ->
  {in iota 0 336 &, injective ep} ->
  (forall k, ep k \in Gg) ->
  (forall k, (k < 336)%N -> fibc 200 (ep k) = N.to_nat (vN k)) ->
  (forall w : 200.-tuple 'I_5, weval w \in Gg) ->
  (2 ^ 40 * (\sum_(k < 336) N.to_nat (absdiffN (336 * vN k) (5 ^ 200)%num))
   <= 336 * 5 ^ 200)%N ->
  var_dist (@rho_from_words_weighted R 6 4 200 pgl27_sym_sigmas Wuni) (`U GposH)
  <= 2%:R^-40.
Proof.
move=> Hcard mem_Gg ep_inj ep_mem fibcnt word_in_G Hcert.
rewrite /var_dist (bigID (fun g => g \in Gg)) /=.
rewrite [X in _ + X]big1 ?addr0; last first.
  move=> g Hg.
  have Hf0 : fibc 200 g = 0.
    rewrite /fibc; apply/eqP; rewrite cards_eq0; apply/eqP; apply/setP => w.
    rewrite !inE; apply/negbTE; apply: contra Hg => /eqP <-; exact: word_in_G.
  by rewrite rho_valE Hf0 mul0r fdist_uniform_supp_notin // subr0 normr0.
have Hperm : perm_eq (enum Gg) [seq ep k | k <- iota 0 336].
  apply: uniq_perm; first exact: enum_uniq.
    by rewrite (map_inj_in_uniq ep_inj); exact: iota_uniq.
  move=> g; rewrite mem_enum.
  apply/idP/idP; first exact: mem_Gg.
  by move=> /mapP[k _ ->]; exact: ep_mem.
rewrite -big_enum (perm_big _ Hperm) big_map.
rewrite -[iota 0 336]/(index_iota 0 336) big_mkord.
rewrite (eq_bigr (fun i : 'I_336 =>
  (N.to_nat (absdiffN (336 * vN i) (5 ^ 200)%num))%:R / (336 * 5 ^ 200)%:R));
    last first.
  move=> i _.
  rewrite rho_valE (fibcnt _ (ltn_ord i)) fdist_uniform_supp_in ?ep_mem // Hcard.
  rewrite frac_diff ?expn_gt0 // normrM normfV.
  rewrite (absN_toR (336 * vN i)%num (5 ^ 200)%num) N2Nat.inj_mul multE NtoNat_pow.
  by rewrite [`|(336 * 5 ^ 200)%:R|]ger0_norm ?ler0n.
rewrite -mulr_suml -natr_sum.
by apply: final_bound_gen; [rewrite expn_gt0 | exact: Hcert].
Qed.

(** pgl27_word_mixing — the law of a uniform 200-letter generator word is
    within 2^-40 of the uniform shuffle in variation distance.  The bound is
    unconditional and information-theoretic, a counting fact about the 5^200
    words with no computational assumption anywhere, so any statement proved
    of the idealised uniform shuffle transfers to the shuffle a dealer can
    actually perform at a cost of 2^-40. *)
Lemma pgl27_word_mixing :
  var_dist (@rho_from_words_weighted R 6 4 200 pgl27_sym_sigmas Wuni)
           (`U pgl27_G_pos)
  <= 2%:R^-40.
Proof.
apply: (@mixing_bound_gen (pgg_G pgl27_M)%G entry_perm
  (fun k => nth 0%num (walkN 200) k) pgl27_G_pos pgl27_card mem_G_Ps
  entry_perm_inj entry_perm_mem (fun k : nat => @fiber_count 200 k)
  (@word_eval_in_G 200) mixing_cert_nat).
Qed.

(** pgl27_endpoint_mixing — each single-card marginal of the 200-letter word
    shuffle is within 2^-40 of uniform.  What one seat holds after the
    realistic shuffle is a uniformly dealt card to within 2^-40; the exact
    shuffle makes that marginal exactly uniform, and this is the price of
    replacing it by a finite word. *)
Lemma pgl27_endpoint_mixing (s : 'I_8) :
  var_dist (@endpoint_dist_weighted R 6 4 200 pgl27_sym_sigmas Wuni s)
           (fdist_uniform (card_ord 8))
  <= 2%:R^-40.
Proof.
rewrite -(pgl27_point_uniform R s).
apply: Order.POrderTheory.le_trans pgl27_word_mixing.
exact: (var_dist_fdistmap (fun sigma : {perm 'I_8} => sigma s)).
Qed.

(* Two products with the same first marginal are as far apart as their second
   marginals.  Tensoring the shuffle law with an independent secret prior
   therefore neither creates nor destroys variation distance. *)
Local Lemma var_dist_prodR (A B : finType) (P : R.-fdist A)
    (Q1 Q2 : R.-fdist B) :
  var_dist (P `x Q1) (P `x Q2) = var_dist Q1 Q2.
Proof.
rewrite /var_dist.
under eq_bigr => ab _ do
  rewrite !fdist_prodE -mulrBr normrM (ger0_norm (FDist.ge0 _ _)).
rewrite -(pair_bigA _ (fun a b => P a * `|Q1 b - Q2 b|)) /=.
rewrite exchange_big /=.
apply: eq_bigr => b _.
by rewrite -big_distrl /= FDist.f1 mul1r.
Qed.

(** pgl27_joint_mixing — the joint secret-and-shuffle law of the 200-letter
    word run is within 2^-40 of the exact-shuffle joint law. Every observable
    of the realistic-shuffle run differs from the exact-shuffle one by at most
    2^-40 in variation distance. *)
Lemma pgl27_joint_mixing (secretP : R.-fdist bool) :
  var_dist
    (secretP `x (@rho_from_words_weighted R 6 4 200 pgl27_sym_sigmas Wuni))
    (secretP `x (`U pgl27_G_pos))
  <= 2%:R^-40.
Proof.
rewrite var_dist_prodR.
exact: pgl27_word_mixing.
Qed.

End pgl27_mixing_sec.
