#!/usr/bin/env python3
"""Rayleigh certificate for the PGL(2,7) Schreier walk on P^1(F_7).

Generators (pgl27_mixing.pgl27_moves): z+1, (z+1)^-1, 3z, (3z)^-1, -1/z,
acting on 'I_8 with 7 = the point at infinity.  Q is the 8x8 Schreier
transition matrix Q(x,y) = #{k : sigma_k x = y} / 5.

Certified statement (consumed by pgl27_spectral.v):
  for every column 8-vector v with sum v_i = 0,
      <v, Q^2 v> <= alpha^2 <v, v>,      alpha = 7/8.

Certificate shape (kernel-checkable with small rationals):
  M' := alpha^2 I - Q^2 + (c/8) J        (J = all-ones; J v = 0 on sum-zero v)
  M'  = L D L^T + E   exactly over Q,
  D >= 0 entrywise, E row- and column-diagonally dominant with E_ii >= 0.
Then v^T M' v = v^T L D L^T v + v^T E v >= 0 for all v, and on sum-zero v
the J term vanishes, giving the Rayleigh bound.

L is the exact LDL^T of M' - eps I rounded to 1/den; D is the exact pivot
list floored to 1/den; E is the exact residual.  Rounding keeps every
number small enough for tactic-level rational arithmetic.

Run:  python3 pgl27_spectral_certificate.py        (prints Rocq literals)
Exit status 1 if any check fails.
"""
from fractions import Fraction as F
import math, sys

p, INF, N, Tg = 7, 7, 8, 5
ALPHA, C, EPS, DEN = F(7, 8), F(1, 4), F(1, 100), 100


def moeb(a, b, c, d, z):
    if z == INF:
        return INF if c % p == 0 else (a * pow(c, -1, p)) % p
    den = (c * z + d) % p
    return INF if den == 0 else ((a * z + b) * pow(den, -1, p)) % p


def inverse(perm):
    r = [0] * N
    for i, j in enumerate(perm):
        r[j] = i
    return r


tr = [moeb(1, 1, 0, 1, z) for z in range(N)]
sc = [moeb(3, 0, 0, 1, z) for z in range(N)]
inv = [moeb(0, -1, 1, 0, z) for z in range(N)]
gens = [tr, inverse(tr), sc, inverse(sc), inv]


def mm(A, B):
    return [[sum(A[i][k] * B[k][j] for k in range(len(B))) for j in range(len(B[0]))]
            for i in range(len(A))]


def T(A):
    return [[A[j][i] for j in range(len(A))] for i in range(len(A[0]))]


Q = [[F(sum(1 for g in gens if g[x] == y), Tg) for y in range(N)] for x in range(N)]
Q2 = mm(Q, Q)
Mp = [[(ALPHA * ALPHA if i == j else 0) - Q2[i][j] + C / N for j in range(N)] for i in range(N)]


def ldl(S):
    n = len(S)
    L = [[F(0)] * n for _ in range(n)]
    D = [F(0)] * n
    for j in range(n):
        D[j] = S[j][j] - sum(L[j][k] ** 2 * D[k] for k in range(j))
        L[j][j] = F(1)
        for i in range(j + 1, n):
            L[i][j] = (S[i][j] - sum(L[i][k] * L[j][k] * D[k] for k in range(j))) / D[j]
    return L, D


Me = [[Mp[i][j] - (EPS if i == j else 0) for j in range(N)] for i in range(N)]
Lx, Dx = ldl(Me)
L = [[F(round(x * DEN), DEN) for x in r] for r in Lx]
D = [F(math.floor(d * DEN), DEN) for d in Dx]
E = [[Mp[i][j] - sum(L[i][k] * D[k] * L[j][k] for k in range(N)) for j in range(N)]
     for i in range(N)]

ok = True
ok &= all(Q[i][j] == Q[j][i] for i in range(N) for j in range(N))
ok &= all(sum(Q[i]) == 1 for i in range(N)) and all(sum(Q[i][j] for i in range(N)) == 1 for j in range(N))
ok &= all(d >= 0 for d in D)
ok &= all(E[i][i] >= sum(abs(E[i][j]) for j in range(N) if j != i) for i in range(N))
ok &= all(E[j][j] >= sum(abs(E[i][j]) for i in range(N) if i != j) for j in range(N))
ok &= all(Mp[i][j] == sum(L[i][k] * D[k] * L[j][k] for k in range(N)) + E[i][j]
          for i in range(N) for j in range(N))

# numerically locate lambda_2 (power iteration on the sum-zero subspace), report only
Qf = [[float(q) for q in r] for r in Q]
import random
random.seed(1)
lam = 0.0
for _ in range(3):
    v = [random.random() for _ in range(N)]
    m = sum(v) / N
    v = [x - m for x in v]
    for _ in range(4000):
        w = [sum(Qf[i][j] * v[j] for j in range(N)) for i in range(N)]
        w = [sum(Qf[i][j] * w[j] for j in range(N)) for i in range(N)]
        m = sum(w) / N
        w = [x - m for x in w]
        n = math.sqrt(sum(x * x for x in w))
        v = [x / n for x in w]
    w = [sum(Qf[i][j] * v[j] for j in range(N)) for i in range(N)]
    w = [sum(Qf[i][j] * w[j] for j in range(N)) for i in range(N)]
    lam = max(lam, sum(a * b for a, b in zip(v, w)))


def table(name, M, den):
    print(f"(* {name}, entries scaled by {den} *)")
    for r in M:
        print("  [:: " + "; ".join(str(int(x * den)) for x in r) + " ]")


print("(* generated by pgl27_spectral_certificate.py *)")
print(f"(* alpha = {ALPHA}, c = {C}, eps = {EPS}, den = {DEN};"
      f" numerically lambda_2^2 ~ {lam:.6f}, alpha^2 = {float(ALPHA*ALPHA):.6f} *)")
print("(* generators tr tr^-1 sc sc^-1 inv on 'I_8: *)")
for g in gens:
    print("  " + str(g))
table("Q", Q, 5)
table("Q^2", Q2, 25)
table("M' = 49/64 I - Q^2 + (1/32) J", Mp, 1600)
table("L", L, DEN)
print("(* D, scaled by %d *)" % DEN)
print("  [:: " + "; ".join(str(int(d * DEN)) for d in D) + " ]")
ED = 1600 * DEN ** 3
table("E", E, ED)
print("(* E common denominator: %d *)" % ED)
A = [[abs(E[i][j]) if i != j else F(0) for j in range(N)] for i in range(N)]
table("A = |E| off the diagonal, 0 on it", A, ED)
ok &= all(sum(A[i]) <= E[i][i] for i in range(N))
ok &= all(sum(A[i][j] for i in range(N)) <= E[j][j] for j in range(N))
# reduced-form integer tables: every table above is integral after scaling,
# so pgl27_spectral.v can state the certificate over int literals.
g = 0
for r in E:
    for x in r:
        g = math.gcd(g, int(x * ED))
print("(* gcd of the scaled E entries: %d; E and A can be stated over denominator %d *)" % (g, ED // g))
table("E reduced", E, ED // g)
table("A reduced", A, ED // g)
print("(* slack per row (E_ii - sum_{j<>i} |E_ij|): *)")
print("  " + str([str(E[i][i] - sum(abs(E[i][j]) for j in range(N) if j != i)) for i in range(N)]))
print("(* all checks passed: %s *)" % ok)
sys.exit(0 if ok else 1)
