#!/usr/bin/env python3
"""Generate the four edited files of landing 4 from their bases.

Landing 3 and landing 4 both edit manifest/pgg_analysis_manifest.v and
manifest/pgg_analysis_client.v, so landing 3's STAGED text is the base of
those two.  instances/psl211/psl211_analysis.v and
instances/psl211/psl211_reading_constancy.v are edited by landing 4 alone, so
PRODUCTION is their base.  All four are GENERATED by the anchored operations
below and never hand-edited.  When a base moves, restage.py copies the new
base and calls this script again, which is what makes the rebase mechanical.

Every operation is one exact anchor and one replacement.  An anchor that is
not found, or found more than once, is an error and nothing is written.

Usage:  python3 rebase_shared.py            write the four staged files
        python3 rebase_shared.py --check    report only
"""

import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
BASE = os.path.join(os.path.dirname(HERE),
                    "2026-09-20-tableau-extensions-landing3", "staged")
PROD = os.path.dirname(os.path.dirname(os.path.dirname(HERE)))
OUT = os.path.join(HERE, "staged")


def banner(lines):
    """A block of 80-column Rocq banner comment lines."""
    return "\n".join(("(* " + l).ljust(78) + "*)" for l in lines) + "\n"

# --------------------------------------------------------------------------
# manifest/pgg_analysis_manifest.v
# --------------------------------------------------------------------------

M_HEADER_ANCHOR = """\
(* claimed, its exact capability, its completion level and its assumption     *)
(* status.                                                                    *)
(*                                                                            *)
"""

M_HEADER = """\
(* claimed, its exact capability, its completion level and its assumption     *)
(* status.                                                                    *)
(*                                                                            *)
(* A row records no security arm. Which arm a published program carries is    *)
(* read off that program by security_arm_of of manifest/pgg_tableau.v, so     *)
(* which arm a path carries is told from the certificate its table names and  *)
(* not from a field of the record.                                            *)
(*                                                                            *)
"""

M_ROW9_ANCHOR = """\
(* | missing premise      | none: the cut this model draws is the uniform     *)
(*                          distribution on the group already, so the path    *)
(*                          compares no idealized model |                     *)
"""

M_ROW9 = """\
(* | missing premise      | none: the cut this model draws is the uniform     *)
(*                          distribution on the group already, so the path    *)
(*                          compares no idealized model. It is the model the  *)
(*                          proximity certificate of Row 11 names as its      *)
(*                          ideal |                                           *)
"""

M_BLOCK_ANCHOR = """\
(*     Aliases carrying no capability yet                                     *)
"""

M_BLOCK = """\
(*     Row 11: twelve-card chirality instance, 584-letter word dealer         *)
(*                                                                            *)
(* | field | value |                                                          *)
(* |---|---|                                                                  *)
(* | protocol family and model | PSL(2,11) twelve-card chirality deck; the    *)
(*                               deck description drawn uniformly over all of *)
(*                               them and the cut drawn by evaluating a word  *)
(*                               of 584 letters, each letter uniform over the *)
(*                               three generators, the two independent |      *)
(* | profile alias      | PSL211Analysis.profile |                            *)
(* | execution alias    | PSL211Analysis.exec_plug |                          *)
(* | observed alias     | PSL211Analysis.observed |                           *)
(* | sample alias       | PSL211Analysis.word_sample; the row's typed model   *)
(*                        witness is PSL211Analysis.word_family, the family   *)
(*                        indexed by unit |                                   *)
(* | observers          | sa_coalition_view of                                *)
(*                        security/pgg_sample_adapter.v at word_sample        *)
(*                          : {ffun 'I_12 -> 'I_12}, executed;                *)
(*                        static_coalition_obs of protocol/pgg_instance.v     *)
(*                          : {ffun 'I_12 -> 'I_12}, the reading the          *)
(*                            certificate's distance field is stated at;      *)
(*                        PSL211Analysis.secret : bool, a random variable on  *)
(*                          the law of word_sample |                          *)
(* | distribution-to-observer bridges | psl211_word_sampleP_E and             *)
(*                        psl211_word_cut_distE of                            *)
(*                        instances/psl211/psl211_word_model.v, which name    *)
(*                        the adapter's own law and its cut law; the row's    *)
(*                        reading is the framework's own sa_coalition_view at *)
(*                        word_sample, which the adapter's projections make   *)
(*                        the all-decks reading, so no facade-level reading   *)
(*                        bridge is named |                                   *)
(* | bound or certificate | psl211_word_proximity_cert of                     *)
(*                          instances/psl211/psl211_word_proximity.v, whose   *)
(*                          number is 2^-40 and whose distance field is       *)
(*                          psl211_word_proximity_close |                     *)
(* | final bridge theorem | psl211_word_view_proximity of                     *)
(*                          instances/psl211/psl211_word_proximity.v |        *)
(* | correctness theorem  | PSL211Analysis.observed_recovers,                 *)
(*                          PSL211Analysis.secret_expectedE |                 *)
(* | model transfer       | an idealized uniform shuffle replaced by a word   *)
(*                          of 584 letters: psl211_word_law_le40 bounds the   *)
(*                          two models' laws at 2^-40 and                     *)
(*                          psl211_word_proximity_close carries that number   *)
(*                          to the joint law of a coalition's reading with    *)
(*                          the chirality, in the sum of absolute             *)
(*                          differences |                                     *)
(* | missing premise      | none: the row's certificate carries its own       *)
(*                          distance field |                                  *)
(* | completion level     | AnalysisBridged |                                 *)
(* | transfer status      | IdealFinite |                                     *)
(* | assumption status    | BaselineClassicalOnly |                           *)
(* | typed row            | psl211_row_word |                                 *)
(*                                                                            *)
(* Capabilities, one line per (theorem, distribution, observer, notion):      *)
(*                                                                            *)
(* | theorem | distribution | observer | notion |                             *)
(* |---|---|---|---|                                                          *)
(* | psl211_word_view_proximity | the law of word_sample                      *)
(*   | sa_coalition_view at a coalition of at most five of the twelve seats   *)
(*   | proximity to a private ideal model |                                   *)
(* | observed_recovers | none, the statement is distribution-free             *)
(*   | the executed endpoint list | correctness |                             *)
(* | secret_expectedE | none, the statement is distribution-free              *)
(*   | the value the run recovers | correctness |                             *)
(*                                                                            *)
(* Level justification. profile gives Algebraic; exec_plug is indexed by      *)
(* profile, giving Executable; observed is the ObservedExecution over that    *)
(* profile and plug, giving Observed; word_sample is a SampleAdapter over     *)
(* that plug and psl211_word_cut_distE identifies its cut distribution with   *)
(* the 584-letter word law, giving Sampled; psl211_word_view_proximity is a   *)
(* security theorem stated at this model's own law and at that model's        *)
(* coalition reader, giving AnalysisBridged. The proximity line quantifies    *)
(* over coalitions of at most five of the twelve seats, the profile's own     *)
(* privacy threshold being six. Its number bounds a sum of absolute           *)
(* differences, which is twice the total variation distance of the            *)
(* literature, so a distinguisher's advantage against this row is at most     *)
(* 2^-41. Row 9 records the same instance and the same execution at the       *)
(* uniform cut, and the model of Row 9 is the ideal this row's certificate    *)
(* is measured against. The two models differ in the law of the cut alone.    *)
(* The two rows differ in the model family and in the transfer status, and    *)
(* they carry different statements, Row 9 exact independence and this row a   *)
(* bound on the distance to that independent model. The propositions refuted  *)
(* in instances/psl211/psl211_reading_constancy.v are instances of            *)
(* coalition_reading_constancy, which                                         *)
(* indistinguishability_cert_reading_constancy reads as ic_const, the fifth   *)
(* field of an input-indistinguishability certificate and a field a proximity *)
(* certificate has no counterpart of. Those refutations stay true beside this *)
(* row.                                                                       *)
(*                                                                            *)
(*     Aliases carrying no capability yet                                     *)
"""

M_ROW_ANCHOR = """\
Definition pgl27_row_prior_exact : AnalysisPathRow :=
  @MkAnalysisPathRow PGL27Analysis.observed AnalysisBridged
    PGL27Analysis.prior_exact_family StaticExecutedOnly BaselineClassicalOnly.
"""

M_ROW = M_ROW_ANCHOR + """
(** The AnalysisPathRow for the twelve-card chirality instance under a
    shuffle of 584 letters: PSL211Analysis.observed paired with the
    unit-indexed word family, AnalysisBridged, IdealFinite,
    BaselineClassicalOnly.  psl211_word_view_proximity is proved at this
    row's own sample distribution and at that distribution's coalition
    reader, which is what reaches AnalysisBridged; the cut is a word a dealer
    can perform where psl211_row_alldecks draws it uniformly from the group,
    so an idealized shuffle is replaced by a finite one, which is the
    IdealFinite status. It differs from psl211_row_alldecks in the model
    family and in the transfer status, and the model of that row is the ideal
    the certificate behind this one is measured against. *)
Definition psl211_row_word : AnalysisPathRow :=
  @MkAnalysisPathRow PSL211Analysis.observed AnalysisBridged
    PSL211Analysis.word_family IdealFinite BaselineClassicalOnly.
"""

M_PIN_ANCHOR = """\
Timeout 60 Check
  (erefl : apr_assumptions pgl27_row_prior_exact = BaselineClassicalOnly).
"""

M_PIN = M_PIN_ANCHOR + """
Timeout 60 Check (psl211_row_word : AnalysisPathRow).
Timeout 60 Check (apr_model psl211_row_word
  : AnalysisModelFamily PSL211Analysis.observed).
Timeout 60 Check (erefl : apr_completion psl211_row_word = AnalysisBridged).
Timeout 60 Check (erefl : apr_transfer psl211_row_word = IdealFinite).
Timeout 60 Check
  (erefl : apr_assumptions psl211_row_word = BaselineClassicalOnly).
"""

M_FAM_ANCHOR = """\
Timeout 60 Check (fun R : realType =>
  amf_sample (apr_model psl211_row_alldecks) R tt).
"""

M_FAM = M_FAM_ANCHOR + """
Timeout 60 Check (fun R : realType =>
  amf_sample (apr_model psl211_row_word) R tt).
"""

M_BANNER_ANCHOR = \
    "(*     The deterministic checker: the ten typed rows                " \
    "          *)"
M_BANNER = \
    "(*     The deterministic checker: the eleven typed rows             " \
    "          *)"

MANIFEST = [
    (M_HEADER_ANCHOR, M_HEADER),
    (M_ROW9_ANCHOR, M_ROW9),
    (M_BLOCK_ANCHOR, M_BLOCK),
    (M_ROW_ANCHOR, M_ROW),
    (M_BANNER_ANCHOR, M_BANNER),
    (M_PIN_ANCHOR, M_PIN),
    (M_FAM_ANCHOR, M_FAM),
]

# --------------------------------------------------------------------------
# manifest/pgg_analysis_client.v
# --------------------------------------------------------------------------

C_HEADER_ANCHOR = \
    "(* One import reaches all four facades, the typed status vocabulary " \
    "and the   *)\n" \
    "(* ten typed rows. The file has EXACTLY ONE Require of any kind, and " \
    "         *)"
C_HEADER = \
    "(* One import reaches all four facades, the typed status vocabulary " \
    "and the   *)\n" \
    "(* eleven typed rows. The file has EXACTLY ONE Require of any kind, " \
    "and       *)"

C_CHECK_ANCHOR = \
    "Check PSL211Analysis.exact_family.              (* 4 Models, typed " \
    "family *)"
C_CHECK = C_CHECK_ANCHOR + "\n" + \
    "Check PSL211Analysis.word_family.               (* 4 Models, typed " \
    "family *)"

CLIENT = [
    (C_HEADER_ANCHOR, C_HEADER),
    (C_CHECK_ANCHOR, C_CHECK),
]

# --------------------------------------------------------------------------
# instances/psl211/psl211_analysis.v, based on production
# --------------------------------------------------------------------------

A_TABLE_ANCHOR = \
    "(*   exact-uniform sample model               -> exact_sample,   " \
    "             *)\n" \
    "(*                                               exact_family    " \
    "             *)"
A_TABLE = A_TABLE_ANCHOR + "\n" + \
    "(*   584-letter word sample model             -> word_sample, word_" \
    "family     *)"

A_IMPORT_ANCHOR = "From pgg_smc Require Import psl211_alldecks psl211_models."
A_IMPORT = \
    "From pgg_smc Require Import psl211_alldecks psl211_models " \
    "psl211_word_model."

A_SEC4_ANCHOR = """\
(* The model is followed by the equations that identify its cut and its       *)
(* coalition distributions, so that a security statement about a named        *)
(* distribution can be attached to a named executed observer.                 *)
"""

A_SEC4 = """\
(* The all-decks model is followed by the equations that identify its cut and *)
(* its coalition distributions, so that a security statement about a named    *)
(* distribution can be attached to a named executed observer. The word model  *)
(* carries its own cut equation psl211_word_cut_distE at                      *)
(* instances/psl211/psl211_word_model.v, and is aliased here for the sample   *)
(* and model slots of its own manifest row.                                   *)
"""

A_ALIAS_ANCHOR = """\
Definition exact_sample := @psl211_alldecks_sample.

(** exact_family — that model as a unit-indexed typed family, one member at
    every real field, the model having no parameter to range over. *)
Definition exact_family := psl211_exact_family.
"""

A_ALIAS = """\
Definition exact_sample := @psl211_alldecks_sample.

(** word_sample — the 584-letter word model as a sample adapter: the sample
    space and the law of the deck description of exact_sample, with the cut
    drawn by evaluating a word in the three generators. *)
Definition word_sample := @psl211_word_sample.

(** exact_family — that model as a unit-indexed typed family, one member at
    every real field, the model having no parameter to range over. *)
Definition exact_family := psl211_exact_family.

(** word_family — the word model as a unit-indexed typed family, carrying the
    index type exact_family carries, so a row over each of the two models is
    read at one index. *)
Definition word_family := psl211_word_family.
"""

ANALYSIS = [
    (A_TABLE_ANCHOR, A_TABLE),
    (A_IMPORT_ANCHOR, A_IMPORT),
    (A_SEC4_ANCHOR, A_SEC4),
    (A_ALIAS_ANCHOR, A_ALIAS),
]

# --------------------------------------------------------------------------
# instances/psl211/psl211_reading_constancy.v, based on production.
# Comment changes only: the code token stream is production's, which
# verify.py check (2) reports.
# --------------------------------------------------------------------------

CONSTANCY = [
    # the header names the third arm this instance now publishes at
    (banner([
     "PSL(2,11) in the two run modes the instance carries. The instance",
     "publishes its all-decks row through the exact arm, and this file is"
     " what",
     "the input-indistinguishability arm would cost it."]),
     banner([
     "PSL(2,11) in the two run modes the instance carries. The instance",
     "publishes its all-decks row through the exact arm and its word row"
     " through",
     "the proximity arm, in instances/psl211/psl211_word_proximity.v, and"
     " this",
     "file is what the input-indistinguishability arm would cost it."])),
    # the excluded range of epsilon is an exclusion at one arm
    (banner([
     "at epsilon zero, which is the epsilon profile_eps_psl211 of",
     "instances/psl211/psl211_profile.v gives this instance's single-card",
     "marginal bound."]),
     banner([
     "at epsilon zero, which is the epsilon profile_eps_psl211 of",
     "instances/psl211/psl211_profile.v gives this instance's single-card",
     "marginal bound. The exclusion covers the input-indistinguishability"
     " arm",
     "alone: a proximity certificate carries no shuffle bound and no"
     " constancy",
     "field, and the row of instances/psl211/psl211_word_proximity.v"
     " publishes",
     "2^-40 over the word model through the proximity arm."])),
    # the clause the word adapter makes false
    (banner([
     "each. Nothing here says the word row is excluded outright:",
     "psl211_alldecks_constancy_false_word584 reaches eps < 1/1320 -"
     " 2^-40, and",
     "no weighted-word sample adapter exists for this instance. How wide"
     " each",
     "failure is stays measured and not proved; the reading multiplicity"]),
     banner([
     "each. Nothing here says the word row is excluded outright:",
     "psl211_alldecks_constancy_false_word584 reaches eps < 1/1320 -"
     " 2^-40, and",
     "the row published over the weighted-word adapter psl211_word_sample"
     " in",
     "instances/psl211/psl211_word_proximity.v carries a proximity"
     " certificate,",
     "which has no constancy field to refute. How wide each",
     "failure is stays measured and not proved; the reading multiplicity"])),
    # the stated reason of psl211_alldecks_constancy_false_word584
    ("""    replacement, while the eps is a certificate's own distance field. It is
    stated on the cut law rather than on a certificate because no
    weighted-word SampleAdapter exists in this tree, so there is no adapter
    whose cut is this law and no ic_Hd through which a certificate's ideal
    could be held near it. *)""",
     """    replacement, while the eps is a certificate's own distance field. It is
    stated on the cut law rather than on a certificate because it quantifies
    over every law within eps of that cut: a certificate whose adapter draws
    this cut is reached at its own shuffle bound, through ic_close read with
    ic_Hd, and no adapter has to be named here. The weighted-word adapter
    psl211_word_sample of instances/psl211/psl211_word_model.v draws this cut,
    and the row published over it in
    instances/psl211/psl211_word_proximity.v carries a proximity certificate,
    which has no constancy field for this refutation to touch, so this
    refutation rules out no proximity row. *)"""),
    # the section banner the word adapter makes false
    ("(*     The word model, which this tree carries no sample adapter for"
     "          *)",
     "(*     The word model, whose sample adapter is psl211_word_sample"
     "             *)"),
]

JOBS = [("manifest/pgg_analysis_manifest.v", MANIFEST, BASE),
        ("manifest/pgg_analysis_client.v", CLIENT, BASE),
        ("instances/psl211/psl211_analysis.v", ANALYSIS, PROD),
        ("instances/psl211/psl211_reading_constancy.v", CONSTANCY, PROD)]


def apply(rel, ops, base, check):
    text = open(os.path.join(base, rel)).read()
    for i, (anchor, repl) in enumerate(ops, 1):
        n = text.count(anchor)
        if n != 1:
            print("%s op %d: anchor found %d time(s), expected 1" % (rel, i, n))
            return 1
        text = text.replace(anchor, repl)
    over = [(j, len(l)) for j, l in enumerate(text.encode().split(b"\n"), 1)
            if len(l) > 80]
    print("%-38s %d op(s) applied, %d line(s) over 80 bytes"
          % (rel, len(ops), len(over)))
    for j, n in over:
        print("    line %d: %d bytes" % (j, n))
    if not check:
        open(os.path.join(OUT, rel), "w").write(text)
    return 0


def main():
    check = "--check" in sys.argv[1:]
    rc = 0
    for rel, ops, base in JOBS:
        rc |= apply(rel, ops, base, check)
    return rc


if __name__ == "__main__":
    sys.exit(main())
