#!/usr/bin/env python3
"""Re-copy the sixteen chain files, rebase the four edited ones, recompile.

Landing 4 chains on landing 3, which chains on landings 1 and 2.  Sixteen
files of this tree are landing 3's staged text verbatim; four more are
GENERATED by rebase_shared.py, two of them from landing 3's staged text and
two from production.  A landing-4 compile is evidence only against the text
it loaded, so whenever a base moves this script copies the sixteen again,
reports whether each changed in code or only in comments, regenerates the
four, and recompiles the whole chain in the _CoqProject order.

Usage:  python3 restage.py            copy, rebase, report, recompile
        python3 restage.py --check    copy nothing; only report what differs
"""

import os
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(os.path.dirname(os.path.dirname(HERE)))
L3 = os.path.join(os.path.dirname(HERE),
                  "2026-09-20-tableau-extensions-landing3", "staged")
L4 = os.path.join(HERE, "staged")

# landing 3's nineteen staged files minus the two landing 4 rebases onto,
# which rebase_shared.py generates instead.
CHAIN = [
    "lib/var_dist_supp.v",
    "security/var_dist_joint_law.v",
    "instances/pgl27/pgl27_exec.v",
    "instances/pgl27/pgl27_models.v",
    "instances/pgl27/pgl27_analysis.v",
    "instances/kim2025/five_card_mixing.v",
    "instances/kim2025/five_card_analysis.v",
    "manifest/pgg_tableau.v",
    "manifest/pgg_tableau_syntax.v",
    "manifest/pgg_tableau_arm_relations.v",
    "instances/pgl27/pgl27_rows.v",
    "instances/kim2025/five_card_rows.v",
    "instances/s5/s5_rows.v",
    "instances/psl211/psl211_rows.v",
    "instances/kim2025/five_card_proximity.v",
    "instances/pgl27/pgl27_proximity.v",
]

sys.path.insert(0, HERE)
from verify import split_comments, tokens  # noqa: E402


def main():
    check = "--check" in sys.argv[1:]
    moved = []
    for rel in CHAIN:
        a = open(os.path.join(L3, rel)).read()
        b = open(os.path.join(L4, rel)).read()
        if a == b:
            print("%-48s unchanged" % rel)
            continue
        code = "CODE CHANGED" if tokens(split_comments(a)[0]) != \
            tokens(split_comments(b)[0]) else "comments only"
        print("%-48s %s" % (rel, code))
        moved.append(rel)
        if not check:
            open(os.path.join(L4, rel), "w").write(a)

    print("\nregenerating the four edited files")
    rc = subprocess.run([sys.executable,
                         os.path.join(HERE, "rebase_shared.py")]
                        + (["--check"] if check else []), cwd=HERE).returncode
    if rc:
        print("rebase failed; nothing recompiled.")
        return rc
    if check:
        print("\n%d chain file(s) differ; nothing recompiled." % len(moved))
        return 0
    print("\ncopied %d chain file(s); recompiling." % len(moved))
    return subprocess.run([sys.executable,
                           os.path.join(HERE, "compile.py")],
                          cwd=HERE).returncode


if __name__ == "__main__":
    sys.exit(main())
