(* Generated by gen_fidelity.py.  Do not edit by hand. *)
From HB Require Import structures.
From mathcomp Require Import ssreflect ssrbool ssrfun eqtype ssrnat seq.
From mathcomp Require Import div fintype tuple finfun finset fingroup perm.
From mathcomp Require Import morphism action bigop order ssrnum ssralg.
From mathcomp Require Import boolp reals lra.
From infotheo Require Import realType_ext fdist proba variation_dist.
From pgg_smc Require Import var_dist_supp var_dist_joint_law.
From pgg_smc Require Import smc_interpreter pgg_interface pgg_monodromy_profile.
From pgg_smc Require Import pgg_execution_plug pgg_observed_execution.
From pgg_smc Require Import pgg_sample_adapter pgg_weighted_words.
From pgg_reconstruct Require Import pgg_sharing_framework covering_scheme.
From pgg_smc Require Import pgg_instance.
From pgg_smc Require Import pgg_analysis_status pgg_analysis_manifest.
From pgg_smc Require Import pgg_tableau pgg_tableau_syntax.
From pgg_smc Require Import psl211_group psl211_orbit psl211_closure.
From pgg_smc Require Import psl211_scheme psl211_profile psl211_mixing.
From pgg_smc Require Import psl211_exec psl211_alldecks psl211_models.
From pgg_smc Require Import psl211_word_model.
From pgg_smc Require Import psl211_rows psl211_word_proximity.

Set Implicit Arguments.
Unset Strict Implicit.
Import Prenex Implicits.
Import GRing.Theory Num.Theory.

Local Open Scope fdist_scope.
Local Open Scope proba_scope.
Local Open Scope entropy_scope.
Local Open Scope ring_scope.

Local Notation seatT :=
  ('I_(pi_T' (mp_PI (instance_profile psl211_algebra))).+1).

Local Notation cardT :=
  ('I_(pgg_N' (mp_M (instance_profile psl211_algebra))).+1).

(* The ten declarations of instances/psl211/psl211_rows.v.                   *)

Check (psl211_alldecks_prefix : Tableau Observed).

Check (psl211_exact_witness :
  forall (R : realType) (idx : unit),
  ExactWitness (amf_sample psl211_exact_family R idx)).

Check (psl211_row_alldecks_tableau : PublishedRow).

Check (psl211_row_alldecks_rowE :
  published_row psl211_row_alldecks_tableau = psl211_row_alldecks).

Check (psl211_row_alldecks_armE :
  forall (R : realType)
    (idx : amf_index (ab_f (published_at psl211_row_alldecks_tableau)) R),
  security_arm_of psl211_row_alldecks_tableau R idx = ExactIndependenceArm).

Check (psl211_alldecks_view_secrecy :
  forall (R : realType) (C : {set seatT}) (HC : (#|C| < 6)%N),
  [/\ psl211_alldecksP R
      |= (@sa_coalition_view R (instance_profile psl211_algebra)
            (instance_exec psl211_alldecks_params)
            (psl211_alldecks_sample R) 0 C) _|_ (psl211_alldecks_secret R),
      `I( psl211_alldecks_secret R ;
          @sa_coalition_view R (instance_profile psl211_algebra)
            (instance_exec psl211_alldecks_params)
            (psl211_alldecks_sample R) 0 C ) = 0,
      `H( psl211_alldecks_secret R |
          @sa_coalition_view R (instance_profile psl211_algebra)
            (instance_exec psl211_alldecks_params)
            (psl211_alldecks_sample R) 0 C )
      = `H `p_ (psl211_alldecks_secret R)
    & forall (W : finType) (h : {ffun seatT -> cardT} -> W),
        psl211_alldecksP R
        |= (h `o (@sa_coalition_view R (instance_profile psl211_algebra)
                    (instance_exec psl211_alldecks_params)
                    (psl211_alldecks_sample R) 0 C))
           _|_ (psl211_alldecks_secret R)]).

Check (psl211_alldecks_prefix_vm : Tableau Observed).

Check (psl211_alldecks_prefix_vm_paramsE :
  projT1 (projT2 (tableau_at psl211_alldecks_prefix_vm))
  = psl211_alldecks_params).

Check (psl211_alldecks_prefix_lit : Tableau Observed).

Check (psl211_alldecks_prefix_lit_paramsE :
  projT1 (projT2 (tableau_at psl211_alldecks_prefix_lit))
  = psl211_alldecks_params).

(* The fourteen declarations of                                              *)
(* instances/psl211/psl211_word_proximity.v.                                 *)

Check (psl211_word_proximity_close :
  forall (R : realType) (C : {set seatT}),
  (#|C| < profile_k (instance_profile psl211_algebra))%N ->
  var_dist
    (fdistmap (fun u => (@static_coalition_obs psl211_algebra
                           psl211_alldecks_params C
                           ((psl211_word_sample R).(sa_arg) u)
                           ((psl211_word_sample R).(sa_cut) u),
                         psl211_alldecks_secret R u))
       (sa_sampleP (psl211_word_sample R)))
    (fdistmap (fun u => (@static_coalition_obs psl211_algebra
                           psl211_alldecks_params C
                           ((psl211_alldecks_sample R).(sa_arg) u)
                           ((psl211_alldecks_sample R).(sa_cut) u),
                         psl211_alldecks_secret R u))
       (sa_sampleP (psl211_alldecks_sample R)))
  <= 2%:R^-40).

Check (psl211_word_proximity_cert :
  forall (R : realType) (idx : unit),
  IdealProximityCert (amf_sample psl211_word_family R idx)).

Check (psl211_word_proximity_cert_idealE :
  forall (R : realType) (idx : unit),
  ipc_ideal (psl211_word_proximity_cert R idx)
  = amf_sample (ab_f (published_at psl211_row_alldecks_tableau)) R idx
  /\ ExactIndependence (ipc_witness (psl211_word_proximity_cert R idx))
     = ab_port (published_at psl211_row_alldecks_tableau) R idx).

Check (psl211_word_proximity_cert_secretE :
  forall (R : realType) (idx : unit),
  ipc_secret (psl211_word_proximity_cert R idx) = psl211_alldecks_secret R
  /\ ew_secret (ipc_witness (psl211_word_proximity_cert R idx))
     = psl211_alldecks_secret R).

Check (psl211_word_proximity_cert_secretTE :
  forall (R : realType) (idx : unit),
  ew_secretT (ipc_witness (psl211_word_proximity_cert R idx)) = bool).

Check (psl211_word_proximity_cert_epsE :
  forall (R : realType) (idx : unit),
  ipc_eps (psl211_word_proximity_cert R idx) = 2%:R^-40 :> R).

Check (psl211_pow2_40_ge1 : forall R : realType, (1:R) <= 2%:R^+40).

Check (psl211_pow2_40_gt0 : forall R : realType, (0:R) < 2%:R^+40).

Check (psl211_word_law_le2 :
  forall R : realType,
  var_dist (psl211_wordP R) (psl211_alldecksP R) <= 2%:R).

Check (psl211_word_proximity_cert_eps_lt2 :
  forall (R : realType) (idx : unit),
  ipc_eps (psl211_word_proximity_cert R idx) < 2%:R :> R).

Check (psl211_row_word_proximity : PublishedRow).

Check (psl211_row_word_proximity_armE :
  forall (R : realType)
    (idx : amf_index (ab_f (published_at psl211_row_word_proximity)) R),
  security_arm_of psl211_row_word_proximity R idx = IdealProximityArm).

Check (psl211_row_word_proximity_rowE :
  published_row psl211_row_word_proximity = psl211_row_word).

Check (psl211_word_view_proximity :
  forall (R : realType) (C : {set seatT}) (HC : (#|C| <= 5)%N),
  var_dist
    (fdistmap (fun u => (@sa_coalition_view R (instance_profile psl211_algebra)
                           (instance_exec psl211_alldecks_params)
                           (amf_sample psl211_word_family R tt) 0 C u,
                         psl211_alldecks_secret R u))
       (sa_sampleP (amf_sample psl211_word_family R tt)))
    ((fdistmap (@sa_coalition_view R (instance_profile psl211_algebra)
                  (instance_exec psl211_alldecks_params)
                  (psl211_alldecks_sample R) 0 C) (psl211_alldecksP R))
     `x (fdistmap (psl211_alldecks_secret R) (psl211_alldecksP R)))
  <= 2%:R^-40).

Print Assumptions psl211_row_alldecks_tableau.
Print Assumptions psl211_row_alldecks_rowE.
Print Assumptions psl211_row_alldecks_armE.
Print Assumptions psl211_alldecks_view_secrecy.
Print Assumptions psl211_alldecks_prefix_vm_paramsE.
Print Assumptions psl211_alldecks_prefix_lit_paramsE.
Print Assumptions psl211_word_proximity_close.
Print Assumptions psl211_word_proximity_cert_idealE.
Print Assumptions psl211_word_proximity_cert_secretE.
Print Assumptions psl211_word_proximity_cert_secretTE.
Print Assumptions psl211_word_proximity_cert_epsE.
Print Assumptions psl211_pow2_40_ge1.
Print Assumptions psl211_pow2_40_gt0.
Print Assumptions psl211_word_law_le2.
Print Assumptions psl211_word_proximity_cert_eps_lt2.
Print Assumptions psl211_row_word_proximity.
Print Assumptions psl211_row_word_proximity_armE.
Print Assumptions psl211_row_word_proximity_rowE.
Print Assumptions psl211_word_view_proximity.
