#!/usr/bin/env python3
"""Generate fidelity.v (against the staged text) and baseline.v (against
production) from one shared body.

Both files ascribe every name instances/psl211/psl211_rows.v and
instances/psl211/psl211_word_proximity.v declare, at the statement it has in
production, so a lost or altered declaration is a compile error, and both
print the assumptions of every published row and every lemma, so the two
outputs can be diffed.  Only the Require line differs.

The scope block below is production psl211_rows.v's: fdist, proba, entropy,
ring.  Production psl211_word_proximity.v's is ring, fdist, proba, so the
twelve declarations that move out of it are ascribed here under a different
innermost scope than they were written in.  That is deliberate: it is the
check that the re-scoping changes no statement.  A numeral or a notation
that resolved differently would make the baseline Check a type error.
"""

import os

HERE = os.path.dirname(os.path.abspath(__file__))

PRELUDE = r"""(* Generated by gen_fidelity.py.  Do not edit by hand. *)
From HB Require Import structures.
From mathcomp Require Import ssreflect ssrbool ssrfun eqtype ssrnat seq.
From mathcomp Require Import div fintype tuple finfun finset fingroup perm.
From mathcomp Require Import morphism action bigop order ssrnum ssralg.
From mathcomp Require Import boolp reals lra.
From infotheo Require Import realType_ext fdist proba variation_dist.
From pgg_smc Require Import var_dist_supp var_dist_joint_law.
From pgg_smc Require Import smc_interpreter pgg_interface pgg_monodromy_profile.
From pgg_smc Require Import pgg_execution_plug pgg_observed_execution.
From pgg_smc Require Import pgg_sample_adapter pgg_weighted_words.
From pgg_reconstruct Require Import pgg_sharing_framework covering_scheme.
From pgg_smc Require Import pgg_instance.
From pgg_smc Require Import pgg_analysis_status pgg_analysis_manifest.
From pgg_smc Require Import pgg_tableau pgg_tableau_syntax.
From pgg_smc Require Import psl211_group psl211_orbit psl211_closure.
From pgg_smc Require Import psl211_scheme psl211_profile psl211_mixing.
From pgg_smc Require Import psl211_exec psl211_alldecks psl211_models.
From pgg_smc Require Import psl211_word_model.
"""

SETTINGS = r"""
Set Implicit Arguments.
Unset Strict Implicit.
Import Prenex Implicits.
Import GRing.Theory Num.Theory.

Local Open Scope fdist_scope.
Local Open Scope proba_scope.
Local Open Scope entropy_scope.
Local Open Scope ring_scope.

Local Notation seatT :=
  ('I_(pi_T' (mp_PI (instance_profile psl211_algebra))).+1).

Local Notation cardT :=
  ('I_(pgg_N' (mp_M (instance_profile psl211_algebra))).+1).
"""

# Every name the two source files declare, ascribed at its production
# statement.  Ten from psl211_rows.v, fourteen from psl211_word_proximity.v.
ASCRIPTIONS = r"""
(* The ten declarations of instances/psl211/psl211_rows.v.                   *)

Check (psl211_alldecks_prefix : Tableau Observed).

Check (psl211_exact_witness :
  forall (R : realType) (idx : unit),
  ExactWitness (amf_sample psl211_exact_family R idx)).

Check (psl211_row_alldecks_tableau : PublishedRow).

Check (psl211_row_alldecks_rowE :
  published_row psl211_row_alldecks_tableau = psl211_row_alldecks).

Check (psl211_row_alldecks_armE :
  forall (R : realType)
    (idx : amf_index (ab_f (published_at psl211_row_alldecks_tableau)) R),
  security_arm_of psl211_row_alldecks_tableau R idx = ExactIndependenceArm).

Check (psl211_alldecks_view_secrecy :
  forall (R : realType) (C : {set seatT}) (HC : (#|C| < 6)%N),
  [/\ psl211_alldecksP R
      |= (@sa_coalition_view R (instance_profile psl211_algebra)
            (instance_exec psl211_alldecks_params)
            (psl211_alldecks_sample R) 0 C) _|_ (psl211_alldecks_secret R),
      `I( psl211_alldecks_secret R ;
          @sa_coalition_view R (instance_profile psl211_algebra)
            (instance_exec psl211_alldecks_params)
            (psl211_alldecks_sample R) 0 C ) = 0,
      `H( psl211_alldecks_secret R |
          @sa_coalition_view R (instance_profile psl211_algebra)
            (instance_exec psl211_alldecks_params)
            (psl211_alldecks_sample R) 0 C )
      = `H `p_ (psl211_alldecks_secret R)
    & forall (W : finType) (h : {ffun seatT -> cardT} -> W),
        psl211_alldecksP R
        |= (h `o (@sa_coalition_view R (instance_profile psl211_algebra)
                    (instance_exec psl211_alldecks_params)
                    (psl211_alldecks_sample R) 0 C))
           _|_ (psl211_alldecks_secret R)]).

Check (psl211_alldecks_prefix_vm : Tableau Observed).

Check (psl211_alldecks_prefix_vm_paramsE :
  projT1 (projT2 (tableau_at psl211_alldecks_prefix_vm))
  = psl211_alldecks_params).

Check (psl211_alldecks_prefix_lit : Tableau Observed).

Check (psl211_alldecks_prefix_lit_paramsE :
  projT1 (projT2 (tableau_at psl211_alldecks_prefix_lit))
  = psl211_alldecks_params).

(* The fourteen declarations of                                              *)
(* instances/psl211/psl211_word_proximity.v.                                 *)

Check (psl211_word_proximity_close :
  forall (R : realType) (C : {set seatT}),
  (#|C| < profile_k (instance_profile psl211_algebra))%N ->
  var_dist
    (fdistmap (fun u => (@static_coalition_obs psl211_algebra
                           psl211_alldecks_params C
                           ((psl211_word_sample R).(sa_arg) u)
                           ((psl211_word_sample R).(sa_cut) u),
                         psl211_alldecks_secret R u))
       (sa_sampleP (psl211_word_sample R)))
    (fdistmap (fun u => (@static_coalition_obs psl211_algebra
                           psl211_alldecks_params C
                           ((psl211_alldecks_sample R).(sa_arg) u)
                           ((psl211_alldecks_sample R).(sa_cut) u),
                         psl211_alldecks_secret R u))
       (sa_sampleP (psl211_alldecks_sample R)))
  <= 2%:R^-40).

Check (psl211_word_proximity_cert :
  forall (R : realType) (idx : unit),
  IdealProximityCert (amf_sample psl211_word_family R idx)).

Check (psl211_word_proximity_cert_idealE :
  forall (R : realType) (idx : unit),
  ipc_ideal (psl211_word_proximity_cert R idx)
  = amf_sample (ab_f (published_at psl211_row_alldecks_tableau)) R idx
  /\ ExactIndependence (ipc_witness (psl211_word_proximity_cert R idx))
     = ab_port (published_at psl211_row_alldecks_tableau) R idx).

Check (psl211_word_proximity_cert_secretE :
  forall (R : realType) (idx : unit),
  ipc_secret (psl211_word_proximity_cert R idx) = psl211_alldecks_secret R
  /\ ew_secret (ipc_witness (psl211_word_proximity_cert R idx))
     = psl211_alldecks_secret R).

Check (psl211_word_proximity_cert_secretTE :
  forall (R : realType) (idx : unit),
  ew_secretT (ipc_witness (psl211_word_proximity_cert R idx)) = bool).

Check (psl211_word_proximity_cert_epsE :
  forall (R : realType) (idx : unit),
  ipc_eps (psl211_word_proximity_cert R idx) = 2%:R^-40 :> R).

Check (psl211_pow2_40_ge1 : forall R : realType, (1:R) <= 2%:R^+40).

Check (psl211_pow2_40_gt0 : forall R : realType, (0:R) < 2%:R^+40).

Check (psl211_word_law_le2 :
  forall R : realType,
  var_dist (psl211_wordP R) (psl211_alldecksP R) <= 2%:R).

Check (psl211_word_proximity_cert_eps_lt2 :
  forall (R : realType) (idx : unit),
  ipc_eps (psl211_word_proximity_cert R idx) < 2%:R :> R).

Check (psl211_row_word_proximity : PublishedRow).

Check (psl211_row_word_proximity_armE :
  forall (R : realType)
    (idx : amf_index (ab_f (published_at psl211_row_word_proximity)) R),
  security_arm_of psl211_row_word_proximity R idx = IdealProximityArm).

Check (psl211_row_word_proximity_rowE :
  published_row psl211_row_word_proximity = psl211_row_word).

Check (psl211_word_view_proximity :
  forall (R : realType) (C : {set seatT}) (HC : (#|C| <= 5)%N),
  var_dist
    (fdistmap (fun u => (@sa_coalition_view R (instance_profile psl211_algebra)
                           (instance_exec psl211_alldecks_params)
                           (amf_sample psl211_word_family R tt) 0 C u,
                         psl211_alldecks_secret R u))
       (sa_sampleP (amf_sample psl211_word_family R tt)))
    ((fdistmap (@sa_coalition_view R (instance_profile psl211_algebra)
                  (instance_exec psl211_alldecks_params)
                  (psl211_alldecks_sample R) 0 C) (psl211_alldecksP R))
     `x (fdistmap (psl211_alldecks_secret R) (psl211_alldecksP R)))
  <= 2%:R^-40).
"""

# The two published rows, and every lemma, fact and theorem of the two source
# files.  The four Definitions that are payloads or prefixes are left out:
# a Print Assumptions on a type naming psl211_alldecks_observed costs about
# twenty seconds, and each of them is reached through a row below.
ASSUMPTIONS = r"""
Print Assumptions psl211_row_alldecks_tableau.
Print Assumptions psl211_row_alldecks_rowE.
Print Assumptions psl211_row_alldecks_armE.
Print Assumptions psl211_alldecks_view_secrecy.
Print Assumptions psl211_alldecks_prefix_vm_paramsE.
Print Assumptions psl211_alldecks_prefix_lit_paramsE.
Print Assumptions psl211_word_proximity_close.
Print Assumptions psl211_word_proximity_cert_idealE.
Print Assumptions psl211_word_proximity_cert_secretE.
Print Assumptions psl211_word_proximity_cert_secretTE.
Print Assumptions psl211_word_proximity_cert_epsE.
Print Assumptions psl211_pow2_40_ge1.
Print Assumptions psl211_pow2_40_gt0.
Print Assumptions psl211_word_law_le2.
Print Assumptions psl211_word_proximity_cert_eps_lt2.
Print Assumptions psl211_row_word_proximity.
Print Assumptions psl211_row_word_proximity_armE.
Print Assumptions psl211_row_word_proximity_rowE.
Print Assumptions psl211_word_view_proximity.
"""

# Only the staged tree has these.  The four new Definitions are ascribed at
# their type, which a wrong body would still satisfy; what pins their bodies
# is the four equations below, each of which holds by conversion.  All five
# new definitions have their assumptions printed, not only the ones an
# equation pins: a type ascription alone would pass on a wrong body, and
# audit F12 asked for the record and not only for the fact.
NEW = r"""
Check (psl211_algebraic_start : Tableau Algebraic).
Check (psl211_alldecks_executable : Tableau Executable).
Check (psl211_exact_sampled : Tableau Sampled).
Check (psl211_word_sampled : Tableau Sampled).

Check (psl211_alldecks_executable_paramsE :
  projT2 (tableau_at psl211_alldecks_executable) = psl211_alldecks_params).

Check (psl211_alldecks_executableE :
  (psl211_alldecks_executable
     execute terminates by psl211_alldecks_terminates
             endpoints by psl211_alldecks_endpoints
             recon by psl211_alldecks_recon) = psl211_alldecks_prefix).

Check (psl211_row_alldecks_sampledE :
  (psl211_exact_sampled
     certify ExactIndependence psl211_exact_witness
     |> publish StaticExecutedOnly BaselineClassicalOnly)
  = psl211_row_alldecks_tableau).

Check (psl211_row_word_proximity_sampledE :
  (psl211_word_sampled
     certify IdealProximity psl211_word_proximity_cert
     |> publish IdealFinite BaselineClassicalOnly)
  = psl211_row_word_proximity).

Print Assumptions psl211_algebraic_start.
Print Assumptions psl211_alldecks_executable.
Print Assumptions psl211_exact_sampled.
Print Assumptions psl211_word_sampled.
Print Assumptions psl211_alldecks_executable_paramsE.
Print Assumptions psl211_alldecks_executableE.
Print Assumptions psl211_row_alldecks_sampledE.
Print Assumptions psl211_row_word_proximity_sampledE.
"""


def write(name, require, extra):
    body = PRELUDE + require + SETTINGS + ASCRIPTIONS + ASSUMPTIONS + extra
    with open(os.path.join(HERE, name), "w") as f:
        f.write(body)
    print("wrote", name)


write("fidelity.v",
      "From pgg_smc Require Import psl211_word_proximity.\n"
      "From pgg_smc Require Import psl211_tableau_algebraic.\n"
      "From pgg_smc Require Import psl211_tableau_executable.\n"
      "From pgg_smc Require Import psl211_tableau_observed.\n"
      "From pgg_smc Require Import psl211_tableau_sampled.\n"
      "From pgg_smc Require Import psl211_tableau_analysis_bridged.\n"
      "From pgg_smc Require Import psl211_tableau_checks.\n",
      NEW)

write("baseline.v",
      "From pgg_smc Require Import psl211_rows psl211_word_proximity.\n",
      "")
