(* infotheo: information theory and error-correcting codes in Rocq            *)
(* Copyright (C) 2025 infotheo authors, license: LGPL-2.1-or-later            *)
From mathcomp Require Import ssreflect ssrbool ssrfun eqtype ssrnat seq.
From mathcomp Require Import fintype bigop div.
From mathcomp Require Import zify.

(******************************************************************************)
(* Free Group Ball-Size Formula (Combinatorial)                               *)
(* Group presentation: <a_1,...,a_r | > (free group, no relations)            *)
(*                                                                            *)
(* Pure nat arithmetic over an alphabet of 2r letters, the r generators and   *)
(* their r formal inverses.  The sphere count is fixed by the closed form     *)
(* 2r*(2r-1)^(k-1), the ball count as the sum of spheres, and the file        *)
(* proves the geometric identities those two satisfy: a multiplicative        *)
(* closed form, its division form, and the exponential lower bound            *)
(* (2r-1)^L <= ball_size r L.                                                 *)
(*                                                                            *)
(* No free group type is constructed, and no lemma here connects sphere_size  *)
(* or ball_size to the predicate reduced.  That a reduced word of length k    *)
(* extends in exactly 2r-1 ways, and that distinct reduced words name         *)
(* distinct free-group elements, are standard facts taken as the reading of   *)
(* these counts rather than discharged in the kernel; reduced is carried so   *)
(* the intended objects are written down, not because a proof consumes it.    *)
(*                                                                            *)
(* That reading is what makes the numbers a PGG search-space bound.  Any      *)
(* group generated by r elements and their inverses is a quotient of the      *)
(* free one, so no deck group on r generators reaches more permutations in    *)
(* words of length at most L than the free ball counts, and the exponential   *)
(* lower bound says how fast that ceiling itself grows.                       *)
(*                                                                            *)
(* Section 1 — Alphabet, reduction predicate, sphere counts:                  *)
(*   letter_inv r i == inverse of letter i in alphabet {0,...,2r-1}           *)
(*   reduced r w    == no adjacent pair (a, inv(a)) in word w                 *)
(*   sphere_size r k == 1 for k = 0, and 2r*(2r-1)^(k-1) for k > 0            *)
(*                                                                            *)
(* Section 2 — Ball size as sum of spheres:                                   *)
(*   ball_size r L == sum of sphere_size r k over k <= L                      *)
(*                                                                            *)
(* Section 3 — Geometric series over nat:                                     *)
(*   geom_series_nat == (q-1) * sum_{k=0}^{L} q^k = q^{L+1} - 1             *)
(*                                                                            *)
(* Section 4 — Closed-form ball-size formula (multiplicative, no division):   *)
(*   ball_size_formula ==                                                     *)
(*     (2r-2) * (ball_size r L - 1) = 2r * ((2r-1)^L - 1)                    *)
(*   ball_size_lower == ball_size r L >= (2r-1)^L                             *)
(******************************************************************************)

Set Implicit Arguments.
Unset Strict Implicit.
Import Prenex Implicits.

(* ========================================================================== *)
(* Section 1: Reduced words and sphere counting                               *)
(* ========================================================================== *)

Section reduced_words.

Variable r : nat.
Hypothesis Hr : 0 < r.

(* alpha = 2r is the size of the alphabet: the r generators and their r
   formal inverses. *)
Let alpha := (r.*2).
(* The alphabet is {0,...,2r-1}, the r generators followed by their r formal
   inverses, so the inverse of letter i is i + r taken mod 2r. *)

Definition letter_inv (i : nat) : nat := (i + r) %% alpha.

(** The inverse of a letter is again a letter of the 2r-symbol alphabet.
    Well-definedness of the involution against which the reduction predicate
    is stated. *)
Lemma letter_inv_lt (i : nat) : i < alpha -> letter_inv i < alpha.
Proof. by move=> _; rewrite /letter_inv ltn_mod double_gt0. Qed.

(** Letter inversion is an involution on the alphabet.
    This is the free-group relation a a^-1 = 1 written at the level of
    symbols, and it is what makes forbidding an adjacent inverse pair the
    right notion of an irredundant word. *)
Lemma letter_invK (i : nat) : i < alpha -> letter_inv (letter_inv i) = i.
Proof.
move=> Hi; rewrite /letter_inv.
have Halpha : 0 < alpha by rewrite double_gt0.
rewrite modnDml -addnA.
have -> : r + r = 1 * alpha by rewrite mul1n /alpha addnn.
rewrite addnC modnMDl.
exact: modn_small.
Qed.

(** No letter is its own inverse.
    The alphabet carries no involutive generator, so a reduced word of
    positive length forbids exactly one of its 2r continuations.  That is
    the branching factor 2r-1 the sphere count is built on. *)
Lemma letter_inv_neq (i : nat) : i < alpha -> letter_inv i != i.
Proof.
move=> Hi; rewrite /letter_inv.
have Halpha : 0 < alpha by rewrite double_gt0.
apply/negP => /eqP Heq.
have Hdvd : alpha %| r.
  apply/dvdnP.
  exists ((i + r) %/ alpha).
  have := divn_eq (i + r) alpha.
  rewrite Heq => Heq2.
  by lia.
move/dvdn_leq: Hdvd => /(_ Hr).
by rewrite /alpha; lia.
Qed.

(* A word is reduced when no letter is immediately followed by its inverse.
   This names the objects sphere_size and ball_size are read as counting.
   No lemma below relates reduced to either count: that reduced words biject
   with free-group elements is the reading of the numbers, not a theorem of
   this file. *)
Fixpoint reduced (w : seq nat) : bool :=
  match w with
  | [::] | [:: _] => true
  | a :: ((b :: _) as w') => (letter_inv a != b) && reduced w'
  end.

(* Number of reduced words of length exactly k over the 2r letters: one
   empty word, and 2r*(2r-1)^(k-1) otherwise, the first letter free and every
   later letter avoiding only the inverse of its predecessor.  Given as a
   closed form; nothing below derives it from reduced. *)

Definition sphere_size (k : nat) : nat :=
  match k with
  | 0 => 1
  | k'.+1 => alpha * (alpha - 1) ^ k'
  end.


(** The radius-0 sphere holds the empty word alone. *)
Lemma sphere_size_0 : sphere_size 0 = 1.
Proof. by []. Qed.

(** The radius-1 sphere has alpha = 2r elements.
    A single letter is unconstrained, so the branching factor 2r-1 first
    applies at the second letter, not the first. *)
Lemma sphere_size_1 : sphere_size 1 = alpha.
Proof. by rewrite /= muln1. Qed.

(** Beyond length 1 each further letter multiplies the sphere count by
    alpha - 1.
    The geometric growth that both the closed form and the exponential lower
    bound rest on: exactly one continuation, the inverse of the last letter,
    is excluded. *)
Lemma sphere_size_S (k : nat) :
  0 < k -> sphere_size k.+1 = sphere_size k * (alpha - 1).
Proof.
case: k => [//|k _].
by rewrite /= expnSr mulnA.
Qed.

End reduced_words.

(* ========================================================================== *)
(* Section 2: Ball size = sum of spheres                                      *)
(* ========================================================================== *)

Section ball_size_def.

Variable r : nat.
Hypothesis Hr : 0 < r.

(** Number of reduced words of length at most L in the free group on r
    generators, the sum of the spheres of radius 0 through L.
    This is the ceiling the search-space reading uses: any group on r
    generators is a quotient of the free one, so words of length at most L
    reach at most this many elements. *)
Definition ball_size (L : nat) : nat :=
  \sum_(k < L.+1) sphere_size r k.

(** The radius-0 ball holds the empty word alone. *)
Lemma ball_size_0 : ball_size 0 = 1.
Proof. by rewrite /ball_size big_ord_recl big_ord0. Qed.

(** The radius-(L+1) ball is the radius-L ball together with the outermost
    sphere. *)
Lemma ball_size_S (L : nat) :
  ball_size L.+1 = ball_size L + sphere_size r L.+1.
Proof. by rewrite /ball_size big_ord_recr. Qed.

(** Every ball is non-empty, the empty word lying in all of them. *)
Lemma ball_size_ge1 (L : nat) : 0 < ball_size L.
Proof. by rewrite /ball_size big_ord_recl /=; lia. Qed.

End ball_size_def.

(* ========================================================================== *)
(* Section 3: Geometric series over nat                                       *)
(* ========================================================================== *)

Section geometric_series.

(* Geometric series over nat, stated multiplicatively so that neither nat
   subtraction nor nat division appears on the left:
   (q-1) * sum_{k=0}^{L} q^k = q^{L+1} - 1 for q >= 1.
   This is what converts the sum of spheres into a closed form. *)
Lemma geom_series_nat (q L : nat) :
  1 <= q ->
  q.-1 * (\sum_(k < L.+1) q ^ k) = q ^ L.+1 - 1.
Proof.
move=> Hq.
elim: L => [|L IH].
  by rewrite big_ord_recl big_ord0 expn0 addn0 muln1 expn1; lia.
rewrite big_ord_recr /= mulnDr IH.
have Hpow : 0 < q ^ L.+1 by rewrite expn_gt0; lia.
have Hpow2 : q ^ L.+1 <= q ^ L.+2.
  by rewrite leq_pexp2l //; lia.
have HqL : q.-1 * q ^ L.+1 + q ^ L.+1 = q ^ L.+2.
  by rewrite addnC -mulSn prednK // expnS.
lia.
Qed.

(* Division form of the same series: sum_{k=0}^{L} q^k = (q^{L+1}-1)/(q-1)
   for q >= 2, the hypothesis under which the nat division is exact. *)
Lemma geom_series_div (q L : nat) :
  2 <= q ->
  \sum_(k < L.+1) q ^ k = (q ^ L.+1 - 1) %/ q.-1.
Proof.
move=> Hq.
have Hq1 : 0 < q.-1 by lia.
have Hq1' : 1 <= q by lia.
rewrite -geom_series_nat // mulKn //.
Qed.

End geometric_series.

(* ========================================================================== *)
(* Section 4: Ball-size closed form                                           *)
(* ========================================================================== *)

Section ball_size_formula.

(* From here r >= 2, so the branching factor q = 2r-1 exceeds 1 and the ball
   grows exponentially.  At r = 1 the free group is infinite cyclic, q = 1,
   and every statement of this section degenerates. *)
Variable r : nat.
Hypothesis Hr : 1 < r.

Let alpha := (r.*2).
Let q := alpha - 1.

(** With at least two generators the alphabet has more than two letters. *)
Lemma alpha_gt1 : 1 < alpha.
Proof. by rewrite /alpha; lia. Qed.

(** The branching factor q = alpha - 1 is positive when r >= 2.
    A free group on one generator has q = 1 and a ball that grows linearly;
    the statements of this section assume that case away. *)
Lemma q_gt0 : 0 < q.
Proof. by rewrite /q /alpha; lia. Qed.

(* The ball split at its first letter: the empty word, plus alpha choices of
   first letter times the geometric sum of the branching that follows. *)
Lemma ball_size_sum (L : nat) :
  ball_size r L = 1 + alpha * \sum_(k < L) q ^ k.
Proof.
rewrite /ball_size big_ord_recl /=; congr (_ + _).
by rewrite -big_distrr.
Qed.

(* Closed form for the ball, stated multiplicatively to avoid nat division:
   (q-1) * (ball_size r L - 1) = alpha * (q^L - 1), i.e.
   (2r-2)*(ball_size r L - 1) = 2r*((2r-1)^L - 1). *)
Lemma ball_size_formula (L : nat) :
  0 < L ->
  q.-1 * (ball_size r L - 1) = alpha * (q ^ L - 1).
Proof.
move=> HL.
case: L HL => [//|L _].
rewrite ball_size_sum addKn mulnCA; congr (alpha * _).
have Hq1 : 1 <= q by rewrite /q /alpha; lia.
by rewrite geom_series_nat.
Qed.

(* The same closed form solved for ball_size:
   ball_size r L = 1 + 2r * ((2r-1)^L - 1) / (2r - 2). *)
Lemma ball_size_div (L : nat) :
  0 < L ->
  ball_size r L = 1 + alpha * ((q ^ L - 1) %/ q.-1).
Proof.
case: L => [//|L _].
rewrite ball_size_sum; congr (1 + alpha * _).
rewrite geom_series_div //.
by rewrite /q /alpha; lia.
Qed.

(* The ball of radius L has at least (2r-1)^L elements.
   The ball already contains the radius-L sphere, of size 2r*(2r-1)^(L-1),
   and 2r >= 2r-1.  This exponent is the growth rate the search-space reading
   of the count quotes. *)
Lemma ball_size_lower (L : nat) : q ^ L <= ball_size r L.
Proof.
case: L => [|L].
  by rewrite expn0; exact: (ball_size_ge1 (ltnW Hr)).
rewrite ball_size_sum.
apply: (leq_trans _ (leq_addl 1 _)).
rewrite expnS.
have Hq_le_a : q <= alpha by rewrite /q /alpha; lia.
have Hsum : q ^ L <= \sum_(k < L.+1) q ^ k.
  by rewrite big_ord_recr /=; apply: leq_addl.
exact: leq_mul Hq_le_a Hsum.
Qed.

End ball_size_formula.

(* ========================================================================== *)
(* Section 5: Connection to word-eval injectivity search space                *)
(* ========================================================================== *)

Section weval_inj_ball_connection.

(* The two counts are indexed differently and are not comparable term by
   term.  For generators word-eval injective at length L, search_space L is
   Tg^L with Tg = 2r, counting words of length exactly L; ball_size r L
   counts reduced words of length at most L and can be the larger of the
   two, as at r = 2, L = 1, where Tg^L = 4 and ball_size r L = 5.  Compared
   at a fixed length the inequality runs the other way, sphere_size r L <=
   Tg^L, with equality only for L <= 1, because after the first letter one
   of the Tg continuations is forbidden.

   In the free group every reduced word names a distinct element and every
   non-reduced word collapses onto a shorter one, so ball_size r L is the
   number of distinct group elements that words of length at most L reach.
   That identification is the reading of the count, not a theorem here. *)

(** (2r-1)^L is at most 1 + 2r * sum_{k<L} (2r-1)^k, which is ball_size r L
    with its definition unfolded to the geometric form.
    The exponential floor on how many free-group elements words of length at
    most L reach.  No search space occurs in the statement: the step from
    this count to a search space is the free-quotient reading of the file
    header. *)
Lemma search_space_exp_growth (r L : nat) :
  1 < r -> (r.*2 - 1) ^ L <= 1 + r.*2 * (\sum_(k < L) (r.*2 - 1) ^ k).
Proof.
move=> Hr.
have := @ball_size_lower r Hr L.
by rewrite ball_size_sum.
Qed.

End weval_inj_ball_connection.
