(* infotheo: information theory and error-correcting codes in Rocq            *)
(* Copyright (C) 2025 infotheo authors, license: LGPL-2.1-or-later            *)
(******************************************************************************)
(* five_card_family: den Boer and Kim as one epsilon-parameterized profile     *)
(*                                                                            *)
(* The den Boer (1989) five-card trick and the Kim-Cetinkaya (2025) biased     *)
(* analysis live on the SAME group: the cyclic C_5 generated by the 5-cycle    *)
(* fc_sigma. Kim's PGG instance FiveCardKim_M uses all five rotations          *)
(* sigma^0..sigma^4 as generators (so its weight distribution can place a      *)
(* distinct probability on each cut); the original den Boer presentation uses   *)
(* the single generator sigma, and both generate <[fc_sigma]> = C_5. The single *)
(* generator is recovered at eps = 0, the perfectly-uniform regime. This file   *)
(* plugs                                                                        *)
(* the heterogeneous-secret bool/'I_5 threshold scheme fcI_scheme (reused from  *)
(* the den Boer directory, since it depends only on N = 5) onto FiveCardKim_M,  *)
(* and bundles a MonodromyProfile parameterized by Kim's bias eps. At eps = 0   *)
(* the bias disappears and the dealing-phase security bound collapses to 0      *)
(* (the perfectly-uniform den Boer regime).                                     *)
(*                                                                            *)
(* Contents:                                                                  *)
(*   fcI_perm_compatible_kim == reconstruction invariance over the FULL group  *)
(*     pgg_G FiveCardKim_M = <[fc_sigma]> (the five generators still generate   *)
(*     the same C_5, so the rotation argument is identical to den Boer).        *)
(*   FiveCardKim_PI          == the five-sheet starting interface (ord_tuple 5) *)
(*   five_card_plug          == the bool/'I_5 ReconPlug on FiveCardKim_M        *)
(*   five_card_profile       == the five-card MonodromyProfile                  *)
(*   five_card_eps0_perfect  == at eps = 0 the security bound is 0              *)
(*                                                                            *)
(* References:                                                                 *)
(*   den Boer (1989), EUROCRYPT, LNCS 434                                       *)
(*   Kim & Cetinkaya (2025), arXiv:2511.05111                                  *)
(******************************************************************************)

From HB Require Import structures.
From mathcomp Require Import ssreflect ssrbool ssrfun eqtype ssrnat seq.
From mathcomp Require Import div fintype tuple finfun finset fingroup perm.
From mathcomp Require Import morphism action bigop order ssrnum ssralg matrix cyclic.
From mathcomp Require Import boolp reals.
From infotheo Require Import realType_ext fdist proba variation_dist.
Require Import pgg_interface.
From pgg_smc Require Import five_card_kim five_card_scheme_I5.
From pgg_reconstruct Require Import pgg_sharing_framework covering_scheme
                                    algebraic_rigidity.
From pgg_smc Require Import pgg_monodromy_profile.

Set Implicit Arguments.
Unset Strict Implicit.
Import Prenex Implicits.

Open Scope group_scope.

(** fcI_perm_compatible_kim — reconstruction is invariant under the monodromy
    share permutation over the FULL group pgg_G FiveCardKim_M.
    Kind: helper.
    @composes: fcI_scheme fc_three_consec_rot fc_sigma_pow_val.
    What: the ts_recon_perm_invariant obligation of five_card_plug, stated for
    Kim's five-generator instance FiveCardKim_M.
    Why: Kim's instance uses all five rotations sigma^0..sigma^4 as generators,
    but they still generate the same cyclic group <[fc_sigma]> = C_5 as the
    single-generator presentation. The ONLY change from the single-generator
    proof is the cyclicity fact Gcyc: the generating set [set sigma^i | i] generates
    <[fc_sigma]> because every sigma^i lies in <[fc_sigma]> and sigma = sigma^1
    is in the generating set. After Gcyc, every group element is a power
    fc_sigma^k, so reindexing the shares by g is a cyclic rotation by k mod 5
    of the decoded row (fc_sigma_pow_val), and fc_three_consec is invariant
    under that rotation (fc_three_consec_rot).
    Used by: five_card_plug (rp_recon_invariant). *)
Lemma fcI_perm_compatible_kim :
  @ts_recon_perm_invariant _ (pgg_G FiveCardKim_M) _ _ fcI_scheme
    (morphism.mfun (@pgg_rho FiveCardKim_M)).
Proof.
rewrite /ts_recon_perm_invariant.
move=> g s shares Hg Hvalid.
rewrite /ts_recon /ts_valid /= in Hvalid *.
rewrite /fcI_recon.
have Gcyc : pgg_G FiveCardKim_M = <[five_card_group.fc_sigma]>.
  rewrite /pgg_G /FiveCardKim_M /=.
  apply/val_inj => /=.
  apply/eqP; rewrite eqEsubset; apply/andP; split.
    rewrite gen_subG; apply/subsetP => x /imsetP[i _ ->].
    by rewrite fc_kim_sigmasE; exact: mem_cycle.
  rewrite cycle_subG; apply: mem_gen; apply/imsetP.
  by exists (@Ordinal 5 1 isT) => //; rewrite fc_kim_sigmasE expg1.
rewrite Gcyc in Hg.
have /cycleP [k Hk] := Hg.
rewrite Hk.
set L := [seq five_card_program.decode_bool x | x <- shares].
have HLsize : size L = 5 by rewrite /L size_map size_tuple.
have Hrot :
    [seq five_card_program.decode_bool x
       | x <- [tuple tnth shares ((five_card_group.fc_sigma ^+ k) i) | i < 5]]
    = rot (k %% 5) L.
  have nth_rot_mod : forall (n p : nat) (xs : seq bool),
      n < 5 -> p < 5 -> size xs = 5 ->
      nth false (rot n xs) p = nth false xs ((p + n) %% 5).
    move=> n p xs Hn Hp Hxs.
    rewrite /rot nth_cat size_drop Hxs.
    case: (ltnP p (5 - n)) => Hpn.
      by rewrite nth_drop addnC modn_small // addnC -ltn_subRL.
    have Hqn : p - (5 - n) < n by rewrite ltn_subLR // subnK ?(ltnW Hn).
    rewrite nth_take //.
    have Heq2 : p + n - 5 = p - (5 - n) by rewrite subnBA ?(ltnW Hn).
    have Hpn5 : (5 <= p + n)%N by rewrite -(subnK (ltnW Hn)) leq_add2r.
    by rewrite -Heq2 -(subnK Hpn5) modnDr modn_small ?addnK //
       Heq2 (leq_ltn_trans (leq_subr _ _) Hp).
  apply: (@eq_from_nth _ false).
    by rewrite size_map size_tuple size_rot HLsize.
  move=> p Hp.
  rewrite size_map size_tuple in Hp.
  rewrite (nth_map (Ordinal Hp)); last by rewrite size_tuple.
  rewrite nth_rot_mod //; last exact: ltn_pmod.
  rewrite (nth_mktuple _ (Ordinal Hp) (Ordinal Hp)) /L.
  have Hq : (p + k %% 5) %% 5 < 5 by exact: ltn_pmod.
  rewrite (nth_map (Ordinal Hp)); last by rewrite size_tuple.
  congr five_card_program.decode_bool.
  rewrite -(tnth_nth (Ordinal Hp) shares (Ordinal Hq)).
  congr (tnth shares _).
  apply: val_inj => /=.
  by rewrite fc_sigma_pow_val /= modnDmr.
rewrite /fcI_valid in Hvalid.
rewrite Hrot fc_three_consec_rot.
- exact: Hvalid.
- exact: ltn_pmod.
- exact: HLsize.
Qed.

(** ord_tuple5_uniq — the five starting card positions are distinct.
    @composes: FiveCardKim_PI
    What: uniq (ord_tuple 5), the uniqueness witness FiveCardKim_PI consumes. *)
Lemma ord_tuple5_uniq : uniq (ord_tuple 5).
Proof. by rewrite val_ord_tuple enum_uniq. Qed.

(** FiveCardKim_PI — the concrete five-sheet starting interface for Kim's
    instance.
    @intent: the identity start tuple (ord_tuple 5) over the five card
    positions of FiveCardKim_M. The identity starts make the G_stable
    condition reduce to reflexivity of pgg_rho (content = fc_content = id),
    exactly as for the s5x5 starting interface. Used-by: five_card_profile. *)
Definition FiveCardKim_PI : PGGInterface FiveCardKim_M :=
  @MkPGGI FiveCardKim_M 4 (ord_tuple 5) ord_tuple5_uniq.

(** five_card_plug — the heterogeneous-secret ReconPlug for FiveCardKim_M.
    @intent: the bool/'I_5 scheme fcI_scheme, the identity content readout
    fc_content, the C_5 monodromy pgg_rho, and the proven full-group
    reconstruction invariance fcI_perm_compatible_kim. Routes Kim's
    five-generator five-card trick through the shared MonodromyProfile program.
    Used-by: five_card_profile. *)
Definition five_card_plug : ReconPlug FiveCardKim_M bool :=
  @MkReconPlug FiveCardKim_M bool fcI_scheme five_card_program.fc_content
    (morphism.mfun (@pgg_rho FiveCardKim_M)) fcI_perm_compatible_kim.

Import GRing.Theory Num.Theory.
Local Open Scope ring_scope.

(** five_card_profile — the five-card MonodromyProfile.
    @intent: bundles FiveCardKim_M, the secret type bool, FiveCardKim_PI and
    five_card_plug. This is the single profile that unifies den Boer and Kim:
    the group, the plug and the starting layout are shared, and the dealing
    distribution's bias eps is data of the separate marginal bound rather than
    of the program layer.
    Used-by: the unified five-card landscape entry. *)
Definition five_card_profile : MonodromyProfile :=
  @MkMonodromyProfile FiveCardKim_M bool FiveCardKim_PI five_card_plug.

(** five_card_eps0_eq0 — at eps = 0 the dealing-phase security bound is 0.
    @main bound: for any positive word length L.+1 the Kim security epsilon
    sw_bound_eps at bias 0 equals 0, the precise sense in which the unbiased
    family member recovers den Boer's perfect dealing-phase anonymity (a
    uniform cyclic cut leaks nothing). At eps = 0 the second-largest eigenvalue
    modulus kim_lambda2 is 0, so any positive power vanishes and the bound
    sqrt 5 * kim_lambda2 ^+ L.+1 collapses to 0 (kim_security_at_zero). Restricted
    to L.+1 because at L = 0 the bound is sqrt 5, not 0 (no shuffle applied).
    Naming: _eq0 marks the lhs = 0 shape (the auditor's own G001 sketch); the
    eps0 component keeps the bias condition explicit. *)
Lemma five_card_eps0_eq0 (R : realType) (L : nat)
    (Hlt : (0:R) < 5%:R^-1) (Hgt : - (4%:R * 5%:R^-1) < (0:R))
    (Hspec : `|(0:R)| < 4%:R / 5%:R) :
  sw_bound_eps (scb_bound (fc_kim_security_bundle Hlt Hgt Hspec L.+1)) = 0.
Proof. by rewrite /= kim_security_at_zero. Qed.
