$ rocq compile <flags of _CoqProject, after> mutation_bare_certify.v
exit status 1, 3.7 s

File "./mutation_bare_certify.v", line 19, characters 0-50:
Warning: Notations "_ <| _ |> _" defined at level 49 with arguments constr
at next level, constr at next level and "_ <| _" defined at level 70
with arguments constr at next level, constr at next level
have incompatible prefixes. One of them will likely not work.
[notation-incompatible-prefix,parsing,default]
File "./mutation_bare_certify.v", line 30, characters 4-51:
Error: Syntax error: '.' expected after [gallina] (in [vernac_aux]).

