"""
ex3_cps_nimpc.py
================
Demonstration: Commuting Permutation Systems (CPS) for NIMPC (§4).

A Commuting Permutation System (CPS) is a collection of permutation families
{π_{i,x} : x ∈ X_i} for each party i such that every pair of permutations
from *different* parties commutes:

    π_{i,x} ∘ π_{j,y} = π_{j,y} ∘ π_{i,x}   for all i ≠ j, all x, y.

This pairwise commutativity is the algebraic condition that makes NIMPC
possible: the final product π_{1,x1} · π_{2,x2} · · · π_{n,xn} is
order-independent, so no party gains information from the order in which
contributions are assembled.

Sections:
  1. CPS example — cyclic group Z/4Z ≤ S_4
  2. Order-independence verification (all 6 orderings of 3 parties)
  3. Partial commutativity contrast — S_3 with a non-commuting pair
  4. RAAG middle ground — which reorderings are valid and which are not
"""

import itertools
from smc_pgg_core import (
    Permutation, word_product, commutator,
    MonodromyGroup, print_separator,
)


# ============================================================
# Section 1 — CPS construction: cyclic group Z/4Z ≤ S_4
# ============================================================
#
# We use the cyclic group generated by the 4-cycle c = (0 1 2 3).
# Its four elements are:
#   c^0 = id
#   c^1 = (0 1 2 3)
#   c^2 = (0 2)(1 3)
#   c^3 = (0 3 2 1)
#
# Since the group is abelian, every pair of elements commutes — in
# particular permutations chosen by different parties always commute.
#
# Party assignments (inputs are single bits 0/1):
#   Party 1: π_{1,0} = c^0 = id,   π_{1,1} = c^1
#   Party 2: π_{2,0} = c^0 = id,   π_{2,1} = c^2
#   Party 3: π_{3,0} = c^0 = id,   π_{3,1} = c^3
#
# Product:  π_{1,x1} · π_{2,x2} · π_{3,x3}
#         = c^{x1} · c^{2·x2} · c^{3·x3}
#         = c^{x1 + 2·x2 + 3·x3}
#
# Endpoint at sheet 0:
#   endpoint = (x1 + 2·x2 + 3·x3) mod 4
#
# This computes the function f(x1, x2, x3) = (x1 + 2*x2 + 3*x3) mod 4.

N = 4  # sheets

c1 = Permutation.from_cycles(N, (0, 1, 2, 3))   # c^1 = (0 1 2 3)
c2 = Permutation.from_cycles(N, (0, 2), (1, 3))  # c^2 = (0 2)(1 3)
c3 = Permutation.from_cycles(N, (0, 3, 2, 1))    # c^3 = (0 3 2 1)
e  = Permutation.identity(N)                      # c^0 = id

# Party permutation families
pi = {
    1: {0: e,  1: c1},
    2: {0: e,  1: c2},
    3: {0: e,  1: c3},
}


def cps_product(x1: int, x2: int, x3: int, order=(1, 2, 3)) -> Permutation:
    """Compute the product of party permutations in the given order."""
    factors = [pi[i][{1: x1, 2: x2, 3: x3}[i]] for i in order]
    return word_product(factors)


def cps_endpoint(x1: int, x2: int, x3: int, order=(1, 2, 3)) -> int:
    """Endpoint at sheet 0 for the given input and evaluation order."""
    return cps_product(x1, x2, x3, order)(0)


def cps_expected(x1: int, x2: int, x3: int) -> int:
    """Reference: f(x1,x2,x3) = (x1 + 2*x2 + 3*x3) mod 4."""
    return (x1 + 2 * x2 + 3 * x3) % 4


print_separator("Section 1 — CPS construction: Z/4Z ≤ S_4")

print("\nGenerators of the cyclic group Z/4Z (all powers of c = (0 1 2 3)):")
print(f"  c^0 = id  = {e}")
print(f"  c^1       = {c1}")
print(f"  c^2       = {c2}")
print(f"  c^3       = {c3}")

print("\nParty permutation families (input bit -> permutation):")
for i in (1, 2, 3):
    for x, label in [(0, "0 -> id"), (1, "1 -> c^" + str(i))]:
        print(f"  Party {i}: x={x}  -> {pi[i][x]}")

print("\nPairwise commutativity check (all pairs of generators c^i, c^j):")
generators = [e, c1, c2, c3]
labels = ["c^0", "c^1", "c^2", "c^3"]
all_commute = True
for (i, gi), (j, gj) in itertools.combinations(enumerate(generators), 2):
    comm = gi.commutes_with(gj)
    if not comm:
        all_commute = False
    status = "commute" if comm else "DO NOT commute"
    print(f"  {labels[i]} and {labels[j]}: {status}")
print(f"\n  => All elements of Z/4Z commute: {all_commute}")


# ============================================================
# Section 2 — Order-independence: all 6 orderings of 3 parties
# ============================================================

print_separator("Section 2 — Order-independence (all 6 party orderings)")

all_orders = list(itertools.permutations([1, 2, 3]))
inputs = list(itertools.product([0, 1], repeat=3))

print("\nFor each input (x1,x2,x3), the endpoint at sheet 0 must be the same")
print("regardless of which order the party permutations are multiplied.\n")

print(f"  {'Input':<18}  {'Expected':>8}  " +
      "  ".join(f"order {''.join(map(str,o))}" for o in all_orders))

order_independent = True
for (x1, x2, x3) in inputs:
    expected = cps_expected(x1, x2, x3)
    endpoints = [cps_endpoint(x1, x2, x3, order) for order in all_orders]
    all_same = all(ep == expected for ep in endpoints)
    if not all_same:
        order_independent = False
    row = f"  ({x1},{x2},{x3})  expected={expected}  " + \
          "        ".join(str(ep) for ep in endpoints)
    flag = "" if all_same else "  <-- MISMATCH"
    print(row + flag)

print(f"\n  => CPS is order-independent for all inputs: {order_independent}")

print("\nExplanation:")
print("  Because every π_{i,xi} and π_{j,xj} (i≠j) are both powers of c,")
print("  and c generates an abelian group, they commute for every input pair.")
print("  Hence π_{σ(1),x_{σ(1)}} · ... · π_{σ(3),x_{σ(3)}} = c^{x1+2x2+3x3}")
print("  for every permutation σ of {1,2,3}.")


# ============================================================
# Section 3 — Partial commutativity contrast: S_3
# ============================================================
#
# S_3 is generated by:
#   σ = (0 1 2)   (3-cycle, order 3)
#   τ = (0 1)     (transposition, order 2)
#
# These do NOT commute: σ·τ ≠ τ·σ.
#
# Concretely:
#   σ·τ: 0->1->0, 1->2->2, 2->0->1  =  (1 2)
#   τ·σ: 0->0->1, 1->1->2, 2->2->0  =  (0 1 2)·... let's compute
#
# So if party A contributes σ and party B contributes τ, the result
# depends on who goes first.

print_separator("Section 3 — Partial commutativity contrast: S_3")

M = 3  # sheets

sigma = Permutation.from_cycles(M, (0, 1, 2))   # 3-cycle
tau   = Permutation.from_cycles(M, (0, 1))       # transposition

print(f"\n  σ = {sigma}  (3-cycle, order {sigma.order()})")
print(f"  τ = {tau}   (transposition, order {tau.order()})")

st = sigma * tau
ts = tau * sigma
print(f"\n  σ · τ = {st}   (apply σ first, then τ)")
print(f"  τ · σ = {ts}   (apply τ first, then σ)")
print(f"\n  σ · τ == τ · σ?  {st == ts}")
print(f"\n  => σ and τ do NOT commute: [σ, τ] = {commutator(sigma, tau)}")

# Now demonstrate that the function computed depends on order.
# Suppose Party A's input selects σ (x_A=1) or id (x_A=0).
# Suppose Party B's input selects τ (x_B=1) or id (x_B=0).

pi_A = {0: Permutation.identity(M), 1: sigma}
pi_B = {0: Permutation.identity(M), 1: tau}

print("\nParty permutation families (S_3, non-commuting):")
print(f"  Party A: x=0 -> id,  x=1 -> σ={sigma}")
print(f"  Party B: x=0 -> id,  x=1 -> τ={tau}")

print("\nEndpoint at sheet 0, both orderings of {A, B}:")
print(f"  {'(xA,xB)':<10}  order A·B  order B·A  same?")
for xA, xB in itertools.product([0, 1], repeat=2):
    pAB = word_product([pi_A[xA], pi_B[xB]])(0)
    pBA = word_product([pi_B[xB], pi_A[xA]])(0)
    same = pAB == pBA
    print(f"  ({xA},{xB})       {pAB}          {pBA}          {same}")

print("\n  => When inputs select the non-commuting generators,")
print("     the result depends on evaluation order: this is NOT a CPS.")


# ============================================================
# Section 4 — RAAG middle ground: 3 generators, mixed commutativity
# ============================================================
#
# A Right-Angled Artin Group (RAAG) A(Γ) has generators {a, b, c} with
# commutativity exactly the edges of a graph Γ.  We embed generators as
# permutations in S_5, choosing them so that:
#
#   a and b  commute   (edge a-b in Γ)
#   a and c  commute   (edge a-c in Γ)
#   b and c  DO NOT commute  (no edge b-c in Γ)
#
# Graph Γ:  b — a — c   (a is connected to both b and c; b,c are not connected)
#
# Concretely (in S_5):
#   a = (0 1)(2 3)
#   b = (0 2)(1 3)
#   c = (0 3)(1 2)
#
# Check:
#   a*b = (0 1)(2 3) · (0 2)(1 3) = ?
#   b*a = (0 2)(1 3) · (0 1)(2 3) = ?
#   Similarly for (a,c) and (b,c).
#
# (If these don't all have the desired commutativity pattern, we fall back to
#  a direct construction in S_4 using the Klein four-group for {a,b,c} with
#  one pair deliberately outside it.)

print_separator("Section 4 — RAAG middle ground: 3 generators, mixed commutativity")

# Construct generators in S_4 using the Klein four-group V4 = {e, r, s, r*s}.
# V4 is abelian, so r and s commute, as do r and r*s, and s and r*s.
# To get a non-commuting pair, we add a generator outside V4.

K = 4  # sheets

# Klein four-group generators
r   = Permutation.from_cycles(K, (0, 1), (2, 3))   # (0 1)(2 3)
s   = Permutation.from_cycles(K, (0, 2), (1, 3))   # (0 2)(1 3)
rs  = r * s                                          # (0 3)(1 2)  = (0 1)(2 3)*(0 2)(1 3)

# A 3-cycle that does not commute with s (lies outside V4 ≤ S_4)
t   = Permutation.from_cycles(K, (0, 1, 2))         # (0 1 2)

print("\nGenerators:")
print(f"  r  = {r}   (order {r.order()})")
print(f"  s  = {s}   (order {s.order()})")
print(f"  rs = {rs}  (order {rs.order()})  [= r·s, still in V4]")
print(f"  t  = {t}   (order {t.order()})  [outside V4]")

print("\nPairwise commutativity:")
gen_pairs = [("r", r, "s", s), ("r", r, "t", t), ("s", s, "t", t)]
for (na, ga, nb, gb) in gen_pairs:
    comm = ga.commutes_with(gb)
    ab = ga * gb
    ba = gb * ga
    status = "commute" if comm else "DO NOT commute"
    edge   = "[edge in Γ]" if comm else "[no edge in Γ]"
    print(f"  {na} and {nb}: {na}·{nb}={ab},  {nb}·{na}={ba}  =>  {status:16s} {edge}")

# RAAG graph:  Γ: r — s   (only r and s commute; r,t and s,t do NOT commute)
# Recheck which pairs actually commute
pairs = [("r", r), ("s", s), ("t", t)]
commutativity = {}
for (na, ga), (nb, gb) in itertools.combinations(pairs, 2):
    commutativity[(na, nb)] = ga.commutes_with(gb)

print("\nActual commutativity graph Γ (edges = commuting pairs):")
for (na, nb), comm in commutativity.items():
    symbol = "—" if comm else "✗"
    print(f"  {na} {symbol} {nb}   ({'commute' if comm else 'do not commute'})")

# Identify which reorderings of a 3-party word are valid.
# Party 1 uses r, Party 2 uses s, Party 3 uses t.
# A reordering is valid if and only if it only swaps adjacent commuting generators.
# More precisely, two orderings give the same product iff they are
# trace-equivalent under independence relation I = commutativity graph.

print("\nParty assignment for the 3-party RAAG example:")
print("  Party 1: generator r")
print("  Party 2: generator s")
print("  Party 3: generator t")

# Enumerate all 6 orderings of the word [r, s, t] and compute the product.
gen_map = {"r": r, "s": s, "t": t}
gen_names_3 = ["r", "s", "t"]
print("\nProducts for all 6 orderings of [r, s, t] (input = 1 for each party):")
products = {}
for perm_order in itertools.permutations(gen_names_3):
    prod = word_product([gen_map[g] for g in perm_order])
    products[perm_order] = prod
    print(f"  {'·'.join(perm_order)} = {prod}")

# Group by outcome
from collections import defaultdict
outcome_groups: dict = defaultdict(list)
for order, prod in products.items():
    outcome_groups[prod].append(order)

print("\nGrouping orderings by their product:")
for prod, orders in outcome_groups.items():
    order_strs = [" · ".join(o) for o in orders]
    print(f"  Product {prod}:  {',  '.join(order_strs)}")

# Explain in terms of trace equivalence
print("\nExplanation via trace equivalence:")
print("  Independence relation I from commutativity graph Γ:")
for (na, nb), comm in commutativity.items():
    if comm:
        print(f"    ({na},{nb}) ∈ I  (may be swapped freely)")
    else:
        print(f"    ({na},{nb}) ∉ I  (order is fixed)")

print()
print("  Foata normal form groups letters that can fire in parallel.")
print("  Two orderings give the same product iff they are I-trace-equivalent")
print("  (i.e., reachable by repeatedly swapping adjacent independent letters).")

# Use TraceMonoid to compute Foata normal forms and check equivalence
from smc_pgg_core import TraceMonoid

independence_pairs = {(na, nb) for (na, nb), comm in commutativity.items() if comm}
tm = TraceMonoid(gen_names_3, independence_pairs)

print("\nFoata normal forms for all 6 orderings:")
fnf_groups: dict = defaultdict(list)
for perm_order in itertools.permutations(gen_names_3):
    fnf = tm.foata_normal_form(list(perm_order))
    fnf_groups[str(fnf)].append(perm_order)
    print(f"  {'·'.join(perm_order):12s}  FNF = {fnf}")

print("\nGrouping orderings by Foata normal form (= trace equivalence class):")
for fnf_str, orders in fnf_groups.items():
    order_strs = [" · ".join(o) for o in orders]
    print(f"  FNF {fnf_str}:")
    for os in order_strs:
        print(f"    {os}")

print()
print("  => Orderings in the same FNF class give the same product.")
print("     Orderings in different FNF classes may give different products.")
print("     This is the RAAG middle ground: some reorderings are free,")
print("     others are forbidden because the generators do not commute.")


# ============================================================
# Section 5 — RAAG-Computed Function: Partial Commutativity Required
# ============================================================
#
# We construct a concrete 3-party function f(x1,x2,x3) that:
#   - Requires RAAG structure to compute correctly AND efficiently.
#   - CPS would give the WRONG answer (forces all generators to commute).
#   - Fully sequential evaluation is correct but wastes a round on P3.
#   - ONLY the RAAG structure gives both correctness AND efficiency.
#
# Setup (in S_5, generators are transpositions):
#   s1 = (0 1)   — Party 1
#   s2 = (1 2)   — Party 2
#   s4 = (3 4)   — Party 3
#
# Independence relation (verify computationally):
#   s1 ↔ s4  commute  (disjoint support)
#   s2 ↔ s4  commute  (disjoint support)
#   s1 ↔ s2  do NOT commute  (share element 1)
#
# Function: f(x1,x2,x3) = endpoint of s1^{x1} · s2^{x2} · s4^{x3} at sheet 0.
#
# Foata normal form of [s1, s2, s4]:
#   Round 1: {s1, s4}  (s4 is independent of s1 and can fire together with s1)
#   Round 2: {s2}      (s2 must wait for s1)
#   => Depth 2 (not 3).  P3 runs in round 1 concurrently with P1.

print_separator("Section 5 — RAAG-Computed Function: Partial Commutativity Required")

P = 5  # sheets

s1 = Permutation.from_cycles(P, (0, 1))   # (0 1)
s2 = Permutation.from_cycles(P, (1, 2))   # (1 2)
s4 = Permutation.from_cycles(P, (3, 4))   # (3 4)
eP = Permutation.identity(P)

print("\nGenerators (in S_5):")
print(f"  s1 = {s1}  (Party 1)")
print(f"  s2 = {s2}  (Party 2)")
print(f"  s4 = {s4}  (Party 3)")

print("\nPairwise commutativity check:")
gen5_pairs = [("s1", s1, "s2", s2), ("s1", s1, "s4", s4), ("s2", s2, "s4", s4)]
independence5 = set()
for (na, ga, nb, gb) in gen5_pairs:
    comm = ga.commutes_with(gb)
    status = "commute ✓" if comm else "do NOT commute ✗"
    print(f"  {na} and {nb}: {status}")
    if comm:
        independence5.add((na, nb))

# Function: f(x1, x2, x3) = endpoint at sheet 0 of s1^x1 · s2^x2 · s4^x3
def raag_fn(x1, x2, x3):
    """Standard RAAG word order: s1^x1 · s2^x2 · s4^x3, endpoint at sheet 0."""
    factors = [s1 if x1 else eP, s2 if x2 else eP, s4 if x3 else eP]
    return word_product(factors)(0)

print("\nTruth table: f(x1,x2,x3) = endpoint of s1^x1·s2^x2·s4^x3 at sheet 0")
print(f"  {'(x1,x2,x3)':<14}  f")
all_inputs = list(itertools.product([0, 1], repeat=3))
for (x1, x2, x3) in all_inputs:
    print(f"  ({x1},{x2},{x3})           {raag_fn(x1, x2, x3)}")

# Show that swapping P1/P2 order changes the result (so this is NOT a CPS)
def raag_fn_swapped(x1, x2, x3):
    """Swapped P1/P2: s2^x2 · s1^x1 · s4^x3, endpoint at sheet 0."""
    factors = [s2 if x2 else eP, s1 if x1 else eP, s4 if x3 else eP]
    return word_product(factors)(0)

print("\nSwapping P1/P2 order (s2^x2 · s1^x1 · s4^x3 instead of s1^x1 · s2^x2 · s4^x3):")
print(f"  {'(x1,x2,x3)':<14}  standard  swapped  same?")
cps_valid = True
for (x1, x2, x3) in all_inputs:
    std = raag_fn(x1, x2, x3)
    swp = raag_fn_swapped(x1, x2, x3)
    same = std == swp
    if not same:
        cps_valid = False
    flag = "" if same else "  <-- DIFFERS"
    print(f"  ({x1},{x2},{x3})           {std}         {swp}        {same}{flag}")
print(f"\n  => This is a CPS (P1/P2 swap safe): {cps_valid}")
print("     CPS would INCORRECTLY allow arbitrary reordering of s1 and s2.")

# Show that moving P3 earlier/later does NOT change result (RAAG parallelism)
def raag_fn_p3_first(x1, x2, x3):
    """P3 first: s4^x3 · s1^x1 · s2^x2, endpoint at sheet 0."""
    factors = [s4 if x3 else eP, s1 if x1 else eP, s2 if x2 else eP]
    return word_product(factors)(0)

print("\nMoving P3 to the front (s4^x3 · s1^x1 · s2^x2) — RAAG parallelism:")
print(f"  {'(x1,x2,x3)':<14}  standard  P3-first  same?")
p3_parallel_valid = True
for (x1, x2, x3) in all_inputs:
    std = raag_fn(x1, x2, x3)
    p3f = raag_fn_p3_first(x1, x2, x3)
    same = std == p3f
    if not same:
        p3_parallel_valid = False
    print(f"  ({x1},{x2},{x3})           {std}         {p3f}        {same}")
print(f"\n  => P3 can run concurrently with P1 (RAAG parallelism safe): {p3_parallel_valid}")

# Foata normal form analysis
gen5_names = ["s1", "s2", "s4"]
tm5 = TraceMonoid(gen5_names, independence5)
word5 = ["s1", "s2", "s4"]
fnf5 = tm5.foata_normal_form(word5)
print("\nFoata normal form of the word [s1, s2, s4]:")
print(f"  FNF = {fnf5}")
print(f"  Depth (number of rounds) = {len(fnf5)}")
print("  Round 1: {s1, s4}  — P1 and P3 run concurrently")
print("  Round 2: {s2}      — P2 waits for P1 (s1 and s2 do not commute)")
print()
print("  Fully sequential depth would be 3 (one round per party).")
print("  RAAG reduces to depth 2: P3 is parallelised with P1 for free.")
print()
print("  => ONLY the RAAG structure gives BOTH correctness AND optimal depth:")
print("       CPS forces all pairs to commute  =>  computes the WRONG function.")
print("       Fully sequential avoids commutativity =>  correct but depth 3.")
print("       RAAG respects the exact commutativity graph =>  correct, depth 2.")


# ============================================================
# Summary
# ============================================================

print_separator("Summary")
print("""
CPS (Commuting Permutation System):
  ALL generator pairs commute  =>  evaluation order is completely free.
  Every permutation of the party order yields the same product.
  Example: cyclic group Z/4Z ≤ S_4 — all elements are powers of one cycle.

Non-commuting system (S_3 fragment):
  σ = (0 1 2) and τ = (0 1) do NOT commute.
  When parties select these generators, the evaluation order matters.
  This violates the CPS condition — NIMPC is not supported directly.

RAAG middle ground:
  Some pairs commute (edges in Γ), others do not (non-edges).
  Reorderings that only swap commuting adjacent generators are free.
  Reorderings that cross a non-commuting pair change the product.
  The safe reorderings are exactly the trace-equivalence classes of the
  trace monoid M(Σ, I) where I is the commutativity (independence) relation.
""")
