(* infotheo: information theory and error-correcting codes in Rocq            *)
(* Copyright (C) 2025 infotheo authors, license: LGPL-2.1-or-later            *)
From HB Require Import structures.
From mathcomp Require Import ssreflect ssrbool ssrfun eqtype ssrnat seq.
From mathcomp Require Import div fintype tuple finfun finset fingroup perm.
From mathcomp Require Import morphism action cyclic bigop.
From pgg_smc Require Import pgg_interface.

(******************************************************************************)
(* PGG: Abelian (Cyclic) Group Instance for MonodromyRepr Mixin              *)
(* Group presentation: <sigma>  (cyclic, abelian)                            *)
(*                                                                           *)
(* Constructs a MonodromyReprType instance where G = <[sigma]> is a cyclic   *)
(* subgroup of S_N generated by a permutation sigma.                         *)
(*                                                                           *)
(*   ncycle n == the canonical N-cycle (0 1 2 ... N-1) on 'I_(n.+2)         *)
(*   Cyclic_PGGTypes n sigma == PGGTypes record for G = <[sigma]>            *)
(*   Cyclic_isMonodromyRepr == HB instance registering the inclusion morphism *)
(*   Cyclic_PGG_2 n sigma == 2-party PGGInterface for the cyclic instance   *)
(*   NCycle_PGGTypes n == PGGTypes using the canonical N-cycle               *)
(*   NCycle_PGG_2 n == 2-party PGGInterface using the canonical N-cycle     *)
(*                                                                           *)
(* Key properties:                                                           *)
(*   cyclic_G_abelian : abelian <[sigma]>                                    *)
(*   ncycle_order : #[ncycle n] = N                                          *)
(*   ncycle_iter : (ncycle n ^+ k) x = (x + k) mod N                        *)
(*                                                                           *)
(* The abelian collapse is formalized in abelian_word_collapse.v:            *)
(* search_space L <= 'C(L+Tg-1, Tg-1) via frequency-vector counting.       *)
(******************************************************************************)

Set Implicit Arguments.
Unset Strict Implicit.
Import Prenex Implicits.

(* ========================================================================== *)
(* Canonical N-cycle permutation                                              *)
(* ========================================================================== *)

Section ncycle_def.

Variable n : nat.
Let N := n.+2.

(** shift_fun — the cyclic shift i |-> (i+1) mod N on 'I_N.
    Kind: helper.
    Why: Underlying function of the canonical N-cycle permutation; kept as a standalone definition to expose its arithmetic form.
    Used by: unshift_fun (as inverse), shift_unshiftK, ncycle.
*)
Definition shift_fun (i : 'I_N) : 'I_N :=
  Ordinal (ltn_pmod (i.+1) (isT : (0 < N)%N)).

(** unshift_fun — inverse of shift_fun: decrement by 1 modulo N.
    Kind: helper.
    Why: Supplies the inverse witness that lets us build an injective permutation from shift_fun via can_inj.
    Used by: shift_unshiftK, shift_fun_inj.
*)
Definition unshift_fun (i : 'I_N) : 'I_N :=
  Ordinal (ltn_pmod (i + n.+1) (isT : (0 < N)%N)).

(** shift_unshiftK — unshift inverts shift on 'I_N.
    Kind: helper.
    Why: Cancellation lemma exhibiting shift_fun as a bijection, feeding injectivity.
    Used by: shift_fun_inj.
*)
Lemma shift_unshiftK : cancel shift_fun unshift_fun.
Proof.
move=> i; apply: val_inj => /=.
rewrite modnDml addnC addSn addnS.
by change ((N + i) %% N = i); rewrite modnDl modn_small.
Qed.

(** shift_fun_inj — the cyclic shift is injective.
    Kind: helper.
    Why: Required to package shift_fun as a {perm 'I_N} via MathComp's perm constructor.
    Used by: ncycle.
*)
Lemma shift_fun_inj : injective shift_fun.
Proof. exact: can_inj shift_unshiftK. Qed.

(** ncycle — the canonical N-cycle permutation (0 1 2 ... N-1) on 'I_N.
    Kind: instance.
    Why: Packages shift_fun as a {perm 'I_N} via the injectivity witness; the main generator of the canonical cyclic PGG instance.
*)
Definition ncycle : {perm 'I_N} := perm shift_fun_inj.

(** ncycleE — evaluation of the canonical N-cycle on i as (i+1) mod N.
    Kind: helper.
    Why: Rewrite lemma that hides the permE/permute layer so reasoning about ncycle works with explicit modular arithmetic.
    Used by: ncycle_iter.
*)
Lemma ncycleE (i : 'I_N) :
  ncycle i = Ordinal (ltn_pmod (i.+1) (isT : (0 < N)%N)).
Proof. by rewrite /ncycle permE. Qed.

(* Iterated application of the N-cycle *)
Lemma ncycle_iter (k : nat) (x : 'I_N) :
  ((ncycle ^+ k)%g : {perm 'I_N}) x =
  Ordinal (ltn_pmod (x + k) (isT : (0 < N)%N)).
Proof.
elim: k => [|k IHk].
  rewrite expg0 perm1; apply val_inj => /=.
  by rewrite addn0 modn_small.
rewrite expgSr permM IHk ncycleE; apply val_inj => /=.
by rewrite addnS -addn1 modnDml addn1.
Qed.

(** ncycle_expN — the N-th power of the canonical N-cycle is the identity permutation.
    Kind: helper.
    Why: Together with a non-divisibility check it pins down the order of ncycle to exactly N.
    Used by: ncycle_order.
*)
Lemma ncycle_expN : (ncycle ^+ N = 1 :> {perm 'I_N})%g.
Proof.
apply/permP => x; rewrite ncycle_iter perm1; apply val_inj => /=.
by rewrite modnDr modn_small.
Qed.

(* Full order of the canonical N-cycle *)
Lemma ncycle_order : #[ncycle]%g = N.
Proof.
apply/eqP; rewrite eqn_dvd.
apply/andP; split.
  by rewrite order_dvdn; apply/eqP; exact ncycle_expN.
rewrite /dvdn.
have /permP /(_ ord0) := expg_order ncycle.
rewrite ncycle_iter perm1 => /eqP.
by rewrite -val_eqE /= add0n.
Qed.

End ncycle_def.

(* ========================================================================== *)
(* Cyclic Group Instance for MonodromyRepr                                    *)
(* ========================================================================== *)

Section cyclic_instance.

Variable n : nat.
Let N := n.+2.
Let gT : finGroupType := {perm 'I_N}.

Variable sigma : gT.
Let G : {group gT} := <[sigma]>.

(* Inclusion morphism: identity on the subgroup *)
Lemma incl_morphM : {in G &, {morph (@id gT) : x y / (x * y)%g}}.
Proof. by []. Qed.

(** incl_morph — the identity inclusion morphism from the cyclic subgroup G into {perm 'I_N}.
    Kind: instance.
    Why: Supplies the morphism data required by the isMonodromyRepr mixin on Cyclic_PGGTypes.
*)
Definition incl_morph : {morphism G >-> {perm 'I_N}} :=
  Morphism incl_morphM.

(** Cyclic_PGGTypes — PGGTypes record whose group is G = <[sigma]>, a cyclic subgroup of {perm 'I_N}.
    Kind: instance.
    Why: Concrete PGGTypes value used to equip the cyclic abelian case with the MonodromyRepr / Generators HB mixins.
*)
Definition Cyclic_PGGTypes := @MkPGG gT N.-1 G.

HB.instance Definition Cyclic_isMonodromyRepr :=
  @isMonodromyRepr.Build Cyclic_PGGTypes incl_morph.

(** cyclic_sigmas — singleton generator tuple [sigma] for a 1-generator cyclic PGG.
    Kind: instance.
    Why: Generator tuple required by hasGenerators HB instance on the cyclic PGGTypes.
*)
Definition cyclic_sigmas : 1.-tuple gT := [tuple sigma].

(** tnth_cyclic_sigmas — tuple lookup in the singleton generator tuple always returns sigma.
    Kind: helper.
    Why: Rewrite lemma used to unfold cyclic_sigmas inside group products.
    Used by: cyclic_sigmas_gen, cyclic_word_eval.
*)
Lemma tnth_cyclic_sigmas (i : 'I_1) : tnth cyclic_sigmas i = sigma.
Proof. by rewrite (tnth_nth sigma) /=; case: i => [[|]]. Qed.

(** cyclic_sigmas_gen — the singleton tuple [sigma] generates the cyclic subgroup G = <[sigma]>.
    Kind: helper.
    Why: Required witness for the hasGenerators HB instance that equips Cyclic_PGGTypes with the generating tuple.
    Used by: Cyclic_hasGenerators HB instance.
*)
Lemma cyclic_sigmas_gen :
  <<[set tnth cyclic_sigmas i | i : 'I_1]>>%G = G.
Proof.
have -> : [set tnth cyclic_sigmas i | i : 'I_1] = [set sigma]; last by [].
apply/setP => x; rewrite in_set1; apply/idP/idP.
  by move/imsetP => [i _ ->]; rewrite tnth_cyclic_sigmas.
by move/eqP => ->; apply/imsetP; exists ord0 => //; rewrite tnth_cyclic_sigmas.
Qed.

HB.instance Definition Cyclic_hasGenerators :=
  @hasGenerators.Build Cyclic_PGGTypes 0 cyclic_sigmas cyclic_sigmas_gen.

(* Key property: cyclic groups are abelian *)
Lemma cyclic_G_abelian : abelian G.
Proof. exact: cycle_abelian. Qed.

(* Word evaluation in the cyclic (1-generator) instance *)
Lemma cyclic_word_eval (L : nat) (w : @pgg_word Cyclic_PGGTypes L) :
  @word_eval Cyclic_PGGTypes L w = (sigma ^+ L)%g.
Proof.
rewrite /word_eval; under eq_bigr do rewrite tnth_cyclic_sigmas.
by rewrite big_const card_ord iter_mulg_1.
Qed.

(** cyclic_search_space_le — in a cyclic instance, at most #[sigma] distinct elements are reachable.
    Kind: main.
    Why: Specialization of search_space_leG to cyclic groups; records the concrete collapse from L^r to #[sigma].
*)
Lemma cyclic_search_space_le (L : nat) :
  @search_space Cyclic_PGGTypes L <= #[sigma]%g.
Proof.
apply: leq_trans (@search_space_leG Cyclic_PGGTypes L) _.
by rewrite /= orderE.
Qed.

(* 2-party interface: starts = [0, 1] *)
Let M : MonodromyReprType := Cyclic_PGGTypes.

(** cyclic_starts_2 — the canonical pair of starts [0; 1] for a 2-party cyclic instance.
    Kind: instance.
    Why: Concrete starts tuple used to instantiate the 2-party PGGInterface over a cyclic group.
*)
Definition cyclic_starts_2 : 2.-tuple 'I_N :=
  [tuple @Ordinal N 0 isT; @Ordinal N 1 isT].

(** cyclic_starts_2_uniq — the two starts 0 and 1 are distinct (as ordinals in 'I_N).
    Kind: helper.
    Why: Uniqueness proof required by the PGGInterface constructor for the 2-party cyclic instance.
    Used by: Cyclic_PGG_2.
*)
Lemma cyclic_starts_2_uniq : uniq cyclic_starts_2.
Proof. by vm_compute. Qed.

(** Cyclic_PGG_2 — 2-party PGG interface for a cyclic instance with starts [0; 1].
    Kind: instance.
    Why: Packages the cyclic MonodromyReprType with a minimal 2-party dealer/relay start configuration.
*)
Definition Cyclic_PGG_2 : PGGInterface M :=
  @MkPGGI M 1 cyclic_starts_2 cyclic_starts_2_uniq.

End cyclic_instance.

(* ========================================================================== *)
(* Concrete instance using the canonical N-cycle                              *)
(* ========================================================================== *)

Section ncycle_instance.

Variable n : nat.
Let N := n.+2.

Definition NCycle_PGGTypes := @Cyclic_PGGTypes n (ncycle n).

Let M : MonodromyReprType := NCycle_PGGTypes.

(** NCycle_PGG_2 — 2-party PGG interface for the canonical N-cycle permutation.
    Kind: instance.
    Why: Convenience wrapper that instantiates Cyclic_PGG_2 with the standard N-cycle ncycle n as the generator.
*)
Definition NCycle_PGG_2 : PGGInterface M :=
  @Cyclic_PGG_2 n (ncycle n).

End ncycle_instance.

(* ========================================================================== *)
(* Parametric Abelian Instance: m+1 Disjoint Transpositions                   *)
(*                                                                            *)
(* sigma_i = tperm(2*i, 2*i+1) for i = 0, ..., m on N = 2*(m+1) sheets.    *)
(* All generators commute (disjoint support).                                 *)
(* Existing abel_sigmas (in rigidity_abelian_instance.v) is the special case *)
(* m=1 giving N=4.                                                           *)
(* ========================================================================== *)

Section disjoint_transpositions.

Variable m : nat.
Let Tg := m.+1.
Let N := Tg.*2.

(** dt_even_lt — the even endpoint 2i of the i-th disjoint transposition is a valid sheet index.
    Kind: helper.
    Why: Bound needed to build the Ordinal argument for the first tperm slot in dt_gen.
    Used by: dt_gen.
*)
Lemma dt_even_lt (i : 'I_Tg) : (val i).*2 < N.
Proof. have := valP i; rewrite /N /Tg ltn_double; exact id. Qed.

(** dt_odd_lt — the odd endpoint 2i+1 of the i-th disjoint transposition is a valid sheet index.
    Kind: helper.
    Why: Bound needed to build the Ordinal argument for the second tperm slot in dt_gen.
    Used by: dt_gen.
*)
Lemma dt_odd_lt (i : 'I_Tg) : (val i).*2.+1 < N.
Proof. have := valP i; rewrite /N /Tg ltn_Sdouble; exact id. Qed.

(** dt_gen — the i-th generator in the disjoint-transposition abelian instance.
    Kind: instance.
    Why: Provides the concrete generator family sigma_i = tperm(2i, 2i+1) used to instantiate the parametric abelian PGG on 2(m+1) sheets.
*)
Definition dt_gen (i : 'I_Tg) : {perm 'I_N} :=
  tperm (Ordinal (dt_even_lt i)) (Ordinal (dt_odd_lt i)).

(** dt_gen_tuple — tuple view of the disjoint-transposition generator family dt_gen.
    Kind: instance.
    Why: Supplies the Tg-tuple form needed to instantiate hasGenerators for the parametric abelian PGG.
*)
Definition dt_gen_tuple : Tg.-tuple {perm 'I_N} := gen_tuple_of dt_gen.

(** dt_gen_tupleE — tuple lookup for dt_gen agrees with the defining function.
    Kind: helper.
    Why: Unfolds the gen_tuple_of wrapper so downstream rewrites can apply dt_gen directly.
    Used by: downstream abelian instantiations using disjoint transposition generators.
*)
Lemma dt_gen_tupleE (i : 'I_Tg) : tnth dt_gen_tuple i = dt_gen i.
Proof. exact: gen_tuple_ofE. Qed.

End disjoint_transpositions.
