(* infotheo: information theory and error-correcting codes in Rocq            *)
(* Copyright (C) 2025 infotheo authors, license: LGPL-2.1-or-later            *)
(******************************************************************************)
(* AG Code Foundations: Linear Code from a Generator Matrix                   *)
(*                                                                            *)
(* Defines a linear code as the image of a generator (evaluation) matrix and  *)
(* derives minimum distance bounds from an axiomatized Goppa weight bound.    *)
(* This lowers the axiomatization boundary for higher-genus coverings: instead *)
(* of axiomatizing an entire ThresholdScheme, we axiomatize at the code level *)
(* (generator matrix + Goppa bound) and derive the ThresholdScheme via        *)
(* Massey's construction (ag_massey_bridge.v).                                *)
(*                                                                            *)
(*   ag_code ev      == linear code {m *m ev | m : 'rV_k} as {vspace 'rV_n} *)
(*   ag_not_trivial  == ag_code is nontrivial when ev has full row rank       *)
(*   ag_min_dist_lb  == minimum distance >= n - (k + g - 1) from Goppa bound *)
(*   ag_min_dist_ge2 == minimum distance >= 2 when k + g < n                 *)
(******************************************************************************)

From HB Require Import structures.
From mathcomp Require Import all_ssreflect ssralg finalg zmodp.
From mathcomp Require Import matrix mxalgebra vector.
From infotheo Require Import ssr_ext ssralg_ext hamming linearcode.

Set Implicit Arguments.
Unset Strict Implicit.
Import Prenex Implicits.

Import GRing.Theory.
Open Scope ring_scope.

(******************************************************************************)
(*     Section 1: Code Definition from Generator Matrix                       *)
(******************************************************************************)

Section ag_code_def.

Variables (F : finFieldType) (n k : nat).
Variable ev : 'M[F]_(k, n).

(** The linear code generated by evaluation matrix ev: the vspace image
    {m *m ev | m : 'rV_k} of the message space under right-multiplication
    by ev. Working at this code level, rather than axiomatizing a full
    ThresholdScheme directly, lets the minimum-distance and dimension facts
    below be derived from ev and the Goppa weight bound alone. *)
Definition ag_code : Lcode0.t F n :=
  (linfun (mulmxr ev) @: fullv)%VS.

(** Every evaluation m *m ev lies in ag_code by construction. This is the
    membership witness the nontriviality and distance-bound arguments below
    build on to exhibit concrete codewords. *)
Lemma ag_code_eval (m : 'rV[F]_k) : m *m ev \in ag_code.
Proof.
apply/memv_imgP; exists m; first by apply: memvf.
by rewrite lfunE.
Qed.

(** A vector lies in ag_code exactly when it is m *m ev for some message m.
    This turns the vspace-image definition of ag_code into the
    message/codeword correspondence the rest of the file reasons in. *)
Lemma ag_code_memP (c : 'rV[F]_n) :
  reflect (exists m : 'rV[F]_k, c = m *m ev) (c \in ag_code).
Proof.
apply: (iffP memv_imgP).
- move=> [u _ ->]; exists u; by rewrite lfunE.
- move=> [m ->]; exists m; first by apply: memvf. by rewrite lfunE.
Qed.

(** When ev has full row rank, ag_code has dimension exactly k: the message
    space and the code coincide in size, so no two distinct messages
    collapse to the same codeword under evaluation. This size match is what
    lets a Massey secret-sharing scheme built on ag_code carry exactly k
    independent shares of secret data. *)
Lemma dim_ag_code : \rank ev = k -> \dim ag_code = k.
Proof.
move=> Hrank.
have Hfree : row_free ev by rewrite -row_leq_rank Hrank.
rewrite limg_dim_eq.
  rewrite dimvf dim_matrix.
  change (1 * k = k)%N.
  by rewrite mul1n.
apply/vspaceP => v; rewrite memv_cap memv0 memvf /=.
by rewrite memv_ker lfunE mulmx_free_eq0.
Qed.

End ag_code_def.

(******************************************************************************)
(*     Section 2: Code Properties from Goppa Weight Bound                     *)
(******************************************************************************)

Section ag_code_props.

Variables (F : finFieldType) (n k : nat).
Variable ev : 'M[F]_(k, n).
Hypothesis ev_rank : \rank ev = k.
Hypothesis k_gt0 : 0 < k.
Hypothesis le_kn : k <= n.

Variable g : nat.
Hypothesis goppa_wt :
  forall m : 'rV[F]_k, m != 0 -> n - (k + g - 1) <= wH (m *m ev).

(** Right-multiplication by a full-row-rank ev is injective on message
    vectors: distinct messages encode to distinct codewords. This is the
    cancellation property the nonzero-codeword and nontriviality arguments
    below depend on. *)
Lemma ag_mulmx_inj : forall m1 m2 : 'rV[F]_k,
  m1 *m ev = m2 *m ev -> m1 = m2.
Proof.
move=> m1 m2 Heq.
have Hfree : row_free ev by rewrite -row_leq_rank ev_rank.
exact: (row_free_inj Hfree Heq).
Qed.

(** A nonzero message encodes to a nonzero codeword, since ev is injective
    on messages. This is exactly the witness needed to show ag_code
    contains more than the zero vector. *)
Lemma ag_mulmx_neq0 (m : 'rV[F]_k) : m != 0 -> m *m ev != 0.
Proof.
move=> Hm; apply/negP => /eqP Habs.
have : m = 0 by apply: ag_mulmx_inj; rewrite Habs mul0mx.
by move/eqP; rewrite (negbTE Hm).
Qed.

(** Under full row rank of ev, ag_code is not the zero code: it contains a
    nonzero codeword. This nontriviality is the hypothesis the generic
    min_dist definition from linearcode.v requires before a distance bound
    can be stated at all. *)
Lemma ag_not_trivial : not_trivial (ag_code ev).
Proof.
have _ := (le_kn, goppa_wt).
apply/not_trivialP; apply/negP => /eqP H0.
have Hmem : delta_mx 0 (Ordinal k_gt0) *m ev \in ag_code ev by apply: ag_code_eval.
rewrite H0 memv0 in Hmem.
have Hm : (delta_mx 0 (Ordinal k_gt0) : 'rV[F]_k) != 0.
  (* Fallback (A002): extracting one entry from a row-vector equality
     is not a congruence over a matched head symbol; goal-level `congr`
     cannot operate on the opaque `delta_mx` / zero-vector heads. *)
  apply/negP => /eqP/(congr1 (fun m : 'rV_k => m 0 (Ordinal k_gt0))).
  by rewrite mxE !eqxx /= mxE => /eqP; rewrite oner_eq0.
by move: (ag_mulmx_neq0 Hm); rewrite (eqP Hmem) eqxx.
Qed.

(** The minimum distance of ag_code is at least n - (k + g - 1), transferring
    the axiomatized Goppa weight bound on individual codewords to a distance
    bound on the whole code. This is the AG-code's minimum-distance
    parameter that a Massey secret-sharing scheme built from ag_code
    inherits as its reconstruction threshold. *)
Lemma ag_min_dist_lb : n - (k + g - 1) <= min_dist ag_not_trivial.
Proof.
have [c [Hc [Hc0 HcwH]]] := min_dist_achieved ag_not_trivial.
rewrite -HcwH.
have /ag_code_memP [m Hm] := Hc.
have Hm0 : m != 0.
  apply/negP => /eqP Hm0; apply: Hc0.
  by rewrite Hm Hm0 mul0mx.
by rewrite Hm; apply: goppa_wt.
Qed.

(** When k + g < n, the minimum distance of ag_code exceeds 1. Stated as
    strict positivity of d - 1 rather than the raw arithmetic bound, this is
    the form a reconstruction/threshold argument over ag_code needs to
    conclude that distinct codewords stay distinguishable after dropping a
    coordinate. *)
Lemma ag_min_dist_ge2 : k + g < n -> 1 < min_dist ag_not_trivial.
Proof.
move=> Hlt.
apply: leq_trans ag_min_dist_lb.
rewrite ltn_subRL.
by rewrite subnK // (leq_trans k_gt0) // leq_addr.
Qed.

End ag_code_props.

Arguments ag_not_trivial {F n k} ev ev_rank k_gt0 le_kn {g} goppa_wt.
Arguments ag_min_dist_lb {F n k} ev ev_rank k_gt0 le_kn {g} goppa_wt.
Arguments ag_min_dist_ge2 {F n k} ev ev_rank k_gt0 le_kn {g} goppa_wt.
