(* Generated by gen_fidelity.py.  Do not edit by hand. *)
From mathcomp Require Import ssreflect ssrbool ssrfun eqtype ssrnat seq.
From mathcomp Require Import fintype tuple finfun finset fingroup perm.
From mathcomp Require Import bigop order ssrnum ssralg reals boolp lra.
From infotheo Require Import realType_ext fdist proba variation_dist entropy.
From pgg_smc Require Import pgg_interface pgg_session_types.
From pgg_smc Require Import pgg_monodromy_profile pgg_execution_plug.
From pgg_smc Require Import pgg_observed_execution pgg_analysis_status.
From pgg_smc Require Import pgg_instance pgg_functionality.
From pgg_smc Require Import pgg_sample_adapter pgg_weighted_words.
From pgg_smc Require Import pgg_collusion_bound var_dist_supp.
From pgg_smc Require Import pgl27_group pgl27_profile pgl27_run.
From pgg_smc Require Import pgl27_secrecy pgl27_mixing pgl27_word_privacy.
From pgg_smc Require Import pgl27_exec pgl27_models.
From pgg_smc Require Import pgg_analysis_manifest.
From pgg_smc Require Import pgg_tableau pgg_tableau_syntax.
From pgg_smc Require Import pgl27_rows pgl27_proximity.

Set Implicit Arguments.
Unset Strict Implicit.
Import Prenex Implicits.
Import GRing.Theory Num.Theory.

Local Open Scope fdist_scope.
Local Open Scope proba_scope.
Local Open Scope entropy_scope.
Local Open Scope ring_scope.

(* pgl27_rows.v *)
Check @pgl27_dealt.
Check @pgl27_static_obsE.
Check @pgl27_static_obs_funE.
Check @pgl27_exact_viewE.
Check @pgl27_exact_witness.
Check @pgl27_exact_leak4.
Check @pgl27_word_view_const.
Check @pgl27_word_cert.
Check @pgl27_row_exact_tableau.
Check @pgl27_row_word_tableau.
Check @pgl27_row_word_certE.
Check @pgl27_row_exact_rowE.
Check @pgl27_row_word_rowE.
Check @pgl27_row_exact_armE.
Check @pgl27_row_word_armE.
Check @pgl27_inline_dealt.
Check @pgl27_inline_paramsE.
Check @pgl27_reprice39.
Check @pgl27_row_word39.
Check @pgl27_row_word39_bind.
Check @pgl27_row_word39_bindE.
Check @pgl27_row_word39_armE.
Check @pgl27_word_sampled.
Check @pgl27_row_word_branch39.
Check @pgl27_row_word_branch39_armE.
Check @pgl27_reprice41.
Check @pgl27_word_reprice41_false.
Check @pgl27_word_target.
Check @pgl27_word_bridge.
Check @pgl27_word_restated.
Check @pgl27_word_view_indistinguishability_restated.
Check @pgl27_exact_target.
Check @pgl27_exact_bridge.
Check @pgl27_exact_restated.
Check @pgl27_exec_exact_view_indep_restated.
Check @pgl27_exact_view_secrecy.
Check @pgl27_word_same_statement.
Check @pgl27_exact_same_statement.
Check @pgl27_F.
Check @pgl27_FE.
Check @pgl27_realises_expected.

(* pgl27_proximity.v *)
Check @pgl27_prior_viewE.
Check @pgl27_prior_exact_witness.
Check @pgl27_row_prior_exact_tableau.
Check @pgl27_row_prior_exact_armE.
Check @pgl27_row_prior_exact_rowE.
Check @pgl27_word_secret.
Check @pgl27_word_proximity_close.
Check @pgl27_word_proximity_cert.
Check @pgl27_word_proximity_cert_idealE.
Check @pgl27_word_proximity_cert_epsE.
Check @pgl27_word_proximity_eps_halfE.
Check @pgl27_pow2_40_ge1.
Check @pgl27_pow2_40_gt0.
Check @pgl27_word_proximity_le39.
Check @pgl27_word_proximity_cert_eps_lt2.
Check @pgl27_row_word_proximity.
Check @pgl27_row_word_proximity_rowE.
Check @pgl27_row_word_proximity_armE.
Check @pgl27_row_word_families_sampledE.
Check @pgl27_row_word_obs_sampledE.
Check @pgl27_row_word_arm_neq.
Check @pgl27_word_view_proximity.
Check @pgl27_word_uniform_ideal_close_false.

(* pgl27_rows.v *)
Print Assumptions pgl27_static_obsE.
Print Assumptions pgl27_static_obs_funE.
Print Assumptions pgl27_exact_viewE.
Print Assumptions pgl27_exact_leak4.
Print Assumptions pgl27_word_view_const.
Print Assumptions pgl27_row_exact_tableau.
Print Assumptions pgl27_row_word_tableau.
Print Assumptions pgl27_row_word_certE.
Print Assumptions pgl27_row_exact_rowE.
Print Assumptions pgl27_row_word_rowE.
Print Assumptions pgl27_row_exact_armE.
Print Assumptions pgl27_row_word_armE.
Print Assumptions pgl27_inline_paramsE.
Print Assumptions pgl27_row_word39.
Print Assumptions pgl27_row_word39_bind.
Print Assumptions pgl27_row_word39_bindE.
Print Assumptions pgl27_row_word39_armE.
Print Assumptions pgl27_row_word_branch39.
Print Assumptions pgl27_row_word_branch39_armE.
Print Assumptions pgl27_word_reprice41_false.
Print Assumptions pgl27_word_bridge.
Print Assumptions pgl27_word_view_indistinguishability_restated.
Print Assumptions pgl27_exact_bridge.
Print Assumptions pgl27_exec_exact_view_indep_restated.
Print Assumptions pgl27_exact_view_secrecy.
Print Assumptions pgl27_FE.
Print Assumptions pgl27_realises_expected.

(* pgl27_proximity.v *)
Print Assumptions pgl27_prior_viewE.
Print Assumptions pgl27_row_prior_exact_tableau.
Print Assumptions pgl27_row_prior_exact_armE.
Print Assumptions pgl27_row_prior_exact_rowE.
Print Assumptions pgl27_word_proximity_close.
Print Assumptions pgl27_word_proximity_cert_idealE.
Print Assumptions pgl27_word_proximity_cert_epsE.
Print Assumptions pgl27_word_proximity_eps_halfE.
Print Assumptions pgl27_pow2_40_ge1.
Print Assumptions pgl27_pow2_40_gt0.
Print Assumptions pgl27_word_proximity_le39.
Print Assumptions pgl27_word_proximity_cert_eps_lt2.
Print Assumptions pgl27_row_word_proximity.
Print Assumptions pgl27_row_word_proximity_rowE.
Print Assumptions pgl27_row_word_proximity_armE.
Print Assumptions pgl27_row_word_families_sampledE.
Print Assumptions pgl27_row_word_obs_sampledE.
Print Assumptions pgl27_row_word_arm_neq.
Print Assumptions pgl27_word_view_proximity.
Print Assumptions pgl27_word_uniform_ideal_close_false.
