#!/usr/bin/env python3
"""Generate fidelity.v (against the staged text) and baseline.v (against
production) from one shared body.

Both files name every declaration of instances/pgl27/pgl27_rows.v and
instances/pgl27/pgl27_proximity.v that is not a recorded Fail, print its type
under one fixed scope block, and print the assumptions of every published
row, lemma, fact and theorem.  Only the Require line differs, so `diff` of
the two outputs is the check: a declaration whose statement or whose axiom
set changed when it moved would print differently.

The two files are written under production pgl27_rows.v's scope block: fdist,
proba, entropy, ring.  Production pgl27_proximity.v's is ring, fdist, proba,
so the declarations that move out of it are printed here under a different
innermost scope than they were written in.  That is deliberate: it is the
check that the re-scoping changes no statement.  A numeral or a notation that
resolved differently would make the two Check lines differ.

The name lists are read out of the two production files, so this generator
cannot drift from them.

Usage: python3 gen_fidelity.py
"""

import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, "..", "..", ".."))
PROD_ROWS = os.path.join(ROOT, "instances", "pgl27", "pgl27_rows.v")
PROD_PROX = os.path.join(ROOT, "instances", "pgl27", "pgl27_proximity.v")

import verify  # noqa: E402  (its strip_comments and items are the audited ones)

PRELUDE = r"""(* Generated by gen_fidelity.py.  Do not edit by hand. *)
From mathcomp Require Import ssreflect ssrbool ssrfun eqtype ssrnat seq.
From mathcomp Require Import fintype tuple finfun finset fingroup perm.
From mathcomp Require Import bigop order ssrnum ssralg reals boolp lra.
From infotheo Require Import realType_ext fdist proba variation_dist entropy.
From pgg_smc Require Import pgg_interface pgg_session_types.
From pgg_smc Require Import pgg_monodromy_profile pgg_execution_plug.
From pgg_smc Require Import pgg_observed_execution pgg_analysis_status.
From pgg_smc Require Import pgg_instance pgg_functionality.
From pgg_smc Require Import pgg_sample_adapter pgg_weighted_words.
From pgg_smc Require Import pgg_collusion_bound var_dist_supp.
From pgg_smc Require Import pgl27_group pgl27_profile pgl27_run.
From pgg_smc Require Import pgl27_secrecy pgl27_mixing pgl27_word_privacy.
From pgg_smc Require Import pgl27_exec pgl27_models.
From pgg_smc Require Import pgg_analysis_manifest.
From pgg_smc Require Import pgg_tableau pgg_tableau_syntax.
"""

SETTINGS = r"""
Set Implicit Arguments.
Unset Strict Implicit.
Import Prenex Implicits.
Import GRing.Theory Num.Theory.

Local Open Scope fdist_scope.
Local Open Scope proba_scope.
Local Open Scope entropy_scope.
Local Open Scope ring_scope.
"""

# The nine declarations only the staged tree has.  Each Definition is checked
# at its type, which a wrong body would still satisfy; what pins the bodies is
# the five equations, each of which holds by conversion against a production
# term.
NEW = r"""
Check @pgl27_algebraic_start.
Check @pgl27_dealt_executable.
Check @pgl27_exact_sampled.
Check @pgl27_prior_exact_sampled.
Check @pgl27_dealt_executable_paramsE.
Check @pgl27_dealt_executableE.
Check @pgl27_row_exact_sampledE.
Check @pgl27_row_word_sampledE.
Check @pgl27_row_prior_exact_sampledE.

Print Assumptions pgl27_algebraic_start.
Print Assumptions pgl27_dealt_executable.
Print Assumptions pgl27_exact_sampled.
Print Assumptions pgl27_prior_exact_sampled.
Print Assumptions pgl27_dealt_executable_paramsE.
Print Assumptions pgl27_dealt_executableE.
Print Assumptions pgl27_row_exact_sampledE.
Print Assumptions pgl27_row_word_sampledE.
Print Assumptions pgl27_row_prior_exact_sampledE.
"""

# Published rows: the Definitions whose assumptions are printed beside the
# lemmas.  Every other Definition is a payload or a prefix reached through one
# of these, and a Print Assumptions on a type naming pgl27_observed is slow.
ROWS_PRINTED = ["pgl27_row_exact_tableau", "pgl27_row_word_tableau",
                "pgl27_row_word39", "pgl27_row_word39_bind",
                "pgl27_row_word_branch39", "pgl27_row_prior_exact_tableau",
                "pgl27_row_word_proximity"]


def inventory():
    checks, prints = [], []
    for path in (PROD_ROWS, PROD_PROX):
        src = verify.strip_comments(open(path).read())
        head = "(* %s *)" % os.path.basename(path)
        checks.append("")
        checks.append(head)
        prints.append("")
        prints.append(head)
        for kind, name, _ in verify.items(src):
            if kind.startswith("Fail"):
                continue
            checks.append("Check @%s." % name)
            if kind != "Definition" or name in ROWS_PRINTED:
                prints.append("Print Assumptions %s." % name)
    return "\n".join(checks) + "\n", "\n".join(prints) + "\n"


CHECKS, PRINTS = inventory()


def write(name, require, extra):
    body = PRELUDE + require + SETTINGS + CHECKS + PRINTS + extra
    with open(os.path.join(HERE, name), "w") as f:
        f.write(body)
    n = len(re.findall(r"^Check @", body, re.M))
    m = len(re.findall(r"^Print Assumptions", body, re.M))
    print("wrote %-12s %d Check, %d Print Assumptions" % (name, n, m))


write("fidelity.v",
      "From pgg_smc Require Import pgl27_proximity.\n"
      "From pgg_smc Require Import pgl27_tableau_algebraic.\n"
      "From pgg_smc Require Import pgl27_tableau_executable.\n"
      "From pgg_smc Require Import pgl27_tableau_observed.\n"
      "From pgg_smc Require Import pgl27_tableau_sampled.\n"
      "From pgg_smc Require Import pgl27_tableau_analysis_bridged.\n"
      "From pgg_smc Require Import pgl27_tableau_checks.\n",
      NEW)

write("baseline.v",
      "From pgg_smc Require Import pgl27_rows pgl27_proximity.\n",
      "")
