(* infotheo: information theory and error-correcting codes in Rocq            *)
(* Copyright (C) 2025 infotheo authors, license: LGPL-2.1-or-later            *)
(******************************************************************************)
(* five_card_verifolio_algebraic: the five-card instance at the Algebraic level *)
(*                                                                            *)
(* The Algebraic level of a program holds an algebra and nothing besides, and *)
(* the proposition it carries is True. A reader shown only this file has been *)
(* shown which group cuts the deck, which scheme the dealer deals and which   *)
(* seats read, and no claim about a coalition, a run or a probability model.  *)
(* All seven published programs of this instance begin at that algebra, and   *)
(* the uniform analysis and Kim's two analyses first differ three levels      *)
(* above, at Sampled, where each names its own model.                         *)
(*                                                                            *)
(* The algebra is five_card_algebra of five_card_exec.v and is not restated   *)
(* here: the cyclic group generated by the rotation five_card_group.fc_sigma  *)
(* acts on the five card positions, den Boer's five-card scheme deals the     *)
(* layout of a pair of committed bits into those five cards and carries its   *)
(* own encoding, reconstruction and privacy obligation, and the five seats    *)
(* start at the five card positions in order. Two is the threshold the        *)
(* derived profile declares, so every statement above this file that          *)
(* quantifies over a coalition quantifies over at most one of the five seats. *)
(*                                                                            *)
(* What this file adds is that algebra read as the first line of a program,   *)
(* and the ideal function beside it. The one run mode of this instance is the *)
(* committed one, and the keyword rule that opens such a run begins at a      *)
(* Targeted and not at a PGGAlgebraic, so the two records belong together:    *)
(* five_card_target is the algebra paired with the conjunction of the two     *)
(* committed bits, and its tg_algebra field is five_card_algebra, the algebra *)
(* five_card_algebraic_start names. The three probability models the instance *)
(* analyses part three levels above, at Sampled, so what this file fixes is   *)
(* shared by every program the instance publishes.                            *)
(*                                                                            *)
(* Definitions:                                                               *)
(*   five_card_algebraic_start                                                *)
(*                           == the five-card algebra as a program at         *)
(*                              Algebraic                                     *)
(*   five_card_target        == the algebra with the ideal function a run of  *)
(*                              it computes                                   *)
(******************************************************************************)

From mathcomp Require Import ssreflect ssrbool ssrfun eqtype ssrnat seq.
From mathcomp Require Import fintype tuple finfun finset fingroup perm.
From mathcomp Require Import order ssrnum ssralg reals boolp.
From pgg_smc Require Import pgg_analysis_status.
From pgg_smc Require Import pgg_observed_execution.
From pgg_smc Require Import pgg_instance pgg_functionality.
From pgg_smc Require Import five_card_group five_card_program.
From pgg_smc Require Import den_boer_encoding den_boer_run.
From pgg_smc Require Import five_card_exec.
From pgg_smc Require Import pgg_verifolio.
From pgg_smc Require Import pgg_verifolio_syntax.

Set Implicit Arguments.
Unset Strict Implicit.
Import Prenex Implicits.
Import GRing.Theory Num.Theory.

Local Open Scope ring_scope.


(******************************************************************************)
(*     The algebra as the first line of a program                             *)
(******************************************************************************)

(** The five-card instance at the Algebraic level: the algebra alone, under
    True, the proposition that level carries. One run mode is built on this
    value, the committed one: the Executable file continues it into
    five_card_committed_executable, and five_card_committed_executableE
    identifies that value, with the three run facts adjoined, with the
    prefix all seven published programs continue from. *)
Definition five_card_algebraic_start : Verifolio Algebraic :=
  verifolio_start five_card_algebra.


(******************************************************************************)
(*     The ideal function the run computes                                    *)
(******************************************************************************)

(** The algebra together with the ideal function a run of it computes. A
    dealer-dealt run has the identity forced on it and writes no such
    record; a run whose input is committed by two parties does not, and the
    function has to be named. The prefix five_card_committed names the same
    one in its own functionality clause, and the two spellings are held
    together by five_card_realises_expected, which is reflexivity only while
    they agree. *)
Definition five_card_target : Targeted :=
  five_card_algebra functionality (fun ab : bool * bool => ab.1 && ab.2).
